// ============================================================
// EQUATION MISSION CONTROL 2.0 — 100+ Question Database
// Grade 6: Expressions, Formulae & Equations
// Comprehensive, kid-friendly 105+ question database across 5 stages
// ============================================================

import { MissionChallenge, MissionCampaign } from '../types';

// ============================================================
// ── STAGE 1: AVIONICS & FLIGHT COMPUTER (Algebraic Expressions - 21 Questions) ──
// ============================================================
export const STAGE_1_QUESTIONS: Omit<MissionChallenge, 'stageId' | 'stageIndex'>[] = [
  {
    id: 's1-01',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Flight Computer Expression',
    missionCode: 'AVN-01',
    bloomLevel: 'understand',
    points: 100,
    timeLimit: 35,
    briefingPrompt: 'Which algebraic expression means "5 more than x"?',
    options: [
      { value: 'x + 5', label: 'x + 5' },
      { value: '5x', label: '5x' },
      { value: 'x - 5', label: 'x - 5' },
      { value: '5 - x', label: '5 - x' },
    ],
    correctAnswer: 'x + 5',
    hint: '"More than" means we add: start with x and add 5.',
    educationalTakeaway: '"5 more than x" is written algebraically as x + 5.',
  },
  {
    id: 's1-02',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Booster Telemetry Channel',
    missionCode: 'AVN-02',
    bloomLevel: 'understand',
    points: 100,
    timeLimit: 35,
    briefingPrompt: 'Which expression means "twice a number n"?',
    options: [
      { value: '2n', label: '2n' },
      { value: 'n + 2', label: 'n + 2' },
      { value: 'n - 2', label: 'n - 2' },
      { value: 'n / 2', label: 'n ÷ 2' },
    ],
    correctAnswer: '2n',
    hint: '"Twice" means 2 times n (written as 2n).',
    educationalTakeaway: '"Twice a number n" means 2 multiplied by n, written as 2n.',
  },
  {
    id: 's1-03',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Cabin Pressure Channel',
    missionCode: 'AVN-03',
    bloomLevel: 'understand',
    points: 100,
    timeLimit: 35,
    briefingPrompt: 'Which expression means "4 less than y"?',
    options: [
      { value: 'y - 4', label: 'y - 4' },
      { value: '4 - y', label: '4 - y' },
      { value: '4y', label: '4y' },
      { value: 'y + 4', label: 'y + 4' },
    ],
    correctAnswer: 'y - 4',
    hint: '"4 less than y" means you start with y and subtract 4.',
    educationalTakeaway: '"4 less than y" means y minus 4, which is y - 4.',
  },
  {
    id: 's1-04',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'RCS Thruster Signal',
    missionCode: 'AVN-04',
    bloomLevel: 'apply',
    points: 110,
    timeLimit: 35,
    briefingPrompt: 'Which expression means "3 times x, plus 2"?',
    options: [
      { value: '3x + 2', label: '3x + 2' },
      { value: '2x + 3', label: '2x + 3' },
      { value: '3x - 2', label: '3x - 2' },
      { value: '3 + x', label: '3 + x' },
    ],
    correctAnswer: '3x + 2',
    hint: 'First multiply 3 by x (3x), then add 2 (+ 2).',
    educationalTakeaway: '"3 times x plus 2" is assembled as 3x + 2.',
  },
  {
    id: 's1-05',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Solar Array Voltage Bus',
    missionCode: 'AVN-05',
    bloomLevel: 'understand',
    points: 100,
    timeLimit: 35,
    briefingPrompt: 'Which expression means "the product of 7 and k"?',
    options: [
      { value: '7k', label: '7k' },
      { value: '7 + k', label: '7 + k' },
      { value: 'k - 7', label: 'k - 7' },
      { value: 'k / 7', label: 'k ÷ 7' },
    ],
    correctAnswer: '7k',
    hint: '"Product" means multiplication: 7 × k = 7k.',
    educationalTakeaway: 'The product of 7 and k is written as 7k.',
  },
  {
    id: 's1-06',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Thermal Shield Bus',
    missionCode: 'AVN-06',
    bloomLevel: 'understand',
    points: 100,
    timeLimit: 35,
    briefingPrompt: 'Which expression represents "a number p divided by 4"?',
    options: [
      { value: 'p / 4', label: 'p ÷ 4' },
      { value: '4p', label: '4p' },
      { value: 'p - 4', label: 'p - 4' },
      { value: '4 / p', label: '4 ÷ p' },
    ],
    correctAnswer: 'p / 4',
    hint: '"Divided by 4" puts 4 in the denominator: p ÷ 4.',
    educationalTakeaway: 'Dividing p by 4 is written as p ÷ 4 or p/4.',
  },
  {
    id: 's1-07',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Antenna Array Gain',
    missionCode: 'AVN-07',
    bloomLevel: 'understand',
    points: 100,
    timeLimit: 35,
    briefingPrompt: 'Which expression represents "8 less than 3 times m"?',
    options: [
      { value: '3m - 8', label: '3m - 8' },
      { value: '8 - 3m', label: '8 - 3m' },
      { value: '3(m - 8)', label: '3(m - 8)' },
      { value: '8m - 3', label: '8m - 3' },
    ],
    correctAnswer: '3m - 8',
    hint: 'First find 3 times m (3m), then take away 8 (- 8).',
    educationalTakeaway: '3m minus 8 gives 3m - 8.',
  },
  {
    id: 's1-08',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Sensor Grid Calibration',
    missionCode: 'AVN-08',
    bloomLevel: 'understand',
    points: 100,
    timeLimit: 35,
    briefingPrompt: 'Which expression means "the sum of 12 and w"?',
    options: [
      { value: '12 + w', label: '12 + w' },
      { value: '12w', label: '12w' },
      { value: '12 - w', label: '12 - w' },
      { value: 'w / 12', label: 'w ÷ 12' },
    ],
    correctAnswer: '12 + w',
    hint: '"Sum" means addition: 12 + w.',
    educationalTakeaway: 'The sum of 12 and w is 12 + w.',
  },
  {
    id: 's1-09',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Laser Gyro Alignment',
    missionCode: 'AVN-09',
    bloomLevel: 'understand',
    points: 100,
    timeLimit: 35,
    briefingPrompt: 'Which expression means "6 times the quantity (x + 3)"?',
    options: [
      { value: '6(x + 3)', label: '6(x + 3)' },
      { value: '6x + 3', label: '6x + 3' },
      { value: 'x + 18', label: 'x + 18' },
      { value: '6 + x + 3', label: '6 + x + 3' },
    ],
    correctAnswer: '6(x + 3)',
    hint: 'Parentheses wrap the quantity (x + 3), multiplied by 6.',
    educationalTakeaway: '6 times (x + 3) is written as 6(x + 3).',
  },
  {
    id: 's1-10',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Battery Storage Bank',
    missionCode: 'AVN-10',
    bloomLevel: 'understand',
    points: 100,
    timeLimit: 35,
    briefingPrompt: 'Which expression means "10 decreased by a number b"?',
    options: [
      { value: '10 - b', label: '10 - b' },
      { value: 'b - 10', label: 'b - 10' },
      { value: '10 / b', label: '10 ÷ b' },
      { value: '10b', label: '10b' },
    ],
    correctAnswer: '10 - b',
    hint: 'Start with 10 and decrease (subtract) b: 10 - b.',
    educationalTakeaway: '10 decreased by b is 10 - b.',
  },
  {
    id: 's1-11',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Oxygen Flow Gauge',
    missionCode: 'AVN-11',
    bloomLevel: 'understand',
    points: 100,
    timeLimit: 35,
    briefingPrompt: 'Which expression means "half of a number z"?',
    options: [
      { value: 'z / 2', label: 'z ÷ 2' },
      { value: '2z', label: '2z' },
      { value: 'z - 2', label: 'z - 2' },
      { value: 'z + 2', label: 'z + 2' },
    ],
    correctAnswer: 'z / 2',
    hint: 'Half means dividing by 2: z ÷ 2 or 1/2 z.',
    educationalTakeaway: 'Half of z is z ÷ 2.',
  },
  {
    id: 's1-12',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Gimbal Motor Frequency',
    missionCode: 'AVN-12',
    bloomLevel: 'understand',
    points: 100,
    timeLimit: 35,
    briefingPrompt: 'In the expression 8y + 5, what is the coefficient of y?',
    options: [
      { value: '8', label: '8' },
      { value: '5', label: '5' },
      { value: 'y', label: 'y' },
      { value: '13', label: '13' },
    ],
    correctAnswer: '8',
    hint: 'The coefficient is the number multiplying the variable (here, 8 multiplies y).',
    educationalTakeaway: 'In 8y + 5, 8 is the coefficient of y and 5 is the constant.',
  },
  {
    id: 's1-13',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Fuel Line Pressure Index',
    missionCode: 'AVN-13',
    bloomLevel: 'understand',
    points: 100,
    timeLimit: 35,
    briefingPrompt: 'In the expression 4x + 9, what is the constant term?',
    options: [
      { value: '9', label: '9' },
      { value: '4', label: '4' },
      { value: 'x', label: 'x' },
      { value: '4x', label: '4x' },
    ],
    correctAnswer: '9',
    hint: 'A constant is a number on its own without a variable.',
    educationalTakeaway: 'In 4x + 9, 9 is the constant term.',
  },
  {
    id: 's1-14',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Telemetry Multiplexer',
    missionCode: 'AVN-14',
    bloomLevel: 'apply',
    points: 110,
    timeLimit: 35,
    briefingPrompt: 'Which expression means "7 added to the product of 4 and c"?',
    options: [
      { value: '4c + 7', label: '4c + 7' },
      { value: '7c + 4', label: '7c + 4' },
      { value: '4(c + 7)', label: '4(c + 7)' },
      { value: '7 - 4c', label: '7 - 4c' },
    ],
    correctAnswer: '4c + 7',
    hint: 'Product of 4 and c is 4c, then add 7: 4c + 7.',
    educationalTakeaway: 'The product 4c plus 7 gives 4c + 7.',
  },
  {
    id: 's1-15',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Avionics Bus Router',
    missionCode: 'AVN-15',
    bloomLevel: 'understand',
    points: 100,
    timeLimit: 35,
    briefingPrompt: 'Which expression means "9 subtracted from 5 times x"?',
    options: [
      { value: '5x - 9', label: '5x - 9' },
      { value: '9 - 5x', label: '9 - 5x' },
      { value: '5(x - 9)', label: '5(x - 9)' },
      { value: '9x - 5', label: '9x - 5' },
    ],
    correctAnswer: '5x - 9',
    hint: '5 times x is 5x. Subtract 9 from it: 5x - 9.',
    educationalTakeaway: '5x - 9 represents 9 subtracted from 5x.',
  },
  {
    id: 's1-16',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Star Tracker Optical Feed',
    missionCode: 'AVN-16',
    bloomLevel: 'understand',
    points: 100,
    timeLimit: 35,
    briefingPrompt: 'Which expression means "a number t increased by 15"?',
    options: [
      { value: 't + 15', label: 't + 15' },
      { value: '15t', label: '15t' },
      { value: 't - 15', label: 't - 15' },
      { value: '15 - t', label: '15 - t' },
    ],
    correctAnswer: 't + 15',
    hint: '"Increased by" means addition: t + 15.',
    educationalTakeaway: 't increased by 15 is t + 15.',
  },
  {
    id: 's1-17',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Doppler Radar Channel',
    missionCode: 'AVN-17',
    bloomLevel: 'understand',
    points: 100,
    timeLimit: 35,
    briefingPrompt: 'Which expression means "the quotient of 36 and y"?',
    options: [
      { value: '36 / y', label: '36 ÷ y' },
      { value: 'y / 36', label: 'y ÷ 36' },
      { value: '36y', label: '36y' },
      { value: '36 - y', label: '36 - y' },
    ],
    correctAnswer: '36 / y',
    hint: 'Quotient of 36 and y means 36 divided by y (36 ÷ y).',
    educationalTakeaway: '36 ÷ y is the quotient of 36 and y.',
  },
  {
    id: 's1-18',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Inertial Measurement Unit',
    missionCode: 'AVN-18',
    bloomLevel: 'apply',
    points: 110,
    timeLimit: 35,
    briefingPrompt: 'Simplify by combining like terms: 3x + 5x = ?',
    options: [
      { value: '8x', label: '8x' },
      { value: '15x', label: '15x' },
      { value: '8x^2', label: '8x²' },
      { value: '8', label: '8' },
    ],
    correctAnswer: '8x',
    hint: 'Add the coefficients: 3 + 5 = 8, so 3x + 5x = 8x.',
    educationalTakeaway: '3x + 5x = 8x.',
  },
  {
    id: 's1-19',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Hydraulic Actuator Line',
    missionCode: 'AVN-19',
    bloomLevel: 'apply',
    points: 110,
    timeLimit: 35,
    briefingPrompt: 'Simplify: 7y - 2y = ?',
    options: [
      { value: '5y', label: '5y' },
      { value: '5', label: '5' },
      { value: '9y', label: '9y' },
      { value: '14y', label: '14y' },
    ],
    correctAnswer: '5y',
    hint: '7 minus 2 is 5, so 7y - 2y = 5y.',
    educationalTakeaway: '7y - 2y = 5y.',
  },
  {
    id: 's1-20',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Beacon Transponder',
    missionCode: 'AVN-20',
    bloomLevel: 'understand',
    points: 100,
    timeLimit: 35,
    briefingPrompt: 'Which expression means "triple a number k"?',
    options: [
      { value: '3k', label: '3k' },
      { value: 'k + 3', label: 'k + 3' },
      { value: 'k / 3', label: 'k ÷ 3' },
      { value: 'k^3', label: 'k³' },
    ],
    correctAnswer: '3k',
    hint: '"Triple" means multiply by 3: 3k.',
    educationalTakeaway: 'Triple a number k is 3k.',
  },
  {
    id: 's1-21',
    stageTitle: 'STAGE 1: AVIONICS CONFIGURATION',
    stageSubtitle: 'Telemetry Link Lock',
    missionCode: 'AVN-21',
    bloomLevel: 'apply',
    points: 110,
    timeLimit: 35,
    briefingPrompt: 'Which expression represents "10 more than twice w"?',
    options: [
      { value: '2w + 10', label: '2w + 10' },
      { value: '10w + 2', label: '10w + 2' },
      { value: '2(w + 10)', label: '2(w + 10)' },
      { value: '2w - 10', label: '2w - 10' },
    ],
    correctAnswer: '2w + 10',
    hint: 'Twice w is 2w, then add 10: 2w + 10.',
    educationalTakeaway: '2w + 10 represents 10 more than twice w.',
  },
];

// ============================================================
// ── STAGE 2: CRYOGENIC PROPELLANT LOADING (Variable Substitution - 21 Questions) ──
// ============================================================
export const STAGE_2_QUESTIONS: Omit<MissionChallenge, 'stageId' | 'stageIndex'>[] = [
  {
    id: 's2-01',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Liquid Oxygen Main Manifold',
    missionCode: 'PRP-SUB-01',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 3x + 4 when x = 5:',
    options: [
      { value: '19', label: '19' },
      { value: '15', label: '15' },
      { value: '12', label: '12' },
      { value: '23', label: '23' },
    ],
    correctAnswer: '19',
    hint: 'Substitute 5 for x: 3 × 5 = 15, then 15 + 4 = 19.',
    educationalTakeaway: '3(5) + 4 = 15 + 4 = 19.',
  },
  {
    id: 's2-02',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Hydrogen Booster Manifold',
    missionCode: 'PRP-SUB-02',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 20 - 2y when y = 7:',
    options: [
      { value: '6', label: '6' },
      { value: '14', label: '14' },
      { value: '8', label: '8' },
      { value: '4', label: '4' },
    ],
    correctAnswer: '6',
    hint: 'Substitute 7 for y: 2 × 7 = 14, then 20 - 14 = 6.',
    educationalTakeaway: '20 - 2(7) = 20 - 14 = 6.',
  },
  {
    id: 's2-03',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Methane Cryo Valve',
    missionCode: 'PRP-SUB-03',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 4m + 3 when m = 6:',
    options: [
      { value: '27', label: '27' },
      { value: '24', label: '24' },
      { value: '21', label: '21' },
      { value: '30', label: '30' },
    ],
    correctAnswer: '27',
    hint: 'Substitute 6 for m: 4 × 6 = 24, then 24 + 3 = 27.',
    educationalTakeaway: '4(6) + 3 = 24 + 3 = 27.',
  },
  {
    id: 's2-04',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Helium Purge System',
    missionCode: 'PRP-SUB-04',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 5(p - 2) when p = 8:',
    options: [
      { value: '30', label: '30' },
      { value: '38', label: '38' },
      { value: '25', label: '25' },
      { value: '40', label: '40' },
    ],
    correctAnswer: '30',
    hint: 'Inside parentheses first: 8 - 2 = 6. Then 5 × 6 = 30.',
    educationalTakeaway: '5(8 - 2) = 5(6) = 30.',
  },
  {
    id: 's2-05',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Nitrogen Pressurization Line',
    missionCode: 'PRP-SUB-05',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate a² + 5 when a = 4:',
    options: [
      { value: '21', label: '21' },
      { value: '13', label: '13' },
      { value: '16', label: '16' },
      { value: '25', label: '25' },
    ],
    correctAnswer: '21',
    hint: '4 squared is 4 × 4 = 16. Then 16 + 5 = 21.',
    educationalTakeaway: '4² + 5 = 16 + 5 = 21.',
  },
  {
    id: 's2-06',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Tank Pressure Ratio',
    missionCode: 'PRP-SUB-06',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 24 / k + 2 when k = 6:',
    options: [
      { value: '6', label: '6' },
      { value: '4', label: '4' },
      { value: '8', label: '8' },
      { value: '10', label: '10' },
    ],
    correctAnswer: '6',
    hint: '24 ÷ 6 = 4, then 4 + 2 = 6.',
    educationalTakeaway: '(24 ÷ 6) + 2 = 4 + 2 = 6.',
  },
  {
    id: 's2-07',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Boil-Off Vent Flow',
    missionCode: 'PRP-SUB-07',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 7x - 10 when x = 4:',
    options: [
      { value: '18', label: '18' },
      { value: '28', label: '28' },
      { value: '14', label: '14' },
      { value: '20', label: '20' },
    ],
    correctAnswer: '18',
    hint: '7 × 4 = 28. Then 28 - 10 = 18.',
    educationalTakeaway: '7(4) - 10 = 28 - 10 = 18.',
  },
  {
    id: 's2-08',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Ullage Pressure Regulator',
    missionCode: 'PRP-SUB-08',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 2(3n + 1) when n = 3:',
    options: [
      { value: '20', label: '20' },
      { value: '19', label: '19' },
      { value: '18', label: '18' },
      { value: '16', label: '16' },
    ],
    correctAnswer: '20',
    hint: 'Inside: 3(3) + 1 = 10. Then 2 × 10 = 20.',
    educationalTakeaway: '2(3(3) + 1) = 2(10) = 20.',
  },
  {
    id: 's2-09',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Turbopump RPM Index',
    missionCode: 'PRP-SUB-09',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 50 - 6w when w = 5:',
    options: [
      { value: '20', label: '20' },
      { value: '30', label: '30' },
      { value: '24', label: '24' },
      { value: '15', label: '15' },
    ],
    correctAnswer: '20',
    hint: '6 × 5 = 30. Then 50 - 30 = 20.',
    educationalTakeaway: '50 - 6(5) = 50 - 30 = 20.',
  },
  {
    id: 's2-10',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Igniter Voltage Gauge',
    missionCode: 'PRP-SUB-10',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 8 + 4z when z = 3:',
    options: [
      { value: '20', label: '20' },
      { value: '24', label: '24' },
      { value: '12', label: '12' },
      { value: '28', label: '28' },
    ],
    correctAnswer: '20',
    hint: '4 × 3 = 12. Then 8 + 12 = 20.',
    educationalTakeaway: '8 + 4(3) = 8 + 12 = 20.',
  },
  {
    id: 's2-11',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Cryo Chilldown Sensor',
    missionCode: 'PRP-SUB-11',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 30 / m + 5 when m = 5:',
    options: [
      { value: '11', label: '11' },
      { value: '10', label: '10' },
      { value: '12', label: '12' },
      { value: '6', label: '6' },
    ],
    correctAnswer: '11',
    hint: '30 ÷ 5 = 6. Then 6 + 5 = 11.',
    educationalTakeaway: '(30 ÷ 5) + 5 = 6 + 5 = 11.',
  },
  {
    id: 's2-12',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Gimbal Pressure Injector',
    missionCode: 'PRP-SUB-12',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate x² - 3 when x = 5:',
    options: [
      { value: '22', label: '22' },
      { value: '25', label: '25' },
      { value: '10', label: '10' },
      { value: '7', label: '7' },
    ],
    correctAnswer: '22',
    hint: '5² = 25. Then 25 - 3 = 22.',
    educationalTakeaway: '5² - 3 = 25 - 3 = 22.',
  },
  {
    id: 's2-13',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'LOX Mass Flow Sensor',
    missionCode: 'PRP-SUB-13',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 9 + 5k when k = 4:',
    options: [
      { value: '29', label: '29' },
      { value: '20', label: '20' },
      { value: '36', label: '36' },
      { value: '25', label: '25' },
    ],
    correctAnswer: '29',
    hint: '5 × 4 = 20. Then 9 + 20 = 29.',
    educationalTakeaway: '9 + 5(4) = 9 + 20 = 29.',
  },
  {
    id: 's2-14',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Regenerative Cooling Jacket',
    missionCode: 'PRP-SUB-14',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 6(y + 4) when y = 5:',
    options: [
      { value: '54', label: '54' },
      { value: '34', label: '34' },
      { value: '45', label: '45' },
      { value: '60', label: '60' },
    ],
    correctAnswer: '54',
    hint: 'Inside: 5 + 4 = 9. Then 6 × 9 = 54.',
    educationalTakeaway: '6(5 + 4) = 6(9) = 54.',
  },
  {
    id: 's2-15',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Hydrazine Thruster Ratio',
    missionCode: 'PRP-SUB-15',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 40 - 7c when c = 4:',
    options: [
      { value: '12', label: '12' },
      { value: '28', label: '28' },
      { value: '14', label: '14' },
      { value: '16', label: '16' },
    ],
    correctAnswer: '12',
    hint: '7 × 4 = 28. Then 40 - 28 = 12.',
    educationalTakeaway: '40 - 7(4) = 40 - 28 = 12.',
  },
  {
    id: 's2-16',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Fuel Density Monitor',
    missionCode: 'PRP-SUB-16',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 2a + 3b when a = 4 and b = 5:',
    options: [
      { value: '23', label: '23' },
      { value: '20', label: '20' },
      { value: '18', label: '18' },
      { value: '25', label: '25' },
    ],
    correctAnswer: '23',
    hint: '2(4) = 8 and 3(5) = 15. Then 8 + 15 = 23.',
    educationalTakeaway: '2(4) + 3(5) = 8 + 15 = 23.',
  },
  {
    id: 's2-17',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Cavitation Damper Valve',
    missionCode: 'PRP-SUB-17',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 100 - 8p when p = 6:',
    options: [
      { value: '52', label: '52' },
      { value: '48', label: '48' },
      { value: '54', label: '54' },
      { value: '62', label: '62' },
    ],
    correctAnswer: '52',
    hint: '8 × 6 = 48. Then 100 - 48 = 52.',
    educationalTakeaway: '100 - 8(6) = 100 - 48 = 52.',
  },
  {
    id: 's2-18',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Propellant Depletion Sensor',
    missionCode: 'PRP-SUB-18',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 3(x² - 1) when x = 3:',
    options: [
      { value: '24', label: '24' },
      { value: '27', label: '27' },
      { value: '18', label: '18' },
      { value: '30', label: '30' },
    ],
    correctAnswer: '24',
    hint: '3² = 9. 9 - 1 = 8. Then 3 × 8 = 24.',
    educationalTakeaway: '3(3² - 1) = 3(8) = 24.',
  },
  {
    id: 's2-19',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Liquid Nitrogen Coolant Sub-loop',
    missionCode: 'PRP-SUB-19',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 45 / t + 8 when t = 9:',
    options: [
      { value: '13', label: '13' },
      { value: '14', label: '14' },
      { value: '12', label: '12' },
      { value: '5', label: '5' },
    ],
    correctAnswer: '13',
    hint: '45 ÷ 9 = 5. Then 5 + 8 = 13.',
    educationalTakeaway: '(45 ÷ 9) + 8 = 5 + 8 = 13.',
  },
  {
    id: 's2-20',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Main Oxidizer Valve Arming',
    missionCode: 'PRP-SUB-20',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 12 + 7m when m = 4:',
    options: [
      { value: '40', label: '40' },
      { value: '28', label: '28' },
      { value: '36', label: '36' },
      { value: '44', label: '44' },
    ],
    correctAnswer: '40',
    hint: '7 × 4 = 28. Then 12 + 28 = 40.',
    educationalTakeaway: '12 + 7(4) = 12 + 28 = 40.',
  },
  {
    id: 's2-21',
    stageTitle: 'STAGE 2: CRYO PROPELLANT LOADING',
    stageSubtitle: 'Secondary Feed Coupler',
    missionCode: 'PRP-SUB-21',
    bloomLevel: 'apply',
    points: 120,
    timeLimit: 35,
    briefingPrompt: 'Evaluate 5(2x - 3) when x = 4:',
    options: [
      { value: '25', label: '25' },
      { value: '20', label: '20' },
      { value: '35', label: '35' },
      { value: '15', label: '15' },
    ],
    correctAnswer: '25',
    hint: 'Inside: 2(4) - 3 = 8 - 3 = 5. Then 5 × 5 = 25.',
    educationalTakeaway: '5(2(4) - 3) = 5(5) = 25.',
  },
];

// ============================================================
// ── STAGE 3: ENGINE THRUST BALANCING (One-Step Equations - 21 Questions) ──
// ============================================================
export const STAGE_3_QUESTIONS: Omit<MissionChallenge, 'stageId' | 'stageIndex'>[] = [
  {
    id: 's3-01',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Primary Nozzle Thrust Balance',
    missionCode: 'ENG-BAL-01',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Balance Engine 1: Solve x + 7 = 15 for x:',
    options: [
      { value: 'x = 8', label: 'x = 8' },
      { value: 'x = 7', label: 'x = 7' },
      { value: 'x = 9', label: 'x = 9' },
      { value: 'x = 22', label: 'x = 22' },
    ],
    correctAnswer: 'x = 8',
    hint: 'Subtract 7 from both sides: 15 - 7 = 8.',
    educationalTakeaway: 'x + 7 = 15  ⟹  x = 15 - 7 = 8.',
  },
  {
    id: 's3-02',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Left Solid Booster Gimbal',
    missionCode: 'ENG-BAL-02',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Balance Booster: Solve 4y = 36 for y:',
    options: [
      { value: 'y = 9', label: 'y = 9' },
      { value: 'y = 8', label: 'y = 8' },
      { value: 'y = 12', label: 'y = 12' },
      { value: 'y = 32', label: 'y = 32' },
    ],
    correctAnswer: 'y = 9',
    hint: 'Divide both sides by 4: 36 ÷ 4 = 9.',
    educationalTakeaway: '4y = 36  ⟹  y = 36 ÷ 4 = 9.',
  },
  {
    id: 's3-03',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Right Solid Booster Gimbal',
    missionCode: 'ENG-BAL-03',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Balance Booster: Solve m - 8 = 12 for m:',
    options: [
      { value: 'm = 20', label: 'm = 20' },
      { value: 'm = 4', label: 'm = 4' },
      { value: 'm = 18', label: 'm = 18' },
      { value: 'm = 24', label: 'm = 24' },
    ],
    correctAnswer: 'm = 20',
    hint: 'Add 8 to both sides: 12 + 8 = 20.',
    educationalTakeaway: 'm - 8 = 12  ⟹  m = 12 + 8 = 20.',
  },
  {
    id: 's3-04',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Center Turbopump Feed',
    missionCode: 'ENG-BAL-04',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Balance Fuel Line: Solve k / 5 = 7 for k:',
    options: [
      { value: 'k = 35', label: 'k = 35' },
      { value: 'k = 12', label: 'k = 12' },
      { value: 'k = 25', label: 'k = 25' },
      { value: 'k = 40', label: 'k = 40' },
    ],
    correctAnswer: 'k = 35',
    hint: 'Multiply both sides by 5: 7 × 5 = 35.',
    educationalTakeaway: 'k ÷ 5 = 7  ⟹  k = 7 × 5 = 35.',
  },
  {
    id: 's3-05',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Combustion Chamber Pressure',
    missionCode: 'ENG-BAL-05',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Balance Pressure: Solve 6n = 48 for n:',
    options: [
      { value: 'n = 8', label: 'n = 8' },
      { value: 'n = 7', label: 'n = 7' },
      { value: 'n = 9', label: 'n = 9' },
      { value: 'n = 6', label: 'n = 6' },
    ],
    correctAnswer: 'n = 8',
    hint: 'Divide both sides by 6: 48 ÷ 6 = 8.',
    educationalTakeaway: '6n = 48  ⟹  n = 48 ÷ 6 = 8.',
  },
  {
    id: 's3-06',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Ignition Spark Timing',
    missionCode: 'ENG-BAL-06',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Balance Ignition: Solve p + 14 = 30 for p:',
    options: [
      { value: 'p = 16', label: 'p = 16' },
      { value: 'p = 14', label: 'p = 14' },
      { value: 'p = 18', label: 'p = 18' },
      { value: 'p = 44', label: 'p = 44' },
    ],
    correctAnswer: 'p = 16',
    hint: 'Subtract 14 from both sides: 30 - 14 = 16.',
    educationalTakeaway: 'p + 14 = 30  ⟹  p = 16.',
  },
  {
    id: 's3-07',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Hydraulic Yaw Damper',
    missionCode: 'ENG-BAL-07',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Solve z - 15 = 25 for z:',
    options: [
      { value: 'z = 40', label: 'z = 40' },
      { value: 'z = 10', label: 'z = 10' },
      { value: 'z = 35', label: 'z = 35' },
      { value: 'z = 45', label: 'z = 45' },
    ],
    correctAnswer: 'z = 40',
    hint: 'Add 15 to both sides: 25 + 15 = 40.',
    educationalTakeaway: 'z - 15 = 25  ⟹  z = 40.',
  },
  {
    id: 's3-08',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Auxiliary Exhaust Duct',
    missionCode: 'ENG-BAL-08',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Solve 8w = 56 for w:',
    options: [
      { value: 'w = 7', label: 'w = 7' },
      { value: 'w = 6', label: 'w = 6' },
      { value: 'w = 8', label: 'w = 8' },
      { value: 'w = 9', label: 'w = 9' },
    ],
    correctAnswer: 'w = 7',
    hint: '56 ÷ 8 = 7.',
    educationalTakeaway: '8w = 56  ⟹  w = 7.',
  },
  {
    id: 's3-09',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Coolant Flow Rate',
    missionCode: 'ENG-BAL-09',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Solve x / 4 = 9 for x:',
    options: [
      { value: 'x = 36', label: 'x = 36' },
      { value: 'x = 32', label: 'x = 32' },
      { value: 'x = 28', label: 'x = 28' },
      { value: 'x = 40', label: 'x = 40' },
    ],
    correctAnswer: 'x = 36',
    hint: 'Multiply both sides by 4: 9 × 4 = 36.',
    educationalTakeaway: 'x ÷ 4 = 9  ⟹  x = 36.',
  },
  {
    id: 's3-10',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Throttle Valve Sync',
    missionCode: 'ENG-BAL-10',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Solve y + 19 = 50 for y:',
    options: [
      { value: 'y = 31', label: 'y = 31' },
      { value: 'y = 29', label: 'y = 29' },
      { value: 'y = 33', label: 'y = 33' },
      { value: 'y = 69', label: 'y = 69' },
    ],
    correctAnswer: 'y = 31',
    hint: '50 - 19 = 31.',
    educationalTakeaway: 'y + 19 = 50  ⟹  y = 31.',
  },
  {
    id: 's3-11',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Turbine Exhaust Port',
    missionCode: 'ENG-BAL-11',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Solve 9a = 81 for a:',
    options: [
      { value: 'a = 9', label: 'a = 9' },
      { value: 'a = 8', label: 'a = 8' },
      { value: 'a = 7', label: 'a = 7' },
      { value: 'a = 10', label: 'a = 10' },
    ],
    correctAnswer: 'a = 9',
    hint: '81 ÷ 9 = 9.',
    educationalTakeaway: '9a = 81  ⟹  a = 9.',
  },
  {
    id: 's3-12',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Vernier Steering Thruster',
    missionCode: 'ENG-BAL-12',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Solve b - 11 = 19 for b:',
    options: [
      { value: 'b = 30', label: 'b = 30' },
      { value: 'b = 28', label: 'b = 28' },
      { value: 'b = 8', label: 'b = 8' },
      { value: 'b = 32', label: 'b = 32' },
    ],
    correctAnswer: 'b = 30',
    hint: '19 + 11 = 30.',
    educationalTakeaway: 'b - 11 = 19  ⟹  b = 30.',
  },
  {
    id: 's3-13',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Nozzle Throat Pressure',
    missionCode: 'ENG-BAL-13',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Solve c / 7 = 8 for c:',
    options: [
      { value: 'c = 56', label: 'c = 56' },
      { value: 'c = 48', label: 'c = 48' },
      { value: 'c = 63', label: 'c = 63' },
      { value: 'c = 54', label: 'c = 54' },
    ],
    correctAnswer: 'c = 56',
    hint: '8 × 7 = 56.',
    educationalTakeaway: 'c ÷ 7 = 8  ⟹  c = 56.',
  },
  {
    id: 's3-14',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Ignition Flame Front',
    missionCode: 'ENG-BAL-14',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Solve 7d = 63 for d:',
    options: [
      { value: 'd = 9', label: 'd = 9' },
      { value: 'd = 8', label: 'd = 8' },
      { value: 'd = 7', label: 'd = 7' },
      { value: 'd = 6', label: 'd = 6' },
    ],
    correctAnswer: 'd = 9',
    hint: '63 ÷ 7 = 9.',
    educationalTakeaway: '7d = 63  ⟹  d = 9.',
  },
  {
    id: 's3-15',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Main Bell Expansion Ratio',
    missionCode: 'ENG-BAL-15',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Solve e + 27 = 60 for e:',
    options: [
      { value: 'e = 33', label: 'e = 33' },
      { value: 'e = 37', label: 'e = 37' },
      { value: 'e = 23', label: 'e = 23' },
      { value: 'e = 43', label: 'e = 43' },
    ],
    correctAnswer: 'e = 33',
    hint: '60 - 27 = 33.',
    educationalTakeaway: 'e + 27 = 60  ⟹  e = 33.',
  },
  {
    id: 's3-16',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Gimbal Vector Servo',
    missionCode: 'ENG-BAL-16',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Solve 12h = 72 for h:',
    options: [
      { value: 'h = 6', label: 'h = 6' },
      { value: 'h = 7', label: 'h = 7' },
      { value: 'h = 8', label: 'h = 8' },
      { value: 'h = 5', label: 'h = 5' },
    ],
    correctAnswer: 'h = 6',
    hint: '72 ÷ 12 = 6.',
    educationalTakeaway: '12h = 72  ⟹  h = 6.',
  },
  {
    id: 's3-17',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'SRB Hold-Down Bolt Pressure',
    missionCode: 'ENG-BAL-17',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Solve m - 23 = 17 for m:',
    options: [
      { value: 'm = 40', label: 'm = 40' },
      { value: 'm = 38', label: 'm = 38' },
      { value: 'm = 6', label: 'm = 6' },
      { value: 'm = 44', label: 'm = 44' },
    ],
    correctAnswer: 'm = 40',
    hint: '17 + 23 = 40.',
    educationalTakeaway: 'm - 23 = 17  ⟹  m = 40.',
  },
  {
    id: 's3-18',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Oxidizer Injector Dome',
    missionCode: 'ENG-BAL-18',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Solve n / 8 = 6 for n:',
    options: [
      { value: 'n = 48', label: 'n = 48' },
      { value: 'n = 42', label: 'n = 42' },
      { value: 'n = 56', label: 'n = 56' },
      { value: 'n = 36', label: 'n = 36' },
    ],
    correctAnswer: 'n = 48',
    hint: '6 × 8 = 48.',
    educationalTakeaway: 'n ÷ 8 = 6  ⟹  n = 48.',
  },
  {
    id: 's3-19',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Thrust Chamber Jacket',
    missionCode: 'ENG-BAL-19',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Solve 15p = 45 for p:',
    options: [
      { value: 'p = 3', label: 'p = 3' },
      { value: 'p = 4', label: 'p = 4' },
      { value: 'p = 5', label: 'p = 5' },
      { value: 'p = 2', label: 'p = 2' },
    ],
    correctAnswer: 'p = 3',
    hint: '45 ÷ 15 = 3.',
    educationalTakeaway: '15p = 45  ⟹  p = 3.',
  },
  {
    id: 's3-20',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Combustion Gas Generator',
    missionCode: 'ENG-BAL-20',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Solve q + 35 = 80 for q:',
    options: [
      { value: 'q = 45', label: 'q = 45' },
      { value: 'q = 55', label: 'q = 55' },
      { value: 'q = 35', label: 'q = 35' },
      { value: 'q = 40', label: 'q = 40' },
    ],
    correctAnswer: 'q = 45',
    hint: '80 - 35 = 45.',
    educationalTakeaway: 'q + 35 = 80  ⟹  q = 45.',
  },
  {
    id: 's3-21',
    stageTitle: 'STAGE 3: ENGINE EQUATION BALANCE',
    stageSubtitle: 'Thrust Vector Actuator Key',
    missionCode: 'ENG-BAL-21',
    bloomLevel: 'apply',
    points: 140,
    timeLimit: 35,
    briefingPrompt: 'Solve r / 6 = 12 for r:',
    options: [
      { value: 'r = 72', label: 'r = 72' },
      { value: 'r = 66', label: 'r = 66' },
      { value: 'r = 60', label: 'r = 60' },
      { value: 'r = 78', label: 'r = 78' },
    ],
    correctAnswer: 'r = 72',
    hint: '12 × 6 = 72.',
    educationalTakeaway: 'r ÷ 6 = 12  ⟹  r = 72.',
  },
];

// ============================================================
// ── STAGE 4: ORBITAL GUIDANCE & FORMULAE (Speed, Distance, Area, Perimeter - 21 Questions) ──
// ============================================================
export const STAGE_4_QUESTIONS: Omit<MissionChallenge, 'stageId' | 'stageIndex'>[] = [
  {
    id: 's4-01',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Low Earth Orbit Arc',
    missionCode: 'NAV-CAL-01',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Formula: Distance = Speed × Time. If Speed = 8 km/s and Time = 4 s, find Distance:',
    options: [
      { value: '32 km', label: '32 km' },
      { value: '12 km', label: '12 km' },
      { value: '2 km', label: '2 km' },
      { value: '24 km', label: '24 km' },
    ],
    correctAnswer: '32 km',
    hint: 'Distance = Speed × Time = 8 × 4 = 32.',
    educationalTakeaway: 'Distance = 8 km/s × 4 s = 32 km.',
  },
  {
    id: 's4-02',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Orbital Speed Calibration',
    missionCode: 'NAV-CAL-02',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Formula: Speed = Distance ÷ Time. A rocket travels 42 km in 6 seconds. What is its speed?',
    options: [
      { value: '7 km/s', label: '7 km/s' },
      { value: '6 km/s', label: '6 km/s' },
      { value: '8 km/s', label: '8 km/s' },
      { value: '36 km/s', label: '36 km/s' },
    ],
    correctAnswer: '7 km/s',
    hint: 'Divide distance by time: 42 ÷ 6 = 7 km/s.',
    educationalTakeaway: 'Speed = 42 km ÷ 6 s = 7 km/s.',
  },
  {
    id: 's4-03',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Telemetry Transmission Time',
    missionCode: 'NAV-CAL-03',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Formula: Time = Distance ÷ Speed. A signal travels 72 km at 8 km/s. How many seconds does it take?',
    options: [
      { value: '9 seconds', label: '9 seconds' },
      { value: '8 seconds', label: '8 seconds' },
      { value: '10 seconds', label: '10 seconds' },
      { value: '64 seconds', label: '64 seconds' },
    ],
    correctAnswer: '9 seconds',
    hint: 'Time = 72 ÷ 8 = 9 seconds.',
    educationalTakeaway: 'Time = 72 km ÷ 8 km/s = 9 seconds.',
  },
  {
    id: 's4-04',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Solar Panel Surface Area',
    missionCode: 'NAV-CAL-04',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Formula: Area = length × width. A solar panel is 6 m long and 4 m wide. What is its Area?',
    options: [
      { value: '24 m²', label: '24 m²' },
      { value: '20 m²', label: '20 m²' },
      { value: '10 m²', label: '10 m²' },
      { value: '28 m²', label: '28 m²' },
    ],
    correctAnswer: '24 m²',
    hint: 'Multiply length by width: 6 × 4 = 24 m².',
    educationalTakeaway: 'Area = 6 m × 4 m = 24 m².',
  },
  {
    id: 's4-05',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Launch Pad Perimeter',
    missionCode: 'NAV-CAL-05',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Formula: Perimeter = 2(length + width). If length = 8 m and width = 5 m, find the Perimeter:',
    options: [
      { value: '26 m', label: '26 m' },
      { value: '40 m', label: '40 m' },
      { value: '13 m', label: '13 m' },
      { value: '24 m', label: '24 m' },
    ],
    correctAnswer: '26 m',
    hint: '8 + 5 = 13. Then 2 × 13 = 26 m.',
    educationalTakeaway: 'Perimeter = 2(8 + 5) = 2(13) = 26 m.',
  },
  {
    id: 's4-06',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Cargo Bay Cube Volume',
    missionCode: 'NAV-CAL-06',
    bloomLevel: 'apply',
    points: 170,
    timeLimit: 40,
    briefingPrompt: 'Formula: Volume of cube = s³. If each side s = 3 m, what is the cargo volume?',
    options: [
      { value: '27 m³', label: '27 m³' },
      { value: '9 m³', label: '9 m³' },
      { value: '18 m³', label: '18 m³' },
      { value: '81 m³', label: '81 m³' },
    ],
    correctAnswer: '27 m³',
    hint: 'Volume = 3 × 3 × 3 = 27 m³.',
    educationalTakeaway: 'Volume = 3³ = 27 m³.',
  },
  {
    id: 's4-07',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Interplanetary Distance Arc',
    missionCode: 'NAV-CAL-07',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Distance = Speed × Time. If Speed = 11 km/s and Time = 5 s, find Distance:',
    options: [
      { value: '55 km', label: '55 km' },
      { value: '50 km', label: '50 km' },
      { value: '60 km', label: '60 km' },
      { value: '16 km', label: '16 km' },
    ],
    correctAnswer: '55 km',
    hint: '11 × 5 = 55 km.',
    educationalTakeaway: 'Distance = 11 × 5 = 55 km.',
  },
  {
    id: 's4-08',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Re-entry Velocity Check',
    missionCode: 'NAV-CAL-08',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Speed = Distance ÷ Time. A probe travels 90 km in 9 seconds. Find Speed:',
    options: [
      { value: '10 km/s', label: '10 km/s' },
      { value: '9 km/s', label: '9 km/s' },
      { value: '12 km/s', label: '12 km/s' },
      { value: '81 km/s', label: '81 km/s' },
    ],
    correctAnswer: '10 km/s',
    hint: '90 ÷ 9 = 10 km/s.',
    educationalTakeaway: 'Speed = 90 ÷ 9 = 10 km/s.',
  },
  {
    id: 's4-09',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Avionics Heat Radiator Area',
    missionCode: 'NAV-CAL-09',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Area = length × width. If length = 9 m and width = 7 m, find the Area:',
    options: [
      { value: '63 m²', label: '63 m²' },
      { value: '32 m²', label: '32 m²' },
      { value: '56 m²', label: '56 m²' },
      { value: '72 m²', label: '72 m²' },
    ],
    correctAnswer: '63 m²',
    hint: '9 × 7 = 63 m².',
    educationalTakeaway: 'Area = 9 × 7 = 63 m².',
  },
  {
    id: 's4-10',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Hatch Seal Perimeter',
    missionCode: 'NAV-CAL-10',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Perimeter of a square = 4s. If side s = 7 m, what is the Perimeter?',
    options: [
      { value: '28 m', label: '28 m' },
      { value: '49 m', label: '49 m' },
      { value: '14 m', label: '14 m' },
      { value: '32 m', label: '32 m' },
    ],
    correctAnswer: '28 m',
    hint: '4 × 7 = 28 m.',
    educationalTakeaway: 'Perimeter = 4(7) = 28 m.',
  },
  {
    id: 's4-11',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Escape Velocity Stage',
    missionCode: 'NAV-CAL-11',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Distance = Speed × Time. If Speed = 12 km/s and Time = 6 s, find Distance:',
    options: [
      { value: '72 km', label: '72 km' },
      { value: '68 km', label: '68 km' },
      { value: '76 km', label: '76 km' },
      { value: '18 km', label: '18 km' },
    ],
    correctAnswer: '72 km',
    hint: '12 × 6 = 72 km.',
    educationalTakeaway: 'Distance = 12 × 6 = 72 km.',
  },
  {
    id: 's4-12',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Radio Wave Duration',
    missionCode: 'NAV-CAL-12',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Time = Distance ÷ Speed. If Distance = 84 km and Speed = 12 km/s, find Time:',
    options: [
      { value: '7 seconds', label: '7 seconds' },
      { value: '8 seconds', label: '8 seconds' },
      { value: '6 seconds', label: '6 seconds' },
      { value: '9 seconds', label: '9 seconds' },
    ],
    correctAnswer: '7 seconds',
    hint: '84 ÷ 12 = 7 seconds.',
    educationalTakeaway: 'Time = 84 ÷ 12 = 7 seconds.',
  },
  {
    id: 's4-13',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Triangular Fin Area',
    missionCode: 'NAV-CAL-13',
    bloomLevel: 'apply',
    points: 170,
    timeLimit: 40,
    briefingPrompt: 'Formula: Area of triangle = ½ × base × height. If base = 8 m and height = 6 m, find Area:',
    options: [
      { value: '24 m²', label: '24 m²' },
      { value: '48 m²', label: '48 m²' },
      { value: '14 m²', label: '14 m²' },
      { value: '28 m²', label: '28 m²' },
    ],
    correctAnswer: '24 m²',
    hint: '8 × 6 = 48, then take half: 48 ÷ 2 = 24 m².',
    educationalTakeaway: 'Area = ½(8)(6) = 24 m².',
  },
  {
    id: 's4-14',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Rectangular Fuel Tank Volume',
    missionCode: 'NAV-CAL-14',
    bloomLevel: 'apply',
    points: 170,
    timeLimit: 40,
    briefingPrompt: 'Volume = length × width × height. If l = 4 m, w = 3 m, h = 5 m, find Volume:',
    options: [
      { value: '60 m³', label: '60 m³' },
      { value: '12 m³', label: '12 m³' },
      { value: '50 m³', label: '50 m³' },
      { value: '35 m³', label: '35 m³' },
    ],
    correctAnswer: '60 m³',
    hint: '4 × 3 × 5 = 60 m³.',
    educationalTakeaway: 'Volume = 4 × 3 × 5 = 60 m³.',
  },
  {
    id: 's4-15',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Orbital Perimeter Track',
    missionCode: 'NAV-CAL-15',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Perimeter = 2(l + w). If l = 15 km and w = 10 km, find Perimeter:',
    options: [
      { value: '50 km', label: '50 km' },
      { value: '150 km', label: '150 km' },
      { value: '25 km', label: '25 km' },
      { value: '60 km', label: '60 km' },
    ],
    correctAnswer: '50 km',
    hint: '15 + 10 = 25, then 2 × 25 = 50 km.',
    educationalTakeaway: 'Perimeter = 2(25) = 50 km.',
  },
  {
    id: 's4-16',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Hypersonic Cruise Stage',
    missionCode: 'NAV-CAL-16',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Speed = Distance ÷ Time. If Distance = 96 km in 8 seconds, find Speed:',
    options: [
      { value: '12 km/s', label: '12 km/s' },
      { value: '11 km/s', label: '11 km/s' },
      { value: '14 km/s', label: '14 km/s' },
      { value: '88 km/s', label: '88 km/s' },
    ],
    correctAnswer: '12 km/s',
    hint: '96 ÷ 8 = 12 km/s.',
    educationalTakeaway: 'Speed = 96 ÷ 8 = 12 km/s.',
  },
  {
    id: 's4-17',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Lunar Injection Burn Duration',
    missionCode: 'NAV-CAL-17',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Distance = Speed × Time. If Speed = 15 km/s and Time = 4 s, find Distance:',
    options: [
      { value: '60 km', label: '60 km' },
      { value: '55 km', label: '55 km' },
      { value: '65 km', label: '65 km' },
      { value: '19 km', label: '19 km' },
    ],
    correctAnswer: '60 km',
    hint: '15 × 4 = 60 km.',
    educationalTakeaway: 'Distance = 15 × 4 = 60 km.',
  },
  {
    id: 's4-18',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Shield Perimeter Ring',
    missionCode: 'NAV-CAL-18',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Perimeter of equilateral triangle = 3s. If side s = 9 m, find Perimeter:',
    options: [
      { value: '27 m', label: '27 m' },
      { value: '18 m', label: '18 m' },
      { value: '81 m', label: '81 m' },
      { value: '24 m', label: '24 m' },
    ],
    correctAnswer: '27 m',
    hint: '3 × 9 = 27 m.',
    educationalTakeaway: 'Perimeter = 3(9) = 27 m.',
  },
  {
    id: 's4-19',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Deep Space Probe Volume',
    missionCode: 'NAV-CAL-19',
    bloomLevel: 'apply',
    points: 170,
    timeLimit: 40,
    briefingPrompt: 'Cube Volume = s³. If side s = 4 m, find Volume:',
    options: [
      { value: '64 m³', label: '64 m³' },
      { value: '16 m³', label: '16 m³' },
      { value: '32 m³', label: '32 m³' },
      { value: '48 m³', label: '48 m³' },
    ],
    correctAnswer: '64 m³',
    hint: '4 × 4 × 4 = 64 m³.',
    educationalTakeaway: 'Volume = 4³ = 64 m³.',
  },
  {
    id: 's4-20',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Orbital Distance Arc',
    missionCode: 'NAV-CAL-20',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Distance = Speed × Time. If Speed = 7 km/s and Time = 8 s, find Distance:',
    options: [
      { value: '56 km', label: '56 km' },
      { value: '54 km', label: '54 km' },
      { value: '49 km', label: '49 km' },
      { value: '15 km', label: '15 km' },
    ],
    correctAnswer: '56 km',
    hint: '7 × 8 = 56 km.',
    educationalTakeaway: 'Distance = 7 × 8 = 56 km.',
  },
  {
    id: 's4-21',
    stageTitle: 'STAGE 4: NAVIGATION CALIBRATION',
    stageSubtitle: 'Solar Reflector Surface Area',
    missionCode: 'NAV-CAL-21',
    bloomLevel: 'apply',
    points: 160,
    timeLimit: 40,
    briefingPrompt: 'Area = length × width. If length = 12 m and width = 5 m, find Area:',
    options: [
      { value: '60 m²', label: '60 m²' },
      { value: '50 m²', label: '50 m²' },
      { value: '34 m²', label: '34 m²' },
      { value: '70 m²', label: '70 m²' },
    ],
    correctAnswer: '60 m²',
    hint: '12 × 5 = 60 m².',
    educationalTakeaway: 'Area = 12 × 5 = 60 m².',
  },
];

// ============================================================
// ── STAGE 5: LAUNCH INTERLOCK ARMING (Two-Step Equations - 21 Questions) ──
// ============================================================
export const STAGE_5_QUESTIONS: Omit<MissionChallenge, 'stageId' | 'stageIndex'>[] = [
  {
    id: 's5-01',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Arm Master Ignition Sequence',
    missionCode: 'LCH-ARM-01',
    bloomLevel: 'evaluate',
    points: 200,
    timeLimit: 45,
    briefingPrompt: 'Master Launch Key: Solve 2x + 2 = 10 for x:',
    options: [
      { value: 'x = 4', label: 'x = 4' },
      { value: 'x = 6', label: 'x = 6' },
      { value: 'x = 8', label: 'x = 8' },
      { value: 'x = 5', label: 'x = 5' },
    ],
    correctAnswer: 'x = 4',
    hint: 'Step 1: Subtract 2 from 10 (gives 8). Step 2: Divide by 2 (8 ÷ 2 = 4).',
    educationalTakeaway: '2x + 2 = 10  ⟹  2x = 8  ⟹  x = 4. Master launch key authorized!',
  },
  {
    id: 's5-02',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Stage Separation Interlock Key',
    missionCode: 'LCH-ARM-02',
    bloomLevel: 'evaluate',
    points: 200,
    timeLimit: 45,
    briefingPrompt: 'Master Launch Key: Solve 3x + 1 = 16 for x:',
    options: [
      { value: 'x = 5', label: 'x = 5' },
      { value: 'x = 4', label: 'x = 4' },
      { value: 'x = 6', label: 'x = 6' },
      { value: 'x = 3', label: 'x = 3' },
    ],
    correctAnswer: 'x = 5',
    hint: 'Step 1: Subtract 1 from 16 (gives 15). Step 2: Divide by 3 (15 ÷ 3 = 5).',
    educationalTakeaway: '3x + 1 = 16  ⟹  3x = 15  ⟹  x = 5. Stage clamps unlocked!',
  },
  {
    id: 's5-03',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Booster Thermal Bypass Key',
    missionCode: 'LCH-ARM-03',
    bloomLevel: 'evaluate',
    points: 210,
    timeLimit: 45,
    briefingPrompt: 'Master Launch Key: Solve 2x - 4 = 10 for x:',
    options: [
      { value: 'x = 7', label: 'x = 7' },
      { value: 'x = 3', label: 'x = 3' },
      { value: 'x = 6', label: 'x = 6' },
      { value: 'x = 14', label: 'x = 14' },
    ],
    correctAnswer: 'x = 7',
    hint: 'Step 1: Add 4 to 10 (gives 14). Step 2: Divide by 2 (14 ÷ 2 = 7).',
    educationalTakeaway: '2x - 4 = 10  ⟹  2x = 14  ⟹  x = 7. Booster bypass primed!',
  },
  {
    id: 's5-04',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Guidance Uplink Authorization',
    missionCode: 'LCH-ARM-04',
    bloomLevel: 'evaluate',
    points: 210,
    timeLimit: 45,
    briefingPrompt: 'Master Launch Key: Solve 4x + 2 = 18 for x:',
    options: [
      { value: 'x = 4', label: 'x = 4' },
      { value: 'x = 5', label: 'x = 5' },
      { value: 'x = 3', label: 'x = 3' },
      { value: 'x = 16', label: 'x = 16' },
    ],
    correctAnswer: 'x = 4',
    hint: 'Step 1: Subtract 2 from 18 (gives 16). Step 2: Divide by 4 (16 ÷ 4 = 4).',
    educationalTakeaway: '4x + 2 = 18  ⟹  4x = 16  ⟹  x = 4. All systems armed for liftoff!',
  },
  {
    id: 's5-05',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Main Ignition Countdown Key',
    missionCode: 'LCH-ARM-05',
    bloomLevel: 'evaluate',
    points: 220,
    timeLimit: 45,
    briefingPrompt: 'Master Launch Key: Solve 5x - 5 = 20 for x:',
    options: [
      { value: 'x = 5', label: 'x = 5' },
      { value: 'x = 3', label: 'x = 3' },
      { value: 'x = 4', label: 'x = 4' },
      { value: 'x = 25', label: 'x = 25' },
    ],
    correctAnswer: 'x = 5',
    hint: 'Step 1: Add 5 to 20 (gives 25). Step 2: Divide by 5 (25 ÷ 5 = 5).',
    educationalTakeaway: '5x - 5 = 20  ⟹  5x = 25  ⟹  x = 5. Ignition countdown enabled!',
  },
  {
    id: 's5-06',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Cryogenic Interlock Breaker',
    missionCode: 'LCH-ARM-06',
    bloomLevel: 'evaluate',
    points: 210,
    timeLimit: 45,
    briefingPrompt: 'Solve 3y + 7 = 28 for y:',
    options: [
      { value: 'y = 7', label: 'y = 7' },
      { value: 'y = 6', label: 'y = 6' },
      { value: 'y = 8', label: 'y = 8' },
      { value: 'y = 9', label: 'y = 9' },
    ],
    correctAnswer: 'y = 7',
    hint: '28 - 7 = 21. Then 21 ÷ 3 = 7.',
    educationalTakeaway: '3y = 21  ⟹  y = 7.',
  },
  {
    id: 's5-07',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Launch Gantry Release Key',
    missionCode: 'LCH-ARM-07',
    bloomLevel: 'evaluate',
    points: 210,
    timeLimit: 45,
    briefingPrompt: 'Solve 4m - 6 = 18 for m:',
    options: [
      { value: 'm = 6', label: 'm = 6' },
      { value: 'm = 5', label: 'm = 5' },
      { value: 'm = 7', label: 'm = 7' },
      { value: 'm = 8', label: 'm = 8' },
    ],
    correctAnswer: 'm = 6',
    hint: '18 + 6 = 24. Then 24 ÷ 4 = 6.',
    educationalTakeaway: '4m = 24  ⟹  m = 6.',
  },
  {
    id: 's5-08',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Main Booster Fuel Valve',
    missionCode: 'LCH-ARM-08',
    bloomLevel: 'evaluate',
    points: 210,
    timeLimit: 45,
    briefingPrompt: 'Solve 2p + 9 = 25 for p:',
    options: [
      { value: 'p = 8', label: 'p = 8' },
      { value: 'p = 7', label: 'p = 7' },
      { value: 'p = 9', label: 'p = 9' },
      { value: 'p = 6', label: 'p = 6' },
    ],
    correctAnswer: 'p = 8',
    hint: '25 - 9 = 16. Then 16 ÷ 2 = 8.',
    educationalTakeaway: '2p = 16  ⟹  p = 8.',
  },
  {
    id: 's5-09',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Flight Computer Master Passcode',
    missionCode: 'LCH-ARM-09',
    bloomLevel: 'evaluate',
    points: 220,
    timeLimit: 45,
    briefingPrompt: 'Solve 6n + 3 = 39 for n:',
    options: [
      { value: 'n = 6', label: 'n = 6' },
      { value: 'n = 7', label: 'n = 7' },
      { value: 'n = 5', label: 'n = 5' },
      { value: 'n = 8', label: 'n = 8' },
    ],
    correctAnswer: 'n = 6',
    hint: '39 - 3 = 36. Then 36 ÷ 6 = 6.',
    educationalTakeaway: '6n = 36  ⟹  n = 6.',
  },
  {
    id: 's5-10',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Umbilical Decouple Key',
    missionCode: 'LCH-ARM-10',
    bloomLevel: 'evaluate',
    points: 210,
    timeLimit: 45,
    briefingPrompt: 'Solve 5z - 8 = 27 for z:',
    options: [
      { value: 'z = 7', label: 'z = 7' },
      { value: 'z = 6', label: 'z = 6' },
      { value: 'z = 8', label: 'z = 8' },
      { value: 'z = 9', label: 'z = 9' },
    ],
    correctAnswer: 'z = 7',
    hint: '27 + 8 = 35. Then 35 ÷ 5 = 7.',
    educationalTakeaway: '5z = 35  ⟹  z = 7.',
  },
  {
    id: 's5-11',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Telemetry Encoder Link',
    missionCode: 'LCH-ARM-11',
    bloomLevel: 'evaluate',
    points: 210,
    timeLimit: 45,
    briefingPrompt: 'Solve 3w - 9 = 21 for w:',
    options: [
      { value: 'w = 10', label: 'w = 10' },
      { value: 'w = 9', label: 'w = 9' },
      { value: 'w = 8', label: 'w = 8' },
      { value: 'w = 12', label: 'w = 12' },
    ],
    correctAnswer: 'w = 10',
    hint: '21 + 9 = 30. Then 30 ÷ 3 = 10.',
    educationalTakeaway: '3w = 30  ⟹  w = 10.',
  },
  {
    id: 's5-12',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Sound Suppression Deluge Arm',
    missionCode: 'LCH-ARM-12',
    bloomLevel: 'evaluate',
    points: 210,
    timeLimit: 45,
    briefingPrompt: 'Solve 4x + 8 = 36 for x:',
    options: [
      { value: 'x = 7', label: 'x = 7' },
      { value: 'x = 6', label: 'x = 6' },
      { value: 'x = 8', label: 'x = 8' },
      { value: 'x = 9', label: 'x = 9' },
    ],
    correctAnswer: 'x = 7',
    hint: '36 - 8 = 28. Then 28 ÷ 4 = 7.',
    educationalTakeaway: '4x = 28  ⟹  x = 7.',
  },
  {
    id: 's5-13',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Ignition Flame Trench Gate',
    missionCode: 'LCH-ARM-13',
    bloomLevel: 'evaluate',
    points: 220,
    timeLimit: 45,
    briefingPrompt: 'Solve 7y + 5 = 47 for y:',
    options: [
      { value: 'y = 6', label: 'y = 6' },
      { value: 'y = 7', label: 'y = 7' },
      { value: 'y = 5', label: 'y = 5' },
      { value: 'y = 8', label: 'y = 8' },
    ],
    correctAnswer: 'y = 6',
    hint: '47 - 5 = 42. Then 42 ÷ 7 = 6.',
    educationalTakeaway: '7y = 42  ⟹  y = 6.',
  },
  {
    id: 's5-14',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Core Engine Chilldown Arm',
    missionCode: 'LCH-ARM-14',
    bloomLevel: 'evaluate',
    points: 210,
    timeLimit: 45,
    briefingPrompt: 'Solve 2a - 7 = 19 for a:',
    options: [
      { value: 'a = 13', label: 'a = 13' },
      { value: 'a = 12', label: 'a = 12' },
      { value: 'a = 14', label: 'a = 14' },
      { value: 'a = 11', label: 'a = 11' },
    ],
    correctAnswer: 'a = 13',
    hint: '19 + 7 = 26. Then 26 ÷ 2 = 13.',
    educationalTakeaway: '2a = 26  ⟹  a = 13.',
  },
  {
    id: 's5-15',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Hydraulic Clamp Jettison Key',
    missionCode: 'LCH-ARM-15',
    bloomLevel: 'evaluate',
    points: 220,
    timeLimit: 45,
    briefingPrompt: 'Solve 8b + 4 = 52 for b:',
    options: [
      { value: 'b = 6', label: 'b = 6' },
      { value: 'b = 7', label: 'b = 7' },
      { value: 'b = 5', label: 'b = 5' },
      { value: 'b = 8', label: 'b = 8' },
    ],
    correctAnswer: 'b = 6',
    hint: '52 - 4 = 48. Then 48 ÷ 8 = 6.',
    educationalTakeaway: '8b = 48  ⟹  b = 6.',
  },
  {
    id: 's5-16',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Upper Stage Guidance Lock',
    missionCode: 'LCH-ARM-16',
    bloomLevel: 'evaluate',
    points: 210,
    timeLimit: 45,
    briefingPrompt: 'Solve 3c - 12 = 15 for c:',
    options: [
      { value: 'c = 9', label: 'c = 9' },
      { value: 'c = 8', label: 'c = 8' },
      { value: 'c = 10', label: 'c = 10' },
      { value: 'c = 7', label: 'c = 7' },
    ],
    correctAnswer: 'c = 9',
    hint: '15 + 12 = 27. Then 27 ÷ 3 = 9.',
    educationalTakeaway: '3c = 27  ⟹  c = 9.',
  },
  {
    id: 's5-17',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Main Booster Igniter Sync',
    missionCode: 'LCH-ARM-17',
    bloomLevel: 'evaluate',
    points: 220,
    timeLimit: 45,
    briefingPrompt: 'Solve 5d + 15 = 60 for d:',
    options: [
      { value: 'd = 9', label: 'd = 9' },
      { value: 'd = 8', label: 'd = 8' },
      { value: 'd = 10', label: 'd = 10' },
      { value: 'd = 7', label: 'd = 7' },
    ],
    correctAnswer: 'd = 9',
    hint: '60 - 15 = 45. Then 45 ÷ 5 = 9.',
    educationalTakeaway: '5d = 45  ⟹  d = 9.',
  },
  {
    id: 's5-18',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Range Safety Transponder Key',
    missionCode: 'LCH-ARM-18',
    bloomLevel: 'evaluate',
    points: 210,
    timeLimit: 45,
    briefingPrompt: 'Solve 4h - 10 = 30 for h:',
    options: [
      { value: 'h = 10', label: 'h = 10' },
      { value: 'h = 9', label: 'h = 9' },
      { value: 'h = 8', label: 'h = 8' },
      { value: 'h = 11', label: 'h = 11' },
    ],
    correctAnswer: 'h = 10',
    hint: '30 + 10 = 40. Then 40 ÷ 4 = 10.',
    educationalTakeaway: '4h = 40  ⟹  h = 10.',
  },
  {
    id: 's5-19',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Launch Director Final Key',
    missionCode: 'LCH-ARM-19',
    bloomLevel: 'evaluate',
    points: 220,
    timeLimit: 45,
    briefingPrompt: 'Solve 6k + 8 = 56 for k:',
    options: [
      { value: 'k = 8', label: 'k = 8' },
      { value: 'k = 7', label: 'k = 7' },
      { value: 'k = 9', label: 'k = 9' },
      { value: 'k = 6', label: 'k = 6' },
    ],
    correctAnswer: 'k = 8',
    hint: '56 - 8 = 48. Then 48 ÷ 6 = 8.',
    educationalTakeaway: '6k = 48  ⟹  k = 8.',
  },
  {
    id: 's5-20',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Terminal Count Enable',
    missionCode: 'LCH-ARM-20',
    bloomLevel: 'evaluate',
    points: 220,
    timeLimit: 45,
    briefingPrompt: 'Solve 9x - 11 = 70 for x:',
    options: [
      { value: 'x = 9', label: 'x = 9' },
      { value: 'x = 8', label: 'x = 8' },
      { value: 'x = 10', label: 'x = 10' },
      { value: 'x = 7', label: 'x = 7' },
    ],
    correctAnswer: 'x = 9',
    hint: '70 + 11 = 81. Then 81 ÷ 9 = 9.',
    educationalTakeaway: '9x = 81  ⟹  x = 9.',
  },
  {
    id: 's5-21',
    stageTitle: 'STAGE 5: FINAL LAUNCH EQUATION',
    stageSubtitle: 'Master Liftoff Sequence GO',
    missionCode: 'LCH-ARM-21',
    bloomLevel: 'evaluate',
    points: 250,
    timeLimit: 45,
    briefingPrompt: 'Solve 10x + 25 = 105 for x:',
    options: [
      { value: 'x = 8', label: 'x = 8' },
      { value: 'x = 7', label: 'x = 7' },
      { value: 'x = 9', label: 'x = 9' },
      { value: 'x = 10', label: 'x = 10' },
    ],
    correctAnswer: 'x = 8',
    hint: '105 - 25 = 80. Then 80 ÷ 10 = 8.',
    educationalTakeaway: '10x = 80  ⟹  x = 8. All ignition constraints satisfied!',
  },
];

// All 105+ questions combined in master list
export const ALL_MISSION_QUESTIONS: Omit<MissionChallenge, 'stageId' | 'stageIndex'>[] = [
  ...STAGE_1_QUESTIONS,
  ...STAGE_2_QUESTIONS,
  ...STAGE_3_QUESTIONS,
  ...STAGE_4_QUESTIONS,
  ...STAGE_5_QUESTIONS,
];
