// ============================================================
// SKILLIZEE ARCADE — BUILT-IN QUESTION BANK SEED (ALL 13 ACTIVITIES)
// Comprehensive Grade 6 mathematics curriculum questions for
// "OTHER QUESTIONS" (Built-in) across all 13 arcade activities.
// ============================================================

import { UniversalQuestion } from '@/types/questionBank';
import { ACTIVITIES_REGISTRY } from './activityRegistry';

const RAW_BUILT_IN_QUESTIONS: Omit<UniversalQuestion, 'topicId' | 'topicName'>[] = [

  // ────────────────────────────────────────────────────────────
  // ACTIVITY 01: MATH ESCAPE VAULT (Place Value & Decimals)
  // ────────────────────────────────────────────────────────────
  {
    id: 'vault_bi_01',
    source: 'built-in',
    activityId: 'math-escape-vault',
    activityName: 'Math Escape Vault',
    question: 'In the number 456,789, what is the value of the digit 5?',
    options: ['500', '5,000', '50,000', '500,000'],
    correctAnswer: 'C',
    explanation: 'The digit 5 is in the ten thousands place, so its value is 5 × 10,000 = 50,000.',
    difficulty: 'easy',
    tags: ['Place Value', 'Whole Numbers', 'Heist'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'vault_bi_02',
    source: 'built-in',
    activityId: 'math-escape-vault',
    activityName: 'Math Escape Vault',
    question: 'What is 3.456 rounded to the nearest hundredth?',
    options: ['3.4', '3.45', '3.46', '3.5'],
    correctAnswer: 'C',
    explanation: 'The thousandths digit is 6 (≥ 5), so we round the hundredths digit 5 up to 6, giving 3.46.',
    difficulty: 'easy',
    tags: ['Decimals', 'Rounding'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'vault_bi_03',
    source: 'built-in',
    activityId: 'math-escape-vault',
    activityName: 'Math Escape Vault',
    question: 'Evaluate the vault security pin code: 0.8 × 0.07',
    options: ['0.56', '0.056', '0.0056', '5.6'],
    correctAnswer: 'B',
    explanation: '8 × 7 = 56. With 1 + 2 = 3 decimal places total, the result is 0.056.',
    difficulty: 'medium',
    tags: ['Decimals', 'Multiplication'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'vault_bi_04',
    source: 'built-in',
    activityId: 'math-escape-vault',
    activityName: 'Math Escape Vault',
    question: 'Which of the following numbers is the greatest?',
    options: ['0.709', '0.79', '0.785', '0.7099'],
    correctAnswer: 'B',
    explanation: 'Comparing the tenths and hundredths places: 0.790 is greater than 0.785, 0.709, and 0.7099.',
    difficulty: 'easy',
    tags: ['Decimals', 'Comparing'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'vault_bi_05',
    source: 'built-in',
    activityId: 'math-escape-vault',
    activityName: 'Math Escape Vault',
    question: 'Solve for the laser bypass code: 42.6 ÷ 0.6',
    options: ['7.1', '71', '0.71', '710'],
    correctAnswer: 'B',
    explanation: 'Multiply numerator and denominator by 10: 426 ÷ 6 = 71.',
    difficulty: 'medium',
    tags: ['Decimals', 'Division'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'vault_bi_06',
    source: 'built-in',
    activityId: 'math-escape-vault',
    activityName: 'Math Escape Vault',
    question: 'What is the expanded form of 308.045?',
    options: [
      '300 + 8 + 4/10 + 5/100',
      '300 + 8 + 4/100 + 5/1000',
      '300 + 80 + 4/10 + 5/100',
      '30 + 8 + 4/100 + 5/1000',
    ],
    correctAnswer: 'B',
    explanation: '300 + 8 + 0.04 (4/100) + 0.005 (5/1000).',
    difficulty: 'medium',
    tags: ['Place Value', 'Expanded Form'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'vault_bi_07',
    source: 'built-in',
    activityId: 'math-escape-vault',
    activityName: 'Math Escape Vault',
    question: 'A gold bar weighs 12.375 kg. If the vault contains 8 gold bars, what is the total weight in kg?',
    options: ['98.0 kg', '99.0 kg', '99.5 kg', '100.0 kg'],
    correctAnswer: 'B',
    explanation: '12.375 × 8 = 99.000 kg.',
    difficulty: 'hard',
    tags: ['Decimals', 'Word Problem'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'vault_bi_08',
    source: 'built-in',
    activityId: 'math-escape-vault',
    activityName: 'Math Escape Vault',
    question: 'Express 7/8 as a decimal number to unlock the keypad.',
    options: ['0.875', '0.78', '0.85', '0.75'],
    correctAnswer: 'A',
    explanation: '7 ÷ 8 = 0.875.',
    difficulty: 'medium',
    tags: ['Decimals', 'Fractions to Decimals'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // ────────────────────────────────────────────────────────────
  // ACTIVITY 02: THE GREAT NUMBER RAILWAY (Operations & Rounding)
  // ────────────────────────────────────────────────────────────
  {
    id: 'railway_bi_01',
    source: 'built-in',
    activityId: 'number-railway',
    activityName: 'The Great Number Railway',
    question: 'What is the sum of 4,582 and 3,749?',
    options: ['8,231', '8,331', '8,321', '7,331'],
    correctAnswer: 'B',
    explanation: '4,582 + 3,749 = 8,331.',
    difficulty: 'easy',
    tags: ['Addition', 'Whole Numbers', 'Railway'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'railway_bi_02',
    source: 'built-in',
    activityId: 'number-railway',
    activityName: 'The Great Number Railway',
    question: 'Round 674,821 to the nearest ten thousand for the railway schedule.',
    options: ['670,000', '675,000', '680,000', '700,000'],
    correctAnswer: 'A',
    explanation: 'The thousands digit is 4 (< 5), so 674,821 rounds down to 670,000.',
    difficulty: 'easy',
    tags: ['Rounding', 'Large Numbers'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'railway_bi_03',
    source: 'built-in',
    activityId: 'number-railway',
    activityName: 'The Great Number Railway',
    question: 'Find the product of 45 × 120.',
    options: ['4,800', '5,400', '5,200', '5,600'],
    correctAnswer: 'B',
    explanation: '45 × 12 = 540, so 45 × 120 = 5,400.',
    difficulty: 'easy',
    tags: ['Multiplication', 'Mental Math'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'railway_bi_04',
    source: 'built-in',
    activityId: 'number-railway',
    activityName: 'The Great Number Railway',
    question: 'An express train travels 480 km in 6 hours. What is its average speed in km/h?',
    options: ['70 km/h', '75 km/h', '80 km/h', '85 km/h'],
    correctAnswer: 'C',
    explanation: 'Speed = Distance ÷ Time = 480 ÷ 6 = 80 km/h.',
    difficulty: 'medium',
    tags: ['Division', 'Word Problem', 'Speed'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'railway_bi_05',
    source: 'built-in',
    activityId: 'number-railway',
    activityName: 'The Great Number Railway',
    question: 'What is 1,000 - 347?',
    options: ['653', '663', '753', '643'],
    correctAnswer: 'A',
    explanation: '1,000 - 347 = 653.',
    difficulty: 'easy',
    tags: ['Subtraction', 'Mental Math'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'railway_bi_06',
    source: 'built-in',
    activityId: 'number-railway',
    activityName: 'The Great Number Railway',
    question: 'A train has 14 carriages. Each carriage seats 68 passengers. How many total seats are on the train?',
    options: ['852', '952', '962', '1,052'],
    correctAnswer: 'B',
    explanation: '14 × 68 = (10 × 68) + (4 × 68) = 680 + 272 = 952.',
    difficulty: 'medium',
    tags: ['Multiplication', 'Word Problem'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // ────────────────────────────────────────────────────────────
  // ACTIVITY 03: CARNIVAL OF CHANCE (Probability)
  // ────────────────────────────────────────────────────────────
  {
    id: 'carnival_bi_01',
    source: 'built-in',
    activityId: 'carnival-of-chance',
    activityName: 'Carnival of Chance',
    question: 'A carnival spinner is divided into 8 equal sections numbered 1 to 8. What is the probability of spinning an even number?',
    options: ['1/8', '1/4', '1/2', '3/8'],
    correctAnswer: 'C',
    explanation: 'The even numbers are 2, 4, 6, 8 (4 outcomes out of 8). 4/8 = 1/2.',
    difficulty: 'easy',
    tags: ['Probability', 'Spinner', 'Carnival'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'carnival_bi_02',
    source: 'built-in',
    activityId: 'carnival-of-chance',
    activityName: 'Carnival of Chance',
    question: 'A bag contains 5 red balls, 3 blue balls, and 2 yellow balls. What is the probability of drawing a blue ball?',
    options: ['3/10', '1/3', '3/7', '2/5'],
    correctAnswer: 'A',
    explanation: 'Total balls = 5 + 3 + 2 = 10. Blue balls = 3. P(Blue) = 3/10.',
    difficulty: 'easy',
    tags: ['Probability', 'Fractions'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'carnival_bi_03',
    source: 'built-in',
    activityId: 'carnival-of-chance',
    activityName: 'Carnival of Chance',
    question: 'If you roll a standard 6-sided die, what is the probability of rolling a number greater than 4?',
    options: ['1/6', '1/3', '1/2', '2/3'],
    correctAnswer: 'B',
    explanation: 'Numbers greater than 4 are 5 and 6 (2 outcomes). 2/6 = 1/3.',
    difficulty: 'easy',
    tags: ['Probability', 'Dice'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'carnival_bi_04',
    source: 'built-in',
    activityId: 'carnival-of-chance',
    activityName: 'Carnival of Chance',
    question: 'What is the probability of an impossible event happening?',
    options: ['0', '0.5', '1', '-1'],
    correctAnswer: 'A',
    explanation: 'The probability of an event that cannot happen is strictly 0 (0%).',
    difficulty: 'easy',
    tags: ['Probability', 'Concepts'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'carnival_bi_05',
    source: 'built-in',
    activityId: 'carnival-of-chance',
    activityName: 'Carnival of Chance',
    question: 'A coin is flipped twice. What is the probability of getting two Heads (H, H)?',
    options: ['1/2', '1/3', '1/4', '1/8'],
    correctAnswer: 'C',
    explanation: 'Sample space: {HH, HT, TH, TT} (4 equally likely outcomes). P(HH) = 1/4.',
    difficulty: 'medium',
    tags: ['Probability', 'Compound Events'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // ────────────────────────────────────────────────────────────
  // ACTIVITY 04: BLUEPRINT BLITZ (Shapes, Area & Volume)
  // ────────────────────────────────────────────────────────────
  {
    id: 'blueprint_bi_01',
    source: 'built-in',
    activityId: 'blueprint-blitz',
    activityName: 'Blueprint Blitz',
    question: 'What is the area of a rectangular building floor measuring 14 m by 8 m?',
    options: ['44 m²', '102 m²', '112 m²', '122 m²'],
    correctAnswer: 'C',
    explanation: 'Area = length × width = 14 × 8 = 112 m².',
    difficulty: 'easy',
    tags: ['Area', 'Geometry', 'Blueprint'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'blueprint_bi_02',
    source: 'built-in',
    activityId: 'blueprint-blitz',
    activityName: 'Blueprint Blitz',
    question: 'Calculate the volume of a rectangular prism water tank with length 5 m, width 4 m, and height 3 m.',
    options: ['60 m³', '45 m³', '30 m³', '24 m³'],
    correctAnswer: 'A',
    explanation: 'Volume = l × w × h = 5 × 4 × 3 = 60 m³.',
    difficulty: 'easy',
    tags: ['Volume', '3D Shapes'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'blueprint_bi_03',
    source: 'built-in',
    activityId: 'blueprint-blitz',
    activityName: 'Blueprint Blitz',
    question: 'What is the perimeter of a regular hexagon with side length 7.5 cm?',
    options: ['37.5 cm', '45.0 cm', '52.5 cm', '60.0 cm'],
    correctAnswer: 'B',
    explanation: 'A regular hexagon has 6 equal sides. Perimeter = 6 × 7.5 = 45 cm.',
    difficulty: 'medium',
    tags: ['Perimeter', 'Polygons'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'blueprint_bi_04',
    source: 'built-in',
    activityId: 'blueprint-blitz',
    activityName: 'Blueprint Blitz',
    question: 'Find the area of a triangle with base 16 cm and perpendicular height 9 cm.',
    options: ['144 cm²', '72 cm²', '64 cm²', '81 cm²'],
    correctAnswer: 'B',
    explanation: 'Area = (1/2) × base × height = (1/2) × 16 × 9 = 8 × 9 = 72 cm².',
    difficulty: 'medium',
    tags: ['Area', 'Triangles'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // ────────────────────────────────────────────────────────────
  // ACTIVITY 05: EQUATION MISSION CONTROL (Expressions & Equations)
  // ────────────────────────────────────────────────────────────
  {
    id: 'equation_bi_01',
    source: 'built-in',
    activityId: 'equation-mission-control',
    activityName: 'Equation Mission Control',
    question: 'Solve for the rocket thruster power x: 3x + 7 = 28',
    options: ['5', '7', '8', '9'],
    correctAnswer: 'B',
    explanation: 'Subtract 7 from both sides: 3x = 21. Divide by 3: x = 7.',
    difficulty: 'easy',
    tags: ['Equations', 'Algebra', 'Mission Control'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'equation_bi_02',
    source: 'built-in',
    activityId: 'equation-mission-control',
    activityName: 'Equation Mission Control',
    question: 'Evaluate the algebraic expression 4n - 5 when n = 6.',
    options: ['19', '21', '24', '29'],
    correctAnswer: 'A',
    explanation: '4(6) - 5 = 24 - 5 = 19.',
    difficulty: 'easy',
    tags: ['Expressions', 'Substitution'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'equation_bi_03',
    source: 'built-in',
    activityId: 'equation-mission-control',
    activityName: 'Equation Mission Control',
    question: 'Simplify the telemetry formula: 5a + 3b + 2a - b',
    options: ['7a + 4b', '7a + 2b', '10ab', '7a - 2b'],
    correctAnswer: 'B',
    explanation: 'Combine like terms: (5a + 2a) + (3b - b) = 7a + 2b.',
    difficulty: 'medium',
    tags: ['Expressions', 'Simplifying'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'equation_bi_04',
    source: 'built-in',
    activityId: 'equation-mission-control',
    activityName: 'Equation Mission Control',
    question: 'Solve for orbital velocity v: v/4 = 15',
    options: ['3.75', '45', '60', '75'],
    correctAnswer: 'C',
    explanation: 'Multiply both sides by 4: v = 15 × 4 = 60.',
    difficulty: 'easy',
    tags: ['Equations', 'One-Step Equations'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // ────────────────────────────────────────────────────────────
  // ACTIVITY 06: PATTERN RACERS (Sequences & Functions)
  // ────────────────────────────────────────────────────────────
  {
    id: 'patterns_bi_01',
    source: 'built-in',
    activityId: 'pattern-racers',
    activityName: 'Pattern Racers',
    question: 'Find the next term in the race lap sequence: 4, 9, 14, 19, ?',
    options: ['22', '23', '24', '25'],
    correctAnswer: 'C',
    explanation: 'The common difference is +5. 19 + 5 = 24.',
    difficulty: 'easy',
    tags: ['Sequences', 'Arithmetic', 'Racing'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'patterns_bi_02',
    source: 'built-in',
    activityId: 'pattern-racers',
    activityName: 'Pattern Racers',
    question: 'What is the nth term rule for the sequence 3, 7, 11, 15, 19...?',
    options: ['4n - 1', '4n + 1', '3n + 1', '2n + 1'],
    correctAnswer: 'A',
    explanation: 'The difference is 4. When n = 1, 4(1) - 1 = 3. The rule is 4n - 1.',
    difficulty: 'medium',
    tags: ['Sequences', 'nth Term'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'patterns_bi_03',
    source: 'built-in',
    activityId: 'pattern-racers',
    activityName: 'Pattern Racers',
    question: 'Find the 10th term in the sequence given by rule 5n + 2.',
    options: ['48', '50', '52', '55'],
    correctAnswer: 'C',
    explanation: '5(10) + 2 = 50 + 2 = 52.',
    difficulty: 'easy',
    tags: ['Functions', 'Sequences'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // ────────────────────────────────────────────────────────────
  // ACTIVITY 07: DECIMAL DELIVERY (Decimals)
  // ────────────────────────────────────────────────────────────
  {
    id: 'decimals_bi_01',
    source: 'built-in',
    activityId: 'decimal-delivery',
    activityName: 'Decimal Delivery',
    question: 'A delivery truck carries 3 parcels weighing 4.25 kg, 6.8 kg, and 12.05 kg. What is the total payload in kg?',
    options: ['22.1 kg', '23.1 kg', '23.0 kg', '22.9 kg'],
    correctAnswer: 'B',
    explanation: '4.25 + 6.80 + 12.05 = 23.10 kg.',
    difficulty: 'easy',
    tags: ['Decimals', 'Addition', 'Delivery'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'decimals_bi_02',
    source: 'built-in',
    activityId: 'decimal-delivery',
    activityName: 'Decimal Delivery',
    question: 'A courier drives 8.4 km on Monday and 3.75 km on Tuesday. How much further did they drive on Monday?',
    options: ['4.65 km', '4.75 km', '5.35 km', '4.35 km'],
    correctAnswer: 'A',
    explanation: '8.40 - 3.75 = 4.65 km.',
    difficulty: 'easy',
    tags: ['Decimals', 'Subtraction'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'decimals_bi_03',
    source: 'built-in',
    activityId: 'decimal-delivery',
    activityName: 'Decimal Delivery',
    question: 'Calculate the total postage for 15 packages costing £2.40 each.',
    options: ['£32.00', '£34.00', '£36.00', '£38.00'],
    correctAnswer: 'C',
    explanation: '15 × 2.40 = 36.00.',
    difficulty: 'medium',
    tags: ['Decimals', 'Money'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // ────────────────────────────────────────────────────────────
  // ACTIVITY 08: THE SOLAR FORGE (Angles, Protractor & Constructions)
  // ────────────────────────────────────────────────────────────
  {
    id: 'solar_bi_01',
    source: 'built-in',
    activityId: 'solar-forge',
    activityName: 'The Solar Forge',
    question: 'The heliostat mirror is aligned at 135°. What type of angle is 135°?',
    options: ['Acute Angle', 'Right Angle', 'Obtuse Angle', 'Reflex Angle'],
    correctAnswer: 'C',
    explanation: 'An angle between 90° and 180° is an obtuse angle.',
    difficulty: 'easy',
    tags: ['Angles', 'Classification', 'Solar Forge'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'solar_bi_02',
    source: 'built-in',
    activityId: 'solar-forge',
    activityName: 'The Solar Forge',
    question: 'Two angles on a straight line add up to 180°. If one angle is 65°, what is the other angle?',
    options: ['115°', '125°', '105°', '135°'],
    correctAnswer: 'A',
    explanation: '180° - 65° = 115°.',
    difficulty: 'easy',
    tags: ['Angles', 'Straight Line'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'solar_bi_03',
    source: 'built-in',
    activityId: 'solar-forge',
    activityName: 'The Solar Forge',
    question: 'What is the sum of the interior angles of any triangle?',
    options: ['90°', '180°', '270°', '360°'],
    correctAnswer: 'B',
    explanation: 'The interior angles of any triangle always sum to 180°.',
    difficulty: 'easy',
    tags: ['Angles', 'Triangles'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'solar_bi_04',
    source: 'built-in',
    activityId: 'solar-forge',
    activityName: 'The Solar Forge',
    question: 'The solar tracker rotates from 12:00 PM to 4:00 PM on a sundial (30° per hour). What is the total angle turned?',
    options: ['90°', '120°', '150°', '180°'],
    correctAnswer: 'B',
    explanation: '4 hours × 30° per hour = 120°.',
    difficulty: 'medium',
    tags: ['Angles', 'Clock & Sundial'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // ────────────────────────────────────────────────────────────
  // ACTIVITY 09: THE CHOCOLATE FACTORY (Fractions)
  // ────────────────────────────────────────────────────────────
  {
    id: 'choco_bi_01',
    source: 'built-in',
    activityId: 'chocolate-factory',
    activityName: 'The Chocolate Factory',
    question: 'What is 3/4 + 2/3 written in simplest form?',
    options: ['5/7', '17/12', '1 5/12', '1 1/12'],
    correctAnswer: 'C',
    explanation: 'Common denominator is 12: (9/12) + (8/12) = 17/12 = 1 5/12.',
    difficulty: 'medium',
    tags: ['Fractions', 'Addition', 'Chocolate'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'choco_bi_02',
    source: 'built-in',
    activityId: 'chocolate-factory',
    activityName: 'The Chocolate Factory',
    question: 'Multiply the recipe batch fractions: 2/5 × 3/4',
    options: ['6/20', '3/10', '5/9', '8/15'],
    correctAnswer: 'B',
    explanation: '(2 × 3) / (5 × 4) = 6/20, which simplifies to 3/10.',
    difficulty: 'easy',
    tags: ['Fractions', 'Multiplication'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'choco_bi_03',
    source: 'built-in',
    activityId: 'chocolate-factory',
    activityName: 'The Chocolate Factory',
    question: 'Divide the chocolate vat: 4/5 ÷ 2/3',
    options: ['6/5', '1 1/5', '8/15', '5/6'],
    correctAnswer: 'B',
    explanation: '4/5 × 3/2 = 12/10 = 6/5 = 1 1/5.',
    difficulty: 'medium',
    tags: ['Fractions', 'Division'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // ────────────────────────────────────────────────────────────
  // ACTIVITY 10: GRAPHWORKS (Data Handling & Graphs)
  // ────────────────────────────────────────────────────────────
  {
    id: 'graphs_bi_01',
    source: 'built-in',
    activityId: 'graphworks',
    activityName: 'Graphworks',
    question: 'The daily temperatures in the city this week were: 18°C, 22°C, 19°C, 25°C, 21°C. What is the mean temperature?',
    options: ['20°C', '21°C', '22°C', '23°C'],
    correctAnswer: 'B',
    explanation: 'Sum = 18 + 22 + 19 + 25 + 21 = 105. Mean = 105 ÷ 5 = 21°C.',
    difficulty: 'easy',
    tags: ['Mean', 'Data Handling', 'Graphs'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'graphs_bi_02',
    source: 'built-in',
    activityId: 'graphworks',
    activityName: 'Graphworks',
    question: 'Find the median of the data set: 14, 8, 22, 16, 19, 11, 25.',
    options: ['14', '16', '19', '17.5'],
    correctAnswer: 'B',
    explanation: 'Sorted in ascending order: 8, 11, 14, 16, 19, 22, 25. The middle value is 16.',
    difficulty: 'easy',
    tags: ['Median', 'Statistics'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'graphs_bi_03',
    source: 'built-in',
    activityId: 'graphworks',
    activityName: 'Graphworks',
    question: 'In a pie chart with 360°, a category represents 25% of the data. What angle should the sector be?',
    options: ['45°', '60°', '90°', '120°'],
    correctAnswer: 'C',
    explanation: '25% of 360° = 0.25 × 360° = 90°.',
    difficulty: 'medium',
    tags: ['Pie Charts', 'Percentages', 'Angles'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // ────────────────────────────────────────────────────────────
  // ACTIVITY 11: PERCENTAGE HARVEST (Percentages)
  // ────────────────────────────────────────────────────────────
  {
    id: 'harvest_bi_01',
    source: 'built-in',
    activityId: 'percentage-harvest',
    activityName: 'Percentage Harvest',
    question: 'What is 35% of 240 kg of wheat harvested on the farm?',
    options: ['72 kg', '84 kg', '88 kg', '92 kg'],
    correctAnswer: 'B',
    explanation: '10% of 240 = 24. 30% = 72. 5% = 12. 72 + 12 = 84 kg.',
    difficulty: 'easy',
    tags: ['Percentages', 'Harvest', 'Farm'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'harvest_bi_02',
    source: 'built-in',
    activityId: 'percentage-harvest',
    activityName: 'Percentage Harvest',
    question: 'A tractor was priced at £800. In a seasonal harvest sale, it is discounted by 15%. What is the sale price?',
    options: ['£680', '£690', '£700', '£720'],
    correctAnswer: 'A',
    explanation: '15% of £800 = £120. Sale price = £800 - £120 = £680.',
    difficulty: 'medium',
    tags: ['Percentages', 'Discounts'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'harvest_bi_03',
    source: 'built-in',
    activityId: 'percentage-harvest',
    activityName: 'Percentage Harvest',
    question: 'Convert 3/5 into a percentage.',
    options: ['30%', '50%', '60%', '75%'],
    correctAnswer: 'C',
    explanation: '3/5 = 60/100 = 60%.',
    difficulty: 'easy',
    tags: ['Fractions to Percentages'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // ────────────────────────────────────────────────────────────
  // ACTIVITY 12: PARK PLANNER (Position & Transformation)
  // ────────────────────────────────────────────────────────────
  {
    id: 'park_bi_01',
    source: 'built-in',
    activityId: 'park-planner',
    activityName: 'Park Planner',
    question: 'In which quadrant of the coordinate grid is the park fountain located at point (-4, 6)?',
    options: ['Quadrant I', 'Quadrant II', 'Quadrant III', 'Quadrant IV'],
    correctAnswer: 'B',
    explanation: 'Points with negative x (-4) and positive y (+6) lie in Quadrant II.',
    difficulty: 'easy',
    tags: ['Coordinates', 'Quadrants', 'Park'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'park_bi_02',
    source: 'built-in',
    activityId: 'park-planner',
    activityName: 'Park Planner',
    question: 'If the park bench at (3, 2) is translated 4 units left and 5 units up, what are its new coordinates?',
    options: ['(7, 7)', '(-1, 7)', '(-1, -3)', '(7, -3)'],
    correctAnswer: 'B',
    explanation: 'x: 3 - 4 = -1. y: 2 + 5 = 7. New position = (-1, 7).',
    difficulty: 'medium',
    tags: ['Transformations', 'Translation'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'park_bi_03',
    source: 'built-in',
    activityId: 'park-planner',
    activityName: 'Park Planner',
    question: 'What are the coordinates of the origin on a Cartesian coordinate plane?',
    options: ['(1, 1)', '(0, 0)', '(-1, -1)', '(0, 1)'],
    correctAnswer: 'B',
    explanation: 'The origin where the x-axis and y-axis intersect is always (0, 0).',
    difficulty: 'easy',
    tags: ['Coordinates', 'Grid'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // ────────────────────────────────────────────────────────────
  // ACTIVITY 13: RATIO RUSH (Ratios, Rates & Proportions)
  // ────────────────────────────────────────────────────────────
  {
    id: 'ratio_bi_01',
    source: 'built-in',
    activityId: 'ratio-rush',
    activityName: 'Ratio Rush',
    question: 'For every 2 Close-up camera shots, the director shoots 3 Wide shots (Ratio 2 : 3). If they shoot 6 Close-up shots, how many Wide shots are needed?',
    options: ['6', '8', '9', '12'],
    correctAnswer: 'C',
    explanation: 'Scale factor = 6 ÷ 2 = 3. Multiply wide shots: 3 × 3 = 9.',
    difficulty: 'easy',
    tags: ['Ratio', 'Equivalent Ratio', 'Movie Studio'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'ratio_bi_02',
    source: 'built-in',
    activityId: 'ratio-rush',
    activityName: 'Ratio Rush',
    question: 'To mix green screen backdrop paint, the painter uses 1 cup of Blue dye for every 3 cups of Green paint (Ratio 1 : 3). If they use 12 cups of Green paint, how many cups of Blue dye are needed?',
    options: ['3', '4', '6', '9'],
    correctAnswer: 'B',
    explanation: 'Scale factor = 12 ÷ 3 = 4. Blue dye = 1 × 4 = 4 cups.',
    difficulty: 'easy',
    tags: ['Ratio', 'Scaling'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'ratio_bi_03',
    source: 'built-in',
    activityId: 'ratio-rush',
    activityName: 'Ratio Rush',
    question: 'A film crew feeds 4 actors with 8 snack boxes (Ratio 4 : 8). How many snack boxes are needed for 10 actors at the same unit rate?',
    options: ['16', '18', '20', '24'],
    correctAnswer: 'C',
    explanation: 'Unit rate = 8 ÷ 4 = 2 boxes per actor. For 10 actors: 10 × 2 = 20 boxes.',
    difficulty: 'medium',
    tags: ['Unit Rate', 'Word Problem'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'ratio_bi_04',
    source: 'built-in',
    activityId: 'ratio-rush',
    activityName: 'Ratio Rush',
    question: 'The film camera records 24 frames every 1 second. How many frames are recorded in 5 seconds?',
    options: ['100', '110', '120', '144'],
    correctAnswer: 'C',
    explanation: 'Rate = 24 frames/sec × 5 sec = 120 frames.',
    difficulty: 'easy',
    tags: ['Rates', 'Speed'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'ratio_bi_05',
    source: 'built-in',
    activityId: 'ratio-rush',
    activityName: 'Ratio Rush',
    question: 'In a cinema auditorium, the ratio of adults to children is 3 : 5. If there are 40 children, how many adults are in the cinema?',
    options: ['18', '24', '30', '32'],
    correctAnswer: 'B',
    explanation: 'Scale factor = 40 ÷ 5 = 8. Adults = 3 × 8 = 24.',
    difficulty: 'medium',
    tags: ['Proportion', 'Word Problem'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'ratio_bi_06',
    source: 'built-in',
    activityId: 'ratio-rush',
    activityName: 'Ratio Rush',
    question: 'Simplify the movie reel length ratio 18 : 24 to its simplest form.',
    options: ['2 : 3', '3 : 4', '4 : 5', '3 : 5'],
    correctAnswer: 'B',
    explanation: 'Divide both terms by the greatest common divisor 6: 18÷6 = 3, 24÷6 = 4. Ratio = 3 : 4.',
    difficulty: 'easy',
    tags: ['Simplifying Ratios', 'Fractions'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'ratio_bi_07',
    source: 'built-in',
    activityId: 'ratio-rush',
    activityName: 'Ratio Rush',
    question: 'A movie studio set model is built to scale 1 : 20. If the real studio door is 200 cm high, how tall is the model door?',
    options: ['10 cm', '15 cm', '20 cm', '25 cm'],
    correctAnswer: 'A',
    explanation: 'Model size = Real size ÷ 20 = 200 ÷ 20 = 10 cm.',
    difficulty: 'medium',
    tags: ['Scale Factor', 'Proportions'],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
];

export const BUILT_IN_QUESTIONS_SEED: UniversalQuestion[] = RAW_BUILT_IN_QUESTIONS.map((q) => {
  const act = ACTIVITIES_REGISTRY.find((a) => a.id === q.activityId);
  return {
    ...q,
    activityName: act ? act.name : q.activityName,
    topicId: act ? act.topicId : 'general',
    topicName: act ? act.topic : 'Mathematics',
  };
});

