// ============================================================
// THE GREAT CARNIVAL OF CHANCE — Probability Engine & Challenge Bank
// Grade 6 Bloom's Taxonomy Mapped Challenges with Mathematical Fractions
// ============================================================

import { ActivityId, AttractionMeta, ProbabilityChallenge } from '../types';

export const ATTRACTIONS_META: Record<ActivityId, AttractionMeta> = {
  hub: {
    id: 'hub',
    name: 'CARNIVAL ISLAND',
    subtitle: 'The Heart of the Festival',
    tagline: 'Explore • Predict • Discover',
    description: 'Explore the 3D carnival island and operate physical probability machines with your team.',
    accentColor: '#f59e0b',
    islandPosition: [0, 0, 0],
    completed: false,
    unlocked: true,
  },
  'mystery-bag': {
    id: 'mystery-bag',
    name: 'THE MYSTERY SACK',
    subtitle: 'Physical Bag Draw Chamber',
    tagline: 'Draw 3D Spheres from the Carnival Sack',
    description: 'A genuine 3D cloth sack holding real spheres. Predict the exact fraction, then pull the drawstring to reveal the drawn ball!',
    accentColor: '#b45309',
    islandPosition: [-6.5, 0, -5.5],
    islandScale: [1.2, 1.2, 1.2],
    completed: false,
    unlocked: true,
  },
  'odds-wheel': {
    id: 'odds-wheel',
    name: 'THE ODDS WHEEL',
    subtitle: 'Likelihood & Ratio Spinner',
    tagline: 'Spin the Mechanical Segmented Wheel',
    description: 'Spin the physical segmented wheel to explore certain, likely, unlikely, and impossible outcomes with tactile ratchet clicks.',
    accentColor: '#2563eb',
    islandPosition: [-8.5, 0, 1.5],
    islandScale: [1.1, 1.1, 1.1],
    completed: false,
    unlocked: true,
  },
  'ball-drop': {
    id: 'ball-drop',
    name: 'GIANT BALL DROP',
    subtitle: 'Pachinko Experimental Tower',
    tagline: 'Theoretical vs 10-Trial Experimental Runs',
    description: 'Drop physical balls down helical chutes and run 10-trial batches to analyze how experimental results compare to theoretical probability.',
    accentColor: '#10b981',
    islandPosition: [6.5, 0, -5.5],
    islandScale: [1.1, 1.1, 1.1],
    completed: false,
    unlocked: true,
  },
  'probability-lab': {
    id: 'probability-lab',
    name: 'THE PROBABILITY LAB',
    subtitle: 'Alchemical Science Machine',
    tagline: 'Configure Sample Spaces & Fluid Chambers',
    description: 'Tune machine outcomes, compute sample spaces, and alter probabilities to achieve target mathematical fractions.',
    accentColor: '#9333ea',
    islandPosition: [8.5, 0, 1.5],
    islandScale: [1.1, 1.1, 1.1],
    completed: false,
    unlocked: true,
  },
  'game-builder': {
    id: 'game-builder',
    name: 'BUILD A CARNIVAL GAME',
    subtitle: 'Crafting & Calibration Workshop',
    tagline: 'Construct a Game with Exact Odds',
    description: 'The creative challenge: Place winning and losing target slots into a real carnival pegboard to meet exact odds rules.',
    accentColor: '#ea580c',
    islandPosition: [-5.5, 0, 6.5],
    islandScale: [1.1, 1.1, 1.1],
    completed: false,
    unlocked: true,
  },
  'grand-carnival': {
    id: 'grand-carnival',
    name: 'GRAND CARNIVAL FINALE',
    subtitle: 'The Ultimate Probability Showdown',
    tagline: 'Claim the Grand Master Championship Trophy',
    description: 'Compare competing carnival machines, justify the highest winning probability, and claim the championship!',
    accentColor: '#dc2626',
    islandPosition: [0, 0, 8.5],
    islandScale: [1.2, 1.2, 1.2],
    completed: false,
    unlocked: false,
  },
};

export const CARNIVAL_CHALLENGES: Record<ActivityId, ProbabilityChallenge[]> = {
  hub: [],
  'mystery-bag': [
    {
      id: 'bag_01',
      activityId: 'mystery-bag',
      bloomLevel: 'apply',
      missionTitle: 'THE RED BALL MYSTERY',
      prompt: 'A carnival sack holds 5 RED balls and 4 BLUE balls (9 total). If you draw one ball at random, what is the probability of picking a RED ball?',
      helperNote: 'Probability = (Favorable Outcomes) ÷ (Total Possible Outcomes)',
      setup: {
        totalItems: 9,
        items: [
          { color: '#dc2626', colorName: 'Red', count: 5 },
          { color: '#2563eb', colorName: 'Blue', count: 4 },
        ],
        targetColor: '#dc2626',
        theoreticalFraction: { numerator: 5, denominator: 9, percentage: '55.6%', decimal: 0.556 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 5, denominator: 9, percentage: '55.6%' },
          label: '5 / 9 (55.6% chance of Red)',
          isCorrect: true,
          feedbackText: '5 Red balls out of 9 Total = 5/9 (55.6%).',
        },
        {
          id: 'b',
          fraction: { numerator: 4, denominator: 9, percentage: '44.4%' },
          label: '4 / 9 (44.4% chance of Blue)',
          isCorrect: false,
          feedbackText: '4/9 is the probability of drawing Blue, not Red.',
        },
        {
          id: 'c',
          fraction: { numerator: 5, denominator: 4, percentage: '125%' },
          label: '5 / 4 (Ratio of Red to Blue)',
          isCorrect: false,
          feedbackText: '5/4 is the ratio of Red to Blue, but probability must be divided by the Total (9).',
        },
        {
          id: 'd',
          fraction: { numerator: 1, denominator: 9, percentage: '11.1%' },
          label: '1 / 9 (Single Ball Chance)',
          isCorrect: false,
          feedbackText: '1/9 is the probability of 1 specific ball, but there are 5 Red balls.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'Since there are 5 Red balls out of a total of 9 balls, P(Red) = 5/9 ≈ 55.6%.',
      reflectionPrompt: 'Notice that Red is slightly more likely than Blue because 5 > 4.',
      points: 120,
      goldTickets: 1,
    },
    {
      id: 'bag_02',
      activityId: 'mystery-bag',
      bloomLevel: 'analyze',
      missionTitle: 'THE COMPLEMENT RULE',
      prompt: 'A carnival sack holds 3 YELLOW, 4 GREEN, and 5 PURPLE balls (12 total). What is the probability of drawing a ball that is NOT PURPLE?',
      helperNote: 'Complementary Events: P(Not Purple) = 1 - P(Purple)',
      setup: {
        totalItems: 12,
        items: [
          { color: '#eab308', colorName: 'Yellow', count: 3 },
          { color: '#16a34a', colorName: 'Green', count: 4 },
          { color: '#9333ea', colorName: 'Purple', count: 5 },
        ],
        targetColor: '#16a34a',
        theoreticalFraction: { numerator: 7, denominator: 12, percentage: '58.3%', decimal: 0.583 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 7, denominator: 12, percentage: '58.3%' },
          label: '7 / 12 (Yellow + Green = 7)',
          isCorrect: true,
          feedbackText: '3 Yellow + 4 Green = 7 non-purple balls out of 12 Total = 7/12.',
        },
        {
          id: 'b',
          fraction: { numerator: 5, denominator: 12, percentage: '41.7%' },
          label: '5 / 12 (Purple balls only)',
          isCorrect: false,
          feedbackText: '5/12 is the probability of drawing Purple.',
        },
        {
          id: 'c',
          fraction: { numerator: 3, denominator: 12, percentage: '25.0%' },
          label: '3 / 12 (Yellow balls only)',
          isCorrect: false,
          feedbackText: '3/12 only counts Yellow, but Green is also not purple.',
        },
        {
          id: 'd',
          fraction: { numerator: 4, denominator: 12, percentage: '33.3%' },
          label: '4 / 12 (Green balls only)',
          isCorrect: false,
          feedbackText: '4/12 only counts Green, but Yellow is also not purple.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'Non-purple balls = 3 Yellow + 4 Green = 7. Total = 12. P(Not Purple) = 7/12 ≈ 58.3%.',
      points: 150,
      goldTickets: 2,
    },
  ],
  'odds-wheel': [
    {
      id: 'wheel_01',
      activityId: 'odds-wheel',
      bloomLevel: 'understand',
      missionTitle: 'THE GOLDEN SECTOR',
      prompt: 'The Odds Wheel has 10 equal segments: 6 BLUE, 3 RED, and 1 GOLD. What is the probability that the spinning flapper stops on the GOLD sector?',
      helperNote: 'Each sector has equal width (1/10 of the circumference).',
      setup: {
        totalItems: 10,
        items: [
          { color: '#2563eb', colorName: 'Blue', count: 6 },
          { color: '#dc2626', colorName: 'Red', count: 3 },
          { color: '#f59e0b', colorName: 'Gold', count: 1 },
        ],
        targetColor: '#f59e0b',
        theoreticalFraction: { numerator: 1, denominator: 10, percentage: '10.0%', decimal: 0.1 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 1, denominator: 10, percentage: '10.0%' },
          label: '1 / 10 (1 Gold out of 10 sectors)',
          isCorrect: true,
          feedbackText: '1 sector out of 10 = 1/10 = 10%.',
        },
        {
          id: 'b',
          fraction: { numerator: 1, denominator: 3, percentage: '33.3%' },
          label: '1 / 3 (1 out of 3 colors)',
          isCorrect: false,
          feedbackText: 'Colors are not equally distributed on the wheel.',
        },
        {
          id: 'c',
          fraction: { numerator: 3, denominator: 10, percentage: '30.0%' },
          label: '3 / 10 (Red sector probability)',
          isCorrect: false,
          feedbackText: '3/10 is the probability of landing on Red.',
        },
        {
          id: 'd',
          fraction: { numerator: 1, denominator: 2, percentage: '50.0%' },
          label: '1 / 2 (Half chance)',
          isCorrect: false,
          feedbackText: '1/2 would require 5 gold sectors.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'There is 1 Gold sector out of 10 equal sectors, so P(Gold) = 1/10 = 10%.',
      points: 120,
      goldTickets: 1,
    },
  ],
  'ball-drop': [
    {
      id: 'drop_01',
      activityId: 'ball-drop',
      bloomLevel: 'evaluate',
      missionTitle: 'THEORETICAL VS EXPERIMENTAL DROP',
      prompt: 'The transparent tower is loaded with 8 GREEN balls and 2 YELLOW balls (10 total). What is the theoretical probability of a YELLOW ball dropping?',
      helperNote: 'After predicting, we will drop a ball, then run a batch of 10 trials!',
      setup: {
        totalItems: 10,
        items: [
          { color: '#16a34a', colorName: 'Green', count: 8 },
          { color: '#eab308', colorName: 'Yellow', count: 2 },
        ],
        targetColor: '#eab308',
        theoreticalFraction: { numerator: 2, denominator: 10, percentage: '20.0%', decimal: 0.2 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 2, denominator: 10, percentage: '20.0%' },
          label: '2 / 10 = 1 / 5 (20.0% chance of Yellow)',
          isCorrect: true,
          feedbackText: '2 Yellow balls out of 10 = 2/10 = 20%.',
        },
        {
          id: 'b',
          fraction: { numerator: 8, denominator: 10, percentage: '80.0%' },
          label: '8 / 10 = 4 / 5 (80.0% chance of Green)',
          isCorrect: false,
          feedbackText: '8/10 is the probability of Green.',
        },
        {
          id: 'c',
          fraction: { numerator: 2, denominator: 8, percentage: '25.0%' },
          label: '2 / 8 (Yellow compared to Green)',
          isCorrect: false,
          feedbackText: '2/8 is the ratio, but probability requires dividing by total (10).',
        },
        {
          id: 'd',
          fraction: { numerator: 1, denominator: 10, percentage: '10.0%' },
          label: '1 / 10 (Single ball probability)',
          isCorrect: false,
          feedbackText: 'There are 2 yellow balls, not 1.',
        },
      ],
      correctAnswerId: 'a',
      explanation: '2 Yellow out of 10 Total = 2/10 = 1/5 = 20%. In 10 trials, experimental results will cluster around 20%!',
      points: 150,
      goldTickets: 2,
    },
  ],
  'probability-lab': [
    {
      id: 'lab_01',
      activityId: 'probability-lab',
      bloomLevel: 'create',
      missionTitle: 'CHAMBER CALIBRATION: 3/5 PROBABILITY',
      prompt: 'The laboratory chamber needs exactly 5 balls loaded so that P(BLUE) = 3/5 (60%). Which combination of 3D balls satisfies this condition?',
      helperNote: 'Target: 3 Blue balls and 2 Red balls out of 5 total.',
      setup: {
        totalItems: 5,
        items: [
          { color: '#2563eb', colorName: 'Blue', count: 3 },
          { color: '#dc2626', colorName: 'Red', count: 2 },
        ],
        targetColor: '#2563eb',
        theoreticalFraction: { numerator: 3, denominator: 5, percentage: '60.0%', decimal: 0.6 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 3, denominator: 5, percentage: '60.0%' },
          label: '3 Blue Balls + 2 Red Balls (5 Total)',
          isCorrect: true,
          feedbackText: '3 Blue out of 5 Total gives P(Blue) = 3/5 = 60%.',
        },
        {
          id: 'b',
          fraction: { numerator: 2, denominator: 5, percentage: '40.0%' },
          label: '2 Blue Balls + 3 Red Balls (5 Total)',
          isCorrect: false,
          feedbackText: 'This would give P(Blue) = 2/5 = 40%.',
        },
        {
          id: 'c',
          fraction: { numerator: 3, denominator: 8, percentage: '37.5%' },
          label: '3 Blue Balls + 5 Red Balls (8 Total)',
          isCorrect: false,
          feedbackText: 'This gives 8 total balls, so P(Blue) = 3/8.',
        },
        {
          id: 'd',
          fraction: { numerator: 1, denominator: 5, percentage: '20.0%' },
          label: '1 Blue Ball + 4 Red Balls (5 Total)',
          isCorrect: false,
          feedbackText: 'This gives P(Blue) = 1/5 = 20%.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'To achieve P(Blue) = 3/5, 3 out of every 5 items in the chamber must be Blue.',
      points: 150,
      goldTickets: 2,
    },
  ],
  'game-builder': [
    {
      id: 'build_01',
      activityId: 'game-builder',
      bloomLevel: 'create',
      missionTitle: 'CONSTRUCT A WINNING GAME: 3/10',
      prompt: 'Construct a carnival pegboard game with 10 slots where the probability of a player winning a prize is exactly 3/10 (30%). How many WINNING slots must be placed?',
      helperNote: 'Total slots = 10. Winning slots = ?',
      setup: {
        totalItems: 10,
        items: [
          { color: '#16a34a', colorName: 'Win', count: 3 },
          { color: '#dc2626', colorName: 'Try Again', count: 7 },
        ],
        targetColor: '#16a34a',
        theoreticalFraction: { numerator: 3, denominator: 10, percentage: '30.0%', decimal: 0.3 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 3, denominator: 10, percentage: '30.0%' },
          label: '3 Winning Slots + 7 Losing Slots (10 Total)',
          isCorrect: true,
          feedbackText: '3 Winning slots out of 10 = 3/10 = 30%.',
        },
        {
          id: 'b',
          fraction: { numerator: 4, denominator: 10, percentage: '40.0%' },
          label: '4 Winning Slots + 6 Losing Slots (10 Total)',
          isCorrect: false,
          feedbackText: 'This gives P(Win) = 4/10 = 40%.',
        },
        {
          id: 'c',
          fraction: { numerator: 1, denominator: 3, percentage: '33.3%' },
          label: '1 Winning Slot + 2 Losing Slots (3 Total)',
          isCorrect: false,
          feedbackText: 'The board requires 10 slots in total.',
        },
        {
          id: 'd',
          fraction: { numerator: 7, denominator: 10, percentage: '70.0%' },
          label: '7 Winning Slots + 3 Losing Slots (10 Total)',
          isCorrect: false,
          feedbackText: 'This gives 70% win chance, which is too high.',
        },
      ],
      correctAnswerId: 'a',
      explanation: '3 winning slots out of 10 total slots satisfies P(Win) = 3/10 = 30%.',
      points: 150,
      goldTickets: 2,
    },
  ],
  'grand-carnival': [
    {
      id: 'grand_01',
      activityId: 'grand-carnival',
      bloomLevel: 'evaluate',
      missionTitle: 'THE GRAND CARNIVAL COMPARISON',
      prompt:
        'Compare three carnival prize games:\n• Game A: 4 wins out of 10 (4/10)\n• Game B: 1 win out of 3 (1/3)\n• Game C: 2 wins out of 5 (2/5)\nWhich game gives you the LOWEST probability of winning?',
      helperNote: 'Convert all fractions to percentages to compare accurately!',
      setup: {
        totalItems: 3,
        items: [
          { color: '#dc2626', colorName: 'Game B (1/3)', count: 1 },
          { color: '#2563eb', colorName: 'Game A (4/10)', count: 1 },
          { color: '#16a34a', colorName: 'Game C (2/5)', count: 1 },
        ],
        targetColor: '#dc2626',
        theoreticalFraction: { numerator: 1, denominator: 3, percentage: '33.3%', decimal: 0.333 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 1, denominator: 3, percentage: '33.3%' },
          label: 'Game B (1/3 ≈ 33.3% is lower than 40%)',
          isCorrect: true,
          feedbackText: 'Game A = 40%, Game C = 40%, but Game B = 33.3% (Lowest!).',
        },
        {
          id: 'b',
          fraction: { numerator: 4, denominator: 10, percentage: '40.0%' },
          label: 'Game A (4/10 = 40%)',
          isCorrect: false,
          feedbackText: '4/10 = 40%, which is higher than Game B (33.3%).',
        },
        {
          id: 'c',
          fraction: { numerator: 2, denominator: 5, percentage: '40.0%' },
          label: 'Game C (2/5 = 40%)',
          isCorrect: false,
          feedbackText: '2/5 = 40%, which is tied with Game A.',
        },
        {
          id: 'd',
          fraction: { numerator: 3, denominator: 3, percentage: '100%' },
          label: 'All games have equal winning chances',
          isCorrect: false,
          feedbackText: 'Game B is 33.3% while Games A & C are 40%.',
        },
      ],
      correctAnswerId: 'a',
      explanation: '4/10 = 40% and 2/5 = 40%. Game B is 1/3 ≈ 33.3%, which is the lowest probability of winning.',
      points: 200,
      goldTickets: 3,
    },
  ],
};
