// ============================================================
// THE GREAT CARNIVAL OF CHANCE — Probability Engine & Data
// Grade 6 Bloom's Taxonomy Mapped Challenges
// ============================================================

import { AttractionId, AttractionInfo, ProbabilityChallenge } from '../types';

export const ATTRACTIONS: AttractionInfo[] = [
  {
    id: 'central-plaza',
    name: 'CARNIVAL PLAZA & CLOCK',
    subtitle: 'The Heart of the Festival',
    description: 'Track your festival progress and master probability across all physical attractions.',
    position: [0, 0, 0],
    cameraPosition: [0, 14, 22],
    cameraTarget: [0, 1.5, 0],
    color: '#f59e0b',
    unlocked: true,
    completed: false,
    totalChallenges: 1,
    completedChallenges: 0,
  },
  {
    id: 'odds-wheel',
    name: 'THE ODDS WHEEL',
    subtitle: 'Likelihood & Ratio Spinner',
    description: 'Spin the physical segmented wheel to explore certain, likely, unlikely, and impossible outcomes.',
    position: [-7.5, 0, -4.5],
    cameraPosition: [-7.5, 5, 4.5],
    cameraTarget: [-7.5, 3.2, -4.5],
    color: '#3b82f6',
    unlocked: true,
    completed: false,
    totalChallenges: 3,
    completedChallenges: 0,
  },
  {
    id: 'mystery-chests',
    name: 'THE MYSTERY CHESTS',
    subtitle: 'Prize Ratio Market',
    description: 'Compare the contents of mysterious prize chests to find the greatest chance of discovering gold.',
    position: [7.5, 0, -4.5],
    cameraPosition: [7.5, 5, 4.5],
    cameraTarget: [7.5, 2.5, -4.5],
    color: '#e11d48',
    unlocked: true,
    completed: false,
    totalChallenges: 3,
    completedChallenges: 0,
  },
  {
    id: 'giant-ball-drop',
    name: 'GIANT BALL DROP',
    subtitle: 'Theoretical vs Experimental Lab',
    description: 'Drop physical spheres through tubes and run 10 to 50 trial batches to see probability in action.',
    position: [-7.5, 0, 6.5],
    cameraPosition: [-7.5, 6, 16],
    cameraTarget: [-7.5, 3.5, 6.5],
    color: '#10b981',
    unlocked: true,
    completed: false,
    totalChallenges: 3,
    completedChallenges: 0,
  },
  {
    id: 'chance-lab',
    name: 'THE PROBABILITY LAB',
    subtitle: 'Interactive Machine Configurator',
    description: 'Tune machine outcomes, compute sample spaces, and alter probabilities to exact target fractions.',
    position: [7.5, 0, 6.5],
    cameraPosition: [7.5, 6, 16],
    cameraTarget: [7.5, 3.5, 6.5],
    color: '#8b5cf6',
    unlocked: true,
    completed: false,
    totalChallenges: 3,
    completedChallenges: 0,
  },
  {
    id: 'carnival-workshop',
    name: 'CARNIVAL WORKSHOP',
    subtitle: 'Build a Carnival Game',
    description: 'The creative challenge: Build and calibrate a physical game that satisfies strict probability rules.',
    position: [0, 0, -9.5],
    cameraPosition: [0, 6.5, -0.5],
    cameraTarget: [0, 3, -9.5],
    color: '#06b6d4',
    unlocked: true,
    completed: false,
    totalChallenges: 2,
    completedChallenges: 0,
  },
  {
    id: 'grand-carnival',
    name: 'GRAND CARNIVAL FINALE',
    subtitle: 'The Ultimate Probability Showdown',
    description: 'Compare competing carnival machines and claim the Grand Master Trophy.',
    position: [0, 0, 11],
    cameraPosition: [0, 7.5, 20.5],
    cameraTarget: [0, 3.5, 11],
    color: '#eab308',
    unlocked: false,
    completed: false,
    totalChallenges: 2,
    completedChallenges: 0,
  },
];

export const CARNIVAL_CHALLENGES: Record<AttractionId, ProbabilityChallenge[]> = {
  'central-plaza': [
    {
      id: 'plaza_01',
      attractionId: 'central-plaza',
      bloomLevel: 'remember',
      difficulty: 'foundation',
      points: 100,
      missionTitle: 'CARNIVAL ORIENTATION',
      prompt: 'In mathematics, what does a probability of 0 (zero) mean for an event?',
      probabilityData: {
        totalOutcomes: 10,
        favorableOutcomes: 0,
        items: [{ label: 'Zero Event', color: '#94a3b8', count: 0 }],
        theoreticalProbabilityFraction: '0/10',
        theoreticalProbabilityDecimal: 0,
      },
      options: [
        { id: 'a', value: 'impossible', label: 'Impossible (It can never happen)' },
        { id: 'b', value: 'likely', label: 'Likely (It will probably happen)' },
        { id: 'c', value: 'certain', label: 'Certain (It is 100% guaranteed)' },
      ],
      correctAnswer: 'impossible',
      hints: [
        'Think of the probability scale from 0 to 1.',
        '0 means no chance at all; 1 means completely certain.',
      ],
      explanation: 'A probability of 0 means the event is impossible and will never occur.',
      reflectionQuestion: 'What number on the probability scale represents an event that is 100% certain?',
      machineAction: 'grand-spectacle',
    },
  ],

  'odds-wheel': [
    {
      id: 'wheel_01',
      attractionId: 'odds-wheel',
      bloomLevel: 'understand',
      difficulty: 'foundation',
      points: 100,
      missionTitle: 'LIKELIHOOD ANALYSIS',
      prompt: 'The physical Odds Wheel has 10 equal sections: 6 Blue, 3 Red, and 1 Gold. Which color is MOST LIKELY to be spun?',
      probabilityData: {
        totalOutcomes: 10,
        favorableOutcomes: 6,
        items: [
          { label: 'Blue', color: '#3b82f6', count: 6 },
          { label: 'Red', color: '#ef4444', count: 3 },
          { label: 'Gold', color: '#f59e0b', count: 1 },
        ],
        theoreticalProbabilityFraction: '6/10',
        theoreticalProbabilityDecimal: 0.6,
      },
      options: [
        { id: 'a', value: 'Blue', label: 'Blue (6 out of 10 sections)', fractionDisplay: '6/10' },
        { id: 'b', value: 'Red', label: 'Red (3 out of 10 sections)', fractionDisplay: '3/10' },
        { id: 'c', value: 'Gold', label: 'Gold (1 out of 10 sections)', fractionDisplay: '1/10' },
      ],
      correctAnswer: 'Blue',
      hints: [
        'Count the number of sections for each color.',
        'The color covering the largest portion of the wheel has the highest chance.',
      ],
      explanation: 'Blue covers 6 out of 10 sections (P = 6/10 = 3/5 = 60%), making it the most likely outcome.',
      reflectionQuestion: 'Does having the highest probability guarantee that Blue will land on every single spin?',
      machineAction: 'spin-wheel',
    },
    {
      id: 'wheel_02',
      attractionId: 'odds-wheel',
      bloomLevel: 'apply',
      difficulty: 'core',
      points: 120,
      missionTitle: 'GOLD TICKET PROBABILITY',
      prompt: 'On the same 10-section wheel (6 Blue, 3 Red, 1 Gold), what is the exact theoretical probability of landing on GOLD?',
      probabilityData: {
        totalOutcomes: 10,
        favorableOutcomes: 1,
        items: [
          { label: 'Blue', color: '#3b82f6', count: 6 },
          { label: 'Red', color: '#ef4444', count: 3 },
          { label: 'Gold', color: '#f59e0b', count: 1 },
        ],
        theoreticalProbabilityFraction: '1/10',
        theoreticalProbabilityDecimal: 0.1,
      },
      options: [
        { id: 'a', value: '1/10', label: '1/10 (10%)', fractionDisplay: '1/10', percentageDisplay: '10%' },
        { id: 'b', value: '1/3', label: '1/3 (33.3%)', fractionDisplay: '1/3', percentageDisplay: '33.3%' },
        { id: 'c', value: '1/2', label: '1/2 (50%)', fractionDisplay: '1/2', percentageDisplay: '50%' },
      ],
      correctAnswer: '1/10',
      hints: [
        'Probability = (Number of Favorable Outcomes) / (Total Number of Equal Outcomes)',
        'There is 1 Gold section out of 10 total sections.',
      ],
      explanation: 'Probability = Favorable / Total = 1 / 10 = 0.10 (or 10%).',
      machineAction: 'spin-wheel',
    },
    {
      id: 'wheel_03',
      attractionId: 'odds-wheel',
      bloomLevel: 'analyze',
      difficulty: 'challenge',
      points: 150,
      missionTitle: 'COMPLEMENTARY CHANCE',
      prompt: 'What is the probability of the wheel landing on a color that is NOT BLUE (landing on Red or Gold)?',
      probabilityData: {
        totalOutcomes: 10,
        favorableOutcomes: 4,
        items: [
          { label: 'Not Blue (Red+Gold)', color: '#ef4444', count: 4 },
          { label: 'Blue', color: '#3b82f6', count: 6 },
        ],
        theoreticalProbabilityFraction: '4/10',
        theoreticalProbabilityDecimal: 0.4,
      },
      options: [
        { id: 'a', value: '4/10', label: '4/10 (or 2/5)', fractionDisplay: '4/10' },
        { id: 'b', value: '3/10', label: '3/10', fractionDisplay: '3/10' },
        { id: 'c', value: '6/10', label: '6/10 (or 3/5)', fractionDisplay: '6/10' },
      ],
      correctAnswer: '4/10',
      hints: [
        'Combine the 3 Red sections and 1 Gold section: 3 + 1 = 4 sections.',
        'Alternatively: 1 - P(Blue) = 1 - 6/10 = 4/10.',
      ],
      explanation: '3 Red + 1 Gold = 4 non-blue sections out of 10. Thus P(Not Blue) = 4/10 = 2/5 = 40%.',
      machineAction: 'spin-wheel',
    },
  ],

  'mystery-chests': [
    {
      id: 'chest_01',
      attractionId: 'mystery-chests',
      bloomLevel: 'understand',
      difficulty: 'foundation',
      points: 100,
      missionTitle: 'CHEST COMPARISON',
      prompt: 'Three prize chests hold tokens:\n• Chest A: 8 Gold, 2 Silver (10 total)\n• Chest B: 5 Gold, 5 Silver (10 total)\n• Chest C: 2 Gold, 8 Silver (10 total)\nWhich chest gives you the GREATEST probability of drawing Gold?',
      probabilityData: {
        totalOutcomes: 10,
        favorableOutcomes: 8,
        items: [
          { label: 'Chest A Gold', color: '#eab308', count: 8 },
          { label: 'Chest A Silver', color: '#94a3b8', count: 2 },
        ],
        theoreticalProbabilityFraction: '8/10',
        theoreticalProbabilityDecimal: 0.8,
      },
      options: [
        { id: 'a', value: 'Chest A', label: 'Chest A (8/10 = 80% Gold)', fractionDisplay: '8/10' },
        { id: 'b', value: 'Chest B', label: 'Chest B (5/10 = 50% Gold)', fractionDisplay: '5/10' },
        { id: 'c', value: 'Chest C', label: 'Chest C (2/10 = 20% Gold)', fractionDisplay: '2/10' },
      ],
      correctAnswer: 'Chest A',
      hints: [
        'Compare the fraction of Gold in each chest: 8/10 vs 5/10 vs 2/10.',
        '8/10 is the largest fraction.',
      ],
      explanation: 'Chest A has 8 Gold out of 10 tokens (8/10 = 80%), which is the highest chance.',
      machineAction: 'open-chest',
    },
    {
      id: 'chest_02',
      attractionId: 'mystery-chests',
      bloomLevel: 'apply',
      difficulty: 'core',
      points: 120,
      missionTitle: 'EQUALLY LIKELY TEST',
      prompt: 'Which chest has Gold and Silver tokens that are EQUALLY LIKELY (50-50 chance) to be drawn?',
      probabilityData: {
        totalOutcomes: 10,
        favorableOutcomes: 5,
        items: [
          { label: 'Gold', color: '#eab308', count: 5 },
          { label: 'Silver', color: '#94a3b8', count: 5 },
        ],
        theoreticalProbabilityFraction: '5/10',
        theoreticalProbabilityDecimal: 0.5,
      },
      options: [
        { id: 'a', value: 'Chest B', label: 'Chest B (5 Gold & 5 Silver)', fractionDisplay: '5/10' },
        { id: 'b', value: 'Chest A', label: 'Chest A (8 Gold & 2 Silver)', fractionDisplay: '8/10' },
        { id: 'c', value: 'Chest C', label: 'Chest C (2 Gold & 8 Silver)', fractionDisplay: '2/10' },
      ],
      correctAnswer: 'Chest B',
      hints: [
        'Equally likely means both outcomes have the exact same count.',
        '5 out of 10 is equal to 1/2 (50%).',
      ],
      explanation: 'In Chest B, 5 Gold = 5 Silver. Both have P = 5/10 = 1/2, so they are equally likely.',
      machineAction: 'open-chest',
    },
    {
      id: 'chest_03',
      attractionId: 'mystery-chests',
      bloomLevel: 'analyze',
      difficulty: 'challenge',
      points: 150,
      missionTitle: 'PROPORTIONAL CHANCE',
      prompt: 'A Mystery Vault has 15 Ruby tokens and 5 Diamond tokens (20 total). A smaller Bag has 3 Ruby and 1 Diamond (4 total). How do the chances of drawing Diamond compare?',
      probabilityData: {
        totalOutcomes: 20,
        favorableOutcomes: 5,
        items: [
          { label: 'Ruby', color: '#ef4444', count: 15 },
          { label: 'Diamond', color: '#38bdf8', count: 5 },
        ],
        theoreticalProbabilityFraction: '5/20',
        theoreticalProbabilityDecimal: 0.25,
      },
      options: [
        { id: 'a', value: 'equal', label: 'Both have the EXACT SAME chance (1/4 = 25%)', fractionDisplay: '1/4' },
        { id: 'b', value: 'vault', label: 'The Vault has a higher chance because 5 > 1', fractionDisplay: '5/20' },
        { id: 'c', value: 'bag', label: 'The Bag has a higher chance because it has fewer tokens', fractionDisplay: '1/4' },
      ],
      correctAnswer: 'equal',
      hints: [
        'Simplify both fractions: 5/20 = 1/4 and 1/4 = 1/4.',
        'Probability depends on the ratio of favorable to total, not just the raw count.',
      ],
      explanation: '5/20 simplifies to 1/4 (25%). Both containers have the exact same probability of drawing Diamond.',
      machineAction: 'open-chest',
    },
  ],

  'giant-ball-drop': [
    {
      id: 'balldrop_01',
      attractionId: 'giant-ball-drop',
      bloomLevel: 'apply',
      difficulty: 'core',
      points: 120,
      missionTitle: 'THEORETICAL BALL CHANCE',
      prompt: 'The transparent ball dispenser mixes 4 Green balls and 6 Orange balls (10 balls total). What is the theoretical probability of dropping a GREEN ball?',
      probabilityData: {
        totalOutcomes: 10,
        favorableOutcomes: 4,
        items: [
          { label: 'Green', color: '#10b981', count: 4 },
          { label: 'Orange', color: '#f97316', count: 6 },
        ],
        theoreticalProbabilityFraction: '2/5',
        theoreticalProbabilityDecimal: 0.4,
      },
      options: [
        { id: 'a', value: '2/5', label: '2/5 (4 out of 10 = 40%)', fractionDisplay: '2/5', percentageDisplay: '40%' },
        { id: 'b', value: '1/2', label: '1/2 (50%)', fractionDisplay: '1/2', percentageDisplay: '50%' },
        { id: 'c', value: '4/5', label: '4/5 (80%)', fractionDisplay: '4/5', percentageDisplay: '80%' },
      ],
      correctAnswer: '2/5',
      hints: [
        'Fraction of Green = 4 / 10.',
        'Simplify 4/10 by dividing numerator and denominator by 2: 4÷2 / 10÷2 = 2/5.',
      ],
      explanation: 'P(Green) = 4/10, which simplifies to 2/5 (40%).',
      reflectionQuestion: 'If we drop 10 balls with replacement, will we ALWAYS get exactly 4 Green every single time?',
      machineAction: 'drop-ball',
    },
    {
      id: 'balldrop_02',
      attractionId: 'giant-ball-drop',
      bloomLevel: 'analyze',
      difficulty: 'challenge',
      points: 150,
      missionTitle: 'EXPERIMENTAL VARIATION',
      prompt: 'Suppose the machine runs 10 actual random trials and produces 3 Green and 7 Orange. Does this mean the theoretical probability was wrong?',
      probabilityData: {
        totalOutcomes: 10,
        favorableOutcomes: 4,
        items: [
          { label: 'Green', color: '#10b981', count: 4 },
          { label: 'Orange', color: '#f97316', count: 6 },
        ],
        theoreticalProbabilityFraction: '2/5',
        theoreticalProbabilityDecimal: 0.4,
      },
      options: [
        { id: 'a', value: 'no_variation', label: 'No: Short-term random experiments naturally vary around the theoretical probability.' },
        { id: 'b', value: 'yes_wrong', label: 'Yes: The theoretical probability must change to 3/10.' },
        { id: 'c', value: 'broken_machine', label: 'Yes: The machine must be physically biased.' },
      ],
      correctAnswer: 'no_variation',
      hints: [
        'Theoretical probability tells us what to expect over a very large number of trials.',
        'In just 10 trials, getting 3, 4, or 5 Green is common due to random variation.',
      ],
      explanation: 'Experimental results fluctuate in small sample sizes. As you run more trials (e.g. 50 or 100), experimental frequency gets closer to 40%.',
      machineAction: 'drop-ball',
    },
    {
      id: 'balldrop_03',
      attractionId: 'giant-ball-drop',
      bloomLevel: 'evaluate',
      difficulty: 'mastery',
      points: 160,
      missionTitle: 'LAW OF LARGE NUMBERS',
      prompt: 'If we increase the experiment from 10 trials to 500 trials, what will happen to the experimental percentage of Green balls?',
      probabilityData: {
        totalOutcomes: 10,
        favorableOutcomes: 4,
        items: [
          { label: 'Green', color: '#10b981', count: 4 },
          { label: 'Orange', color: '#f97316', count: 6 },
        ],
        theoreticalProbabilityFraction: '2/5',
        theoreticalProbabilityDecimal: 0.4,
      },
      options: [
        { id: 'a', value: 'closer', label: 'It will get CLOSER to the true theoretical 40% (2/5).' },
        { id: 'b', value: 'farther', label: 'It will drift completely away from 40%.' },
        { id: 'c', value: 'unpredictable', label: 'More trials make the outcome completely unpredictable.' },
      ],
      correctAnswer: 'closer',
      hints: [
        'This fundamental math principle is known as the Law of Large Numbers.',
        'More trials average out individual streaks and converge toward theoretical probability.',
      ],
      explanation: 'With larger samples (500 trials), experimental probability converges closely toward the theoretical 40%.',
      machineAction: 'drop-ball',
    },
  ],

  'chance-lab': [
    {
      id: 'lab_01',
      attractionId: 'chance-lab',
      bloomLevel: 'apply',
      difficulty: 'core',
      points: 120,
      missionTitle: 'CALCULATING PROBABILITY',
      prompt: 'In the Lab Dispenser, there are 2 Red, 6 Blue, and 2 Green marbles (10 total). What is the probability of drawing RED?',
      probabilityData: {
        totalOutcomes: 10,
        favorableOutcomes: 2,
        items: [
          { label: 'Red', color: '#ef4444', count: 2 },
          { label: 'Blue', color: '#3b82f6', count: 6 },
          { label: 'Green', color: '#10b981', count: 2 },
        ],
        theoreticalProbabilityFraction: '1/5',
        theoreticalProbabilityDecimal: 0.2,
      },
      options: [
        { id: 'a', value: '1/5', label: '1/5 (2/10 = 20%)', fractionDisplay: '1/5' },
        { id: 'b', value: '1/3', label: '1/3 (33%)', fractionDisplay: '1/3' },
        { id: 'c', value: '2/5', label: '2/5 (40%)', fractionDisplay: '2/5' },
      ],
      correctAnswer: '1/5',
      hints: [
        'Favorable (Red) = 2. Total = 2 + 6 + 2 = 10.',
        '2/10 = 1/5 = 20%.',
      ],
      explanation: 'P(Red) = 2/10 = 1/5 = 20%.',
      machineAction: 'run-lab',
    },
    {
      id: 'lab_02',
      attractionId: 'chance-lab',
      bloomLevel: 'analyze',
      difficulty: 'challenge',
      points: 150,
      missionTitle: 'TARGET CONFIGURATION',
      prompt: 'How many RED balls must be inside a 10-ball dispenser so that the probability of drawing Red is EXACTLY 1/2 (50%)?',
      probabilityData: {
        totalOutcomes: 10,
        favorableOutcomes: 5,
        items: [
          { label: 'Red', color: '#ef4444', count: 5 },
          { label: 'Other', color: '#94a3b8', count: 5 },
        ],
        theoreticalProbabilityFraction: '1/2',
        theoreticalProbabilityDecimal: 0.5,
      },
      options: [
        { id: 'a', value: 5, label: '5 Red Balls (5 out of 10 = 1/2)', fractionDisplay: '5/10' },
        { id: 'b', value: 4, label: '4 Red Balls (4 out of 10)', fractionDisplay: '4/10' },
        { id: 'c', value: 6, label: '6 Red Balls (6 out of 10)', fractionDisplay: '6/10' },
      ],
      correctAnswer: 5,
      hints: [
        '1/2 of 10 = 5 balls.',
        '5 / 10 = 1/2 = 50%.',
      ],
      explanation: 'To have P(Red) = 1/2 in a 10-ball machine, exactly 5 balls must be Red.',
      machineAction: 'run-lab',
    },
    {
      id: 'lab_03',
      attractionId: 'chance-lab',
      bloomLevel: 'evaluate',
      difficulty: 'mastery',
      points: 160,
      missionTitle: 'SUM OF ALL PROBABILITIES',
      prompt: 'In any complete probability experiment with all possible outcomes (e.g., Red, Blue, Green), what must the sum of all probabilities always equal?',
      probabilityData: {
        totalOutcomes: 1,
        favorableOutcomes: 1,
        items: [{ label: 'Complete Sample Space', color: '#8b5cf6', count: 1 }],
        theoreticalProbabilityFraction: '1/1',
        theoreticalProbabilityDecimal: 1.0,
      },
      options: [
        { id: 'a', value: '1', label: 'Exactly 1 (or 100%)' },
        { id: 'b', value: '10', label: '10 (or 1000%)' },
        { id: 'c', value: '0.5', label: '0.5 (or 50%)' },
      ],
      correctAnswer: '1',
      hints: [
        'All possible outcomes combined account for every possible scenario.',
        '100% of all events equals 1 in fractional/decimal probability.',
      ],
      explanation: 'The sum of probabilities for all mutually exclusive and exhaustive outcomes is always 1 (100%).',
      machineAction: 'run-lab',
    },
  ],

  'carnival-workshop': [
    {
      id: 'workshop_01',
      attractionId: 'carnival-workshop',
      bloomLevel: 'create',
      difficulty: 'challenge',
      points: 180,
      missionTitle: 'DESIGN A FAIR GAME',
      prompt: 'You have a 10-slot carnival prize track. To create a game where the probability of winning is EXACTLY 3/10 (30%), how should you configure the slots?',
      probabilityData: {
        totalOutcomes: 10,
        favorableOutcomes: 3,
        items: [
          { label: 'WIN', color: '#10b981', count: 3 },
          { label: 'TRY AGAIN', color: '#ef4444', count: 7 },
        ],
        theoreticalProbabilityFraction: '3/10',
        theoreticalProbabilityDecimal: 0.3,
      },
      options: [
        { id: 'a', value: '3win_7lose', label: '3 WIN slots and 7 TRY AGAIN slots', fractionDisplay: '3/10' },
        { id: 'b', value: '5win_5lose', label: '5 WIN slots and 5 TRY AGAIN slots', fractionDisplay: '5/10' },
        { id: 'c', value: '3win_10lose', label: '3 WIN slots and 10 TRY AGAIN slots', fractionDisplay: '3/13' },
      ],
      correctAnswer: '3win_7lose',
      hints: [
        'The total number of slots must equal 10.',
        '3 WIN slots + 7 TRY AGAIN slots = 10 total slots with 3/10 winning probability.',
      ],
      explanation: '3 WIN slots out of 10 total slots yields P(Win) = 3/10 (30%).',
      machineAction: 'test-slots',
    },
    {
      id: 'workshop_02',
      attractionId: 'carnival-workshop',
      bloomLevel: 'create',
      difficulty: 'mastery',
      points: 200,
      missionTitle: '20-SLOT CARNIVAL RE-DESIGN',
      prompt: 'A carnival manager asks you to build a 20-slot spinner with a 1/4 (25%) chance of hitting the Grand Prize. How many Grand Prize slots must you place?',
      probabilityData: {
        totalOutcomes: 20,
        favorableOutcomes: 5,
        items: [
          { label: 'Grand Prize', color: '#f59e0b', count: 5 },
          { label: 'Regular', color: '#64748b', count: 15 },
        ],
        theoreticalProbabilityFraction: '1/4',
        theoreticalProbabilityDecimal: 0.25,
      },
      options: [
        { id: 'a', value: 5, label: '5 Grand Prize slots (5/20 = 1/4 = 25%)', fractionDisplay: '5/20' },
        { id: 'b', value: 4, label: '4 Grand Prize slots (4/20 = 1/5 = 20%)', fractionDisplay: '4/20' },
        { id: 'c', value: 10, label: '10 Grand Prize slots (10/20 = 1/2 = 50%)', fractionDisplay: '10/20' },
      ],
      correctAnswer: 5,
      hints: [
        '1/4 of 20 = 20 ÷ 4 = 5 slots.',
        '5 / 20 = 1/4 = 25%.',
      ],
      explanation: '5 Grand Prize slots out of 20 total slots gives P(Grand Prize) = 5/20 = 1/4 (25%).',
      machineAction: 'test-slots',
    },
  ],

  'grand-carnival': [
    {
      id: 'grand_01',
      attractionId: 'grand-carnival',
      bloomLevel: 'evaluate',
      difficulty: 'mastery',
      points: 200,
      missionTitle: 'CARNIVAL GAME COMPARISON',
      prompt: 'Compare three Grand Carnival prize games:\n• Game A: 4 winning tickets out of 10 (4/10)\n• Game B: 1 winning ticket out of 3 (1/3)\n• Game C: 2 winning tickets out of 5 (2/5)\nWhich game gives you the LOWEST probability of winning?',
      probabilityData: {
        totalOutcomes: 30,
        favorableOutcomes: 10,
        items: [
          { label: 'Game A (40%)', color: '#3b82f6', count: 12 },
          { label: 'Game B (33.3%)', color: '#ef4444', count: 10 },
          { label: 'Game C (40%)', color: '#10b981', count: 12 },
        ],
        theoreticalProbabilityFraction: '1/3',
        theoreticalProbabilityDecimal: 0.333,
      },
      options: [
        { id: 'a', value: 'Game B', label: 'Game B (1/3 ≈ 33.3% is lower than 40%)', percentageDisplay: '33.3%' },
        { id: 'b', value: 'Game A', label: 'Game A (4/10 = 40%)', percentageDisplay: '40%' },
        { id: 'c', value: 'Game C', label: 'Game C (2/5 = 40%)', percentageDisplay: '40%' },
      ],
      correctAnswer: 'Game B',
      hints: [
        'Convert to percentages: Game A = 40%, Game C = 40%, Game B = 33.33%.',
        '33.3% is less than 40%.',
      ],
      explanation: 'Game A is 4/10 = 40% and Game C is 2/5 = 40%. Game B is 1/3 ≈ 33.3%, which is the lowest probability.',
      machineAction: 'grand-spectacle',
    },
    {
      id: 'grand_02',
      attractionId: 'grand-carnival',
      bloomLevel: 'evaluate',
      difficulty: 'mastery',
      points: 250,
      missionTitle: 'THE GRAND TROPHY DRAW',
      prompt: 'The Grand Carnival Master Chest has 1 Golden Ticket among 20 total tickets. What is the probability of picking the Golden Ticket in a single draw?',
      probabilityData: {
        totalOutcomes: 20,
        favorableOutcomes: 1,
        items: [
          { label: 'Golden Ticket', color: '#f59e0b', count: 1 },
          { label: 'Standard Ticket', color: '#94a3b8', count: 19 },
        ],
        theoreticalProbabilityFraction: '1/20',
        theoreticalProbabilityDecimal: 0.05,
      },
      options: [
        { id: 'a', value: '1/20', label: '1/20 (5%)', fractionDisplay: '1/20', percentageDisplay: '5%' },
        { id: 'b', value: '1/10', label: '1/10 (10%)', fractionDisplay: '1/10', percentageDisplay: '10%' },
        { id: 'c', value: '1/2', label: '1/2 (50%)', fractionDisplay: '1/2', percentageDisplay: '50%' },
      ],
      correctAnswer: '1/20',
      hints: [
        '1 favorable ticket out of 20 total tickets.',
        '1 ÷ 20 = 0.05 = 5%.',
      ],
      explanation: 'P(Gold) = 1/20 = 0.05 = 5%. A rare, thrilling carnival jackpot!',
      machineAction: 'grand-spectacle',
    },
  ],
};
