// ============================================================
// THE GREAT CARNIVAL OF CHANCE — Probability Engine & Challenge Bank
// 5 Grade 6 Bloom's Taxonomy Mapped Challenges Per Attraction (30 Total)
// With Mathematical Fractions, Decimals, Percentages & Explanations
// ============================================================

import { ActivityId, AttractionMeta, ProbabilityChallenge } from '../types';

export const ATTRACTIONS_META: Record<ActivityId, AttractionMeta> = {
  hub: {
    id: 'hub',
    name: 'CARNIVAL ISLAND',
    subtitle: 'The Heart of the Festival',
    tagline: 'Explore • Predict • Discover',
    description: 'Explore the 3D carnival island and operate physical probability machines with your team.',
    accentColor: '#f59e0b',
    islandPosition: [0, 0, 0],
    completed: false,
    unlocked: true,
  },
  'mystery-bag': {
    id: 'mystery-bag',
    name: 'THE MYSTERY SACK',
    subtitle: 'Physical Bag Draw Chamber',
    tagline: 'Draw 3D Spheres from the Carnival Sack',
    description: 'A genuine 3D cloth sack holding real spheres. Predict the exact fraction, then pull the drawstring to reveal the drawn ball!',
    accentColor: '#b45309',
    islandPosition: [-6.5, 0, -5.5],
    islandScale: [1.2, 1.2, 1.2],
    completed: false,
    unlocked: true,
  },
  'odds-wheel': {
    id: 'odds-wheel',
    name: 'THE ODDS WHEEL',
    subtitle: 'Likelihood & Ratio Spinner',
    tagline: 'Spin the Mechanical Segmented Wheel',
    description: 'Spin the physical segmented wheel to explore certain, likely, unlikely, and impossible outcomes with tactile ratchet clicks.',
    accentColor: '#2563eb',
    islandPosition: [-8.5, 0, 1.5],
    islandScale: [1.1, 1.1, 1.1],
    completed: false,
    unlocked: true,
  },
  'ball-drop': {
    id: 'ball-drop',
    name: 'GIANT BALL DROP',
    subtitle: 'Pachinko Experimental Tower',
    tagline: 'Theoretical vs 10-Trial Experimental Runs',
    description: 'Drop physical balls down helical chutes and run 10-trial batches to analyze how experimental results compare to theoretical probability.',
    accentColor: '#10b981',
    islandPosition: [6.5, 0, -5.5],
    islandScale: [1.1, 1.1, 1.1],
    completed: false,
    unlocked: true,
  },
  'probability-lab': {
    id: 'probability-lab',
    name: 'THE PROBABILITY LAB',
    subtitle: 'Alchemical Science Machine',
    tagline: 'Configure Sample Spaces & Fluid Chambers',
    description: 'Tune machine outcomes, compute sample spaces, and alter probabilities to achieve target mathematical fractions.',
    accentColor: '#9333ea',
    islandPosition: [8.5, 0, 1.5],
    islandScale: [1.1, 1.1, 1.1],
    completed: false,
    unlocked: true,
  },
  'game-builder': {
    id: 'game-builder',
    name: 'BUILD A CARNIVAL GAME',
    subtitle: 'Crafting & Calibration Workshop',
    tagline: 'Construct a Game with Exact Odds',
    description: 'The creative challenge: Place winning and losing target slots into a real carnival pegboard to meet exact odds rules.',
    accentColor: '#ea580c',
    islandPosition: [-5.5, 0, 6.5],
    islandScale: [1.1, 1.1, 1.1],
    completed: false,
    unlocked: true,
  },
  'grand-carnival': {
    id: 'grand-carnival',
    name: 'GRAND CARNIVAL FINALE',
    subtitle: 'The Ultimate Probability Showdown',
    tagline: 'Claim the Grand Master Championship Trophy',
    description: 'Compare competing carnival machines, justify the highest winning probability, and claim the championship!',
    accentColor: '#dc2626',
    islandPosition: [0, 0, 8.5],
    islandScale: [1.2, 1.2, 1.2],
    completed: false,
    unlocked: false,
  },
};

export const CARNIVAL_CHALLENGES: Record<ActivityId, ProbabilityChallenge[]> = {
  hub: [],

  // ═══════════════════════════════════════════════════════════════════
  // 1. THE ODDS WHEEL (5 Challenges)
  // ═══════════════════════════════════════════════════════════════════
  'odds-wheel': [
    {
      id: 'wheel_01',
      activityId: 'odds-wheel',
      bloomLevel: 'understand',
      missionTitle: 'THE GOLDEN SECTOR',
      prompt: 'The Odds Wheel has 10 equal sectors: 6 BLUE, 3 RED, and 1 GOLD. What is the probability that the spinning flapper stops on the GOLD sector?',
      helperNote: 'Each sector has equal width (1/10 of the circumference).',
      setup: {
        totalItems: 10,
        items: [
          { color: '#2563eb', colorName: 'Blue', count: 6 },
          { color: '#dc2626', colorName: 'Red', count: 3 },
          { color: '#f59e0b', colorName: 'Gold', count: 1 },
        ],
        targetColor: '#f59e0b',
        theoreticalFraction: { numerator: 1, denominator: 10, percentage: '10.0%', decimal: 0.1 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 1, denominator: 10, percentage: '10.0%' },
          label: '1 / 10 (10% Chance)',
          isCorrect: true,
          feedbackText: '1 Gold sector out of 10 equal sectors = 1/10 = 10%.',
        },
        {
          id: 'b',
          fraction: { numerator: 1, denominator: 3, percentage: '33.3%' },
          label: '1 / 3 (33.3% Chance)',
          isCorrect: false,
          feedbackText: 'Colors are not distributed equally; there are 10 sectors, not 3.',
        },
        {
          id: 'c',
          fraction: { numerator: 3, denominator: 10, percentage: '30.0%' },
          label: '3 / 10 (30% Chance)',
          isCorrect: false,
          feedbackText: '3/10 is the probability of landing on Red.',
        },
        {
          id: 'd',
          fraction: { numerator: 6, denominator: 10, percentage: '60.0%' },
          label: '6 / 10 (60% Chance)',
          isCorrect: false,
          feedbackText: '6/10 is the probability of landing on Blue.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'There is 1 Gold sector out of 10 equal sectors. P(Gold) = 1/10 = 10%.',
      points: 100,
      goldTickets: 1,
    },
    {
      id: 'wheel_02',
      activityId: 'odds-wheel',
      bloomLevel: 'apply',
      missionTitle: 'MAJORITY SPIN ODDS',
      prompt: 'A carnival spinner is divided into 8 equal parts: 5 RED and 3 BLUE. What is the probability of spinning a RED sector?',
      helperNote: 'Red occupies 5 out of the 8 total sections.',
      setup: {
        totalItems: 8,
        items: [
          { color: '#dc2626', colorName: 'Red', count: 5 },
          { color: '#2563eb', colorName: 'Blue', count: 3 },
        ],
        targetColor: '#dc2626',
        theoreticalFraction: { numerator: 5, denominator: 8, percentage: '62.5%', decimal: 0.625 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 5, denominator: 8, percentage: '62.5%' },
          label: '5 / 8 (62.5% Majority Chance)',
          isCorrect: true,
          feedbackText: '5 Red sectors out of 8 = 5/8 = 62.5%.',
        },
        {
          id: 'b',
          fraction: { numerator: 3, denominator: 8, percentage: '37.5%' },
          label: '3 / 8 (37.5% Chance)',
          isCorrect: false,
          feedbackText: '3/8 is the probability of Blue, not Red.',
        },
        {
          id: 'c',
          fraction: { numerator: 5, denominator: 3, percentage: '166%' },
          label: '5 / 3 (Odds Ratio)',
          isCorrect: false,
          feedbackText: '5/3 is the ratio of Red to Blue, not the probability.',
        },
        {
          id: 'd',
          fraction: { numerator: 1, denominator: 2, percentage: '50.0%' },
          label: '1 / 2 (50% Chance)',
          isCorrect: false,
          feedbackText: 'Red occupies more than half of the wheel.',
        },
      ],
      correctAnswerId: 'a',
      explanation: '5 favorable sectors out of 8 total sectors gives P(Red) = 5/8 = 62.5%.',
      points: 100,
      goldTickets: 1,
    },
    {
      id: 'wheel_03',
      activityId: 'odds-wheel',
      bloomLevel: 'analyze',
      missionTitle: 'PRIME NUMBER SECTORS',
      prompt: 'A 12-sector wheel is numbered 1 through 12. What is the probability that the pointer lands on a PRIME number? (Primes: 2, 3, 5, 7, 11)',
      helperNote: 'Count the prime numbers between 1 and 12 (Note: 1 is neither prime nor composite).',
      setup: {
        totalItems: 12,
        items: [
          { color: '#f59e0b', colorName: 'Prime (2,3,5,7,11)', count: 5 },
          { color: '#64748b', colorName: 'Composite / One', count: 7 },
        ],
        targetColor: '#f59e0b',
        theoreticalFraction: { numerator: 5, denominator: 12, percentage: '41.7%', decimal: 0.417 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 5, denominator: 12, percentage: '41.7%' },
          label: '5 / 12 (5 Primes: 2, 3, 5, 7, 11)',
          isCorrect: true,
          feedbackText: '5 prime numbers out of 12 numbers = 5/12 ≈ 41.7%.',
        },
        {
          id: 'b',
          fraction: { numerator: 6, denominator: 12, percentage: '50.0%' },
          label: '6 / 12 = 1 / 2 (Half)',
          isCorrect: false,
          feedbackText: '1 is not a prime number.',
        },
        {
          id: 'c',
          fraction: { numerator: 4, denominator: 12, percentage: '33.3%' },
          label: '4 / 12 = 1 / 3',
          isCorrect: false,
          feedbackText: 'There are 5 prime numbers: 2, 3, 5, 7, and 11.',
        },
        {
          id: 'd',
          fraction: { numerator: 7, denominator: 12, percentage: '58.3%' },
          label: '7 / 12 (Non-Primes)',
          isCorrect: false,
          feedbackText: '7/12 is the probability of non-prime sectors.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'The prime numbers are 2, 3, 5, 7, 11 (5 primes). P(Prime) = 5/12 ≈ 41.7%.',
      points: 120,
      goldTickets: 1,
    },
    {
      id: 'wheel_04',
      activityId: 'odds-wheel',
      bloomLevel: 'apply',
      missionTitle: 'THE COMPLEMENT SPIN',
      prompt: 'A wheel has 10 sectors: 2 BLACK, 4 YELLOW, and 4 GREEN. What is the probability of NOT landing on a BLACK sector?',
      helperNote: 'P(Not Black) = 1 - P(Black) = (Total - Black) ÷ Total',
      setup: {
        totalItems: 10,
        items: [
          { color: '#eab308', colorName: 'Yellow', count: 4 },
          { color: '#16a34a', colorName: 'Green', count: 4 },
          { color: '#1e293b', colorName: 'Black', count: 2 },
        ],
        targetColor: '#eab308',
        theoreticalFraction: { numerator: 8, denominator: 10, percentage: '80.0%', decimal: 0.8 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 8, denominator: 10, percentage: '80.0%' },
          label: '8 / 10 = 4 / 5 (80% Not Black)',
          isCorrect: true,
          feedbackText: '4 Yellow + 4 Green = 8 non-black sectors out of 10 = 8/10 = 80%.',
        },
        {
          id: 'b',
          fraction: { numerator: 2, denominator: 10, percentage: '20.0%' },
          label: '2 / 10 = 1 / 5 (20% Black)',
          isCorrect: false,
          feedbackText: '2/10 is the probability of landing on Black.',
        },
        {
          id: 'c',
          fraction: { numerator: 4, denominator: 10, percentage: '40.0%' },
          label: '4 / 10 = 2 / 5 (Yellow only)',
          isCorrect: false,
          feedbackText: 'Green sectors are also not black.',
        },
        {
          id: 'd',
          fraction: { numerator: 6, denominator: 10, percentage: '60.0%' },
          label: '6 / 10 (60% Chance)',
          isCorrect: false,
          feedbackText: 'There are 8 non-black sectors, not 6.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'Non-black sectors = 4 Yellow + 4 Green = 8 sectors. P(Not Black) = 8/10 = 4/5 = 80%.',
      points: 120,
      goldTickets: 1,
    },
    {
      id: 'wheel_05',
      activityId: 'odds-wheel',
      bloomLevel: 'evaluate',
      missionTitle: 'CERTAIN VS IMPOSSIBLE',
      prompt: 'A carnival spinner has 6 sectors: 3 RED and 3 BLUE. What is the probability of landing on a PURPLE sector?',
      helperNote: 'An event that has 0 favorable outcomes in the sample space is Impossible.',
      setup: {
        totalItems: 6,
        items: [
          { color: '#dc2626', colorName: 'Red', count: 3 },
          { color: '#2563eb', colorName: 'Blue', count: 3 },
        ],
        targetColor: '#a855f7',
        theoreticalFraction: { numerator: 0, denominator: 6, percentage: '0.0%', decimal: 0.0 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 0, denominator: 6, percentage: '0.0%' },
          label: '0 / 6 = 0 (Impossible Event)',
          isCorrect: true,
          feedbackText: 'There are 0 purple sectors on the wheel, so P(Purple) = 0 (0%).',
        },
        {
          id: 'b',
          fraction: { numerator: 3, denominator: 6, percentage: '50.0%' },
          label: '3 / 6 = 1 / 2 (50% Chance)',
          isCorrect: false,
          feedbackText: '3/6 is the probability of Red or Blue, but not Purple.',
        },
        {
          id: 'c',
          fraction: { numerator: 1, denominator: 6, percentage: '16.7%' },
          label: '1 / 6 (16.7% Chance)',
          isCorrect: false,
          feedbackText: 'There is no purple sector on this wheel.',
        },
        {
          id: 'd',
          fraction: { numerator: 6, denominator: 6, percentage: '100%' },
          label: '6 / 6 = 1 (Certain Event)',
          isCorrect: false,
          feedbackText: 'Landing on Purple is impossible, not certain.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'Because purple is not in the sample space, P(Purple) = 0/6 = 0% (Impossible event).',
      points: 150,
      goldTickets: 2,
    },
  ],

  // ═══════════════════════════════════════════════════════════════════
  // 2. THE MYSTERY SACK (5 Challenges)
  // ═══════════════════════════════════════════════════════════════════
  'mystery-bag': [
    {
      id: 'bag_01',
      activityId: 'mystery-bag',
      bloomLevel: 'apply',
      missionTitle: 'THE RED BALL MYSTERY',
      prompt: 'A carnival sack holds 5 RED balls and 4 BLUE balls (9 total). If you draw one ball at random, what is the probability of picking a RED ball?',
      helperNote: 'Probability = (Favorable Outcomes) ÷ (Total Possible Outcomes)',
      setup: {
        totalItems: 9,
        items: [
          { color: '#dc2626', colorName: 'Red', count: 5 },
          { color: '#2563eb', colorName: 'Blue', count: 4 },
        ],
        targetColor: '#dc2626',
        theoreticalFraction: { numerator: 5, denominator: 9, percentage: '55.6%', decimal: 0.556 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 5, denominator: 9, percentage: '55.6%' },
          label: '5 / 9 (55.6% Chance of Red)',
          isCorrect: true,
          feedbackText: '5 Red balls out of 9 Total = 5/9 ≈ 55.6%.',
        },
        {
          id: 'b',
          fraction: { numerator: 4, denominator: 9, percentage: '44.4%' },
          label: '4 / 9 (44.4% Chance of Blue)',
          isCorrect: false,
          feedbackText: '4/9 is the probability of drawing Blue, not Red.',
        },
        {
          id: 'c',
          fraction: { numerator: 5, denominator: 4, percentage: '125%' },
          label: '5 / 4 (Ratio of Red to Blue)',
          isCorrect: false,
          feedbackText: '5/4 is the ratio, but probability requires dividing by Total (9).',
        },
        {
          id: 'd',
          fraction: { numerator: 1, denominator: 9, percentage: '11.1%' },
          label: '1 / 9 (Single Ball Chance)',
          isCorrect: false,
          feedbackText: '1/9 is the probability of 1 specific ball.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'Since there are 5 Red balls out of 9 total, P(Red) = 5/9 ≈ 55.6%.',
      points: 100,
      goldTickets: 1,
    },
    {
      id: 'bag_02',
      activityId: 'mystery-bag',
      bloomLevel: 'analyze',
      missionTitle: 'THE COMPLEMENT RULE',
      prompt: 'A carnival sack holds 3 YELLOW, 4 GREEN, and 5 PURPLE balls (12 total). What is the probability of drawing a ball that is NOT PURPLE?',
      helperNote: 'Complementary Events: P(Not Purple) = 1 - P(Purple)',
      setup: {
        totalItems: 12,
        items: [
          { color: '#eab308', colorName: 'Yellow', count: 3 },
          { color: '#16a34a', colorName: 'Green', count: 4 },
          { color: '#9333ea', colorName: 'Purple', count: 5 },
        ],
        targetColor: '#16a34a',
        theoreticalFraction: { numerator: 7, denominator: 12, percentage: '58.3%', decimal: 0.583 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 7, denominator: 12, percentage: '58.3%' },
          label: '7 / 12 (Yellow + Green = 7)',
          isCorrect: true,
          feedbackText: '3 Yellow + 4 Green = 7 non-purple balls out of 12 = 7/12 ≈ 58.3%.',
        },
        {
          id: 'b',
          fraction: { numerator: 5, denominator: 12, percentage: '41.7%' },
          label: '5 / 12 (Purple balls only)',
          isCorrect: false,
          feedbackText: '5/12 is the probability of drawing Purple.',
        },
        {
          id: 'c',
          fraction: { numerator: 3, denominator: 12, percentage: '25.0%' },
          label: '3 / 12 (Yellow balls only)',
          isCorrect: false,
          feedbackText: '3/12 only counts Yellow, but Green is also not purple.',
        },
        {
          id: 'd',
          fraction: { numerator: 4, denominator: 12, percentage: '33.3%' },
          label: '4 / 12 (Green balls only)',
          isCorrect: false,
          feedbackText: '4/12 only counts Green, but Yellow is also not purple.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'Non-purple balls = 3 Yellow + 4 Green = 7. Total = 12. P(Not Purple) = 7/12 ≈ 58.3%.',
      points: 100,
      goldTickets: 1,
    },
    {
      id: 'bag_03',
      activityId: 'mystery-bag',
      bloomLevel: 'apply',
      missionTitle: 'SIMPLIFYING PROBABILITY FRACTIONS',
      prompt: 'A sack contains 6 GOLD prize spheres and 18 SILVER spheres (24 total). What is the simplified probability of drawing a GOLD prize sphere?',
      helperNote: 'Simplify 6/24 by dividing numerator and denominator by their greatest common divisor (6).',
      setup: {
        totalItems: 24,
        items: [
          { color: '#f59e0b', colorName: 'Gold', count: 6 },
          { color: '#94a3b8', colorName: 'Silver', count: 18 },
        ],
        targetColor: '#f59e0b',
        theoreticalFraction: { numerator: 1, denominator: 4, percentage: '25.0%', decimal: 0.25 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 1, denominator: 4, percentage: '25.0%' },
          label: '1 / 4 (Simplified from 6/24 = 25%)',
          isCorrect: true,
          feedbackText: '6/24 reduces to 1/4 = 25%.',
        },
        {
          id: 'b',
          fraction: { numerator: 1, denominator: 3, percentage: '33.3%' },
          label: '1 / 3 (6 / 18)',
          isCorrect: false,
          feedbackText: '6/18 is the ratio of Gold to Silver, not divided by Total (24).',
        },
        {
          id: 'c',
          fraction: { numerator: 3, denominator: 4, percentage: '75.0%' },
          label: '3 / 4 (75% Silver)',
          isCorrect: false,
          feedbackText: '3/4 is the probability of Silver.',
        },
        {
          id: 'd',
          fraction: { numerator: 1, denominator: 6, percentage: '16.7%' },
          label: '1 / 6 (16.7% Chance)',
          isCorrect: false,
          feedbackText: '6 / 24 simplifies to 1/4, not 1/6.',
        },
      ],
      correctAnswerId: 'a',
      explanation: '6 Gold / 24 Total = 6/24. Divide top and bottom by 6 gives 1/4 = 25%.',
      points: 120,
      goldTickets: 1,
    },
    {
      id: 'bag_04',
      activityId: 'mystery-bag',
      bloomLevel: 'understand',
      missionTitle: 'COMPARING BAG ODDS',
      prompt: 'In a sack with 8 BLUE spheres and 6 ORANGE spheres (14 total), which statement is mathematically TRUE?',
      helperNote: 'Compare P(Blue) = 8/14 with P(Orange) = 6/14.',
      setup: {
        totalItems: 14,
        items: [
          { color: '#2563eb', colorName: 'Blue', count: 8 },
          { color: '#ea580c', colorName: 'Orange', count: 6 },
        ],
        targetColor: '#2563eb',
        theoreticalFraction: { numerator: 8, denominator: 14, percentage: '57.1%', decimal: 0.571 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 8, denominator: 14, percentage: '57.1%' },
          label: 'Drawing Blue is LIKELY (> 50%)',
          isCorrect: true,
          feedbackText: '8/14 ≈ 57.1% which is greater than 50% (Likely).',
        },
        {
          id: 'b',
          fraction: { numerator: 6, denominator: 14, percentage: '42.9%' },
          label: 'Drawing Orange is EQUALLY LIKELY as Blue',
          isCorrect: false,
          feedbackText: '8 is greater than 6, so outcomes are not equally likely.',
        },
        {
          id: 'c',
          fraction: { numerator: 14, denominator: 14, percentage: '100%' },
          label: 'Drawing Blue is CERTAIN (100%)',
          isCorrect: false,
          feedbackText: 'It is possible to draw an Orange ball.',
        },
        {
          id: 'd',
          fraction: { numerator: 0, denominator: 14, percentage: '0%' },
          label: 'Drawing Orange is IMPOSSIBLE',
          isCorrect: false,
          feedbackText: 'There are 6 orange balls, so drawing orange is possible.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'P(Blue) = 8/14 ≈ 57.1% > 50%, which makes drawing Blue a Likely event.',
      points: 120,
      goldTickets: 1,
    },
    {
      id: 'bag_05',
      activityId: 'mystery-bag',
      bloomLevel: 'apply',
      missionTitle: 'COMPOUND "OR" EVENT',
      prompt: 'A sack holds 2 RED, 3 GREEN, and 5 WHITE balls (10 total). What is the probability of drawing a RED OR GREEN ball?',
      helperNote: 'For mutually exclusive outcomes: P(Red OR Green) = P(Red) + P(Green)',
      setup: {
        totalItems: 10,
        items: [
          { color: '#dc2626', colorName: 'Red', count: 2 },
          { color: '#16a34a', colorName: 'Green', count: 3 },
          { color: '#f8fafc', colorName: 'White', count: 5 },
        ],
        targetColor: '#16a34a',
        theoreticalFraction: { numerator: 5, denominator: 10, percentage: '50.0%', decimal: 0.5 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 5, denominator: 10, percentage: '50.0%' },
          label: '5 / 10 = 1 / 2 (50% Chance: Red or Green)',
          isCorrect: true,
          feedbackText: '2 Red + 3 Green = 5 favorable balls out of 10 = 5/10 = 50%.',
        },
        {
          id: 'b',
          fraction: { numerator: 2, denominator: 10, percentage: '20.0%' },
          label: '2 / 10 (Red only)',
          isCorrect: false,
          feedbackText: 'This ignores the 3 green balls.',
        },
        {
          id: 'c',
          fraction: { numerator: 3, denominator: 10, percentage: '30.0%' },
          label: '3 / 10 (Green only)',
          isCorrect: false,
          feedbackText: 'This ignores the 2 red balls.',
        },
        {
          id: 'd',
          fraction: { numerator: 6, denominator: 10, percentage: '60.0%' },
          label: '6 / 10 (60% Chance)',
          isCorrect: false,
          feedbackText: '2 + 3 = 5 favorable balls, not 6.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'Favorable balls = 2 Red + 3 Green = 5. P(Red or Green) = 5/10 = 1/2 = 50%.',
      points: 150,
      goldTickets: 2,
    },
  ],

  // ═══════════════════════════════════════════════════════════════════
  // 3. GIANT BALL DROP / PLINKO (5 Challenges)
  // ═══════════════════════════════════════════════════════════════════
  'ball-drop': [
    {
      id: 'drop_01',
      activityId: 'ball-drop',
      bloomLevel: 'evaluate',
      missionTitle: 'THEORETICAL VS EXPERIMENTAL DROP',
      prompt: 'The transparent tower is loaded with 8 GREEN balls and 2 YELLOW balls (10 total). What is the theoretical probability of a YELLOW ball dropping?',
      helperNote: 'After predicting, we will drop a ball, then run a batch of 10 trials!',
      setup: {
        totalItems: 10,
        items: [
          { color: '#16a34a', colorName: 'Green', count: 8 },
          { color: '#eab308', colorName: 'Yellow', count: 2 },
        ],
        targetColor: '#eab308',
        theoreticalFraction: { numerator: 2, denominator: 10, percentage: '20.0%', decimal: 0.2 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 2, denominator: 10, percentage: '20.0%' },
          label: '2 / 10 = 1 / 5 (20% Yellow)',
          isCorrect: true,
          feedbackText: '2 Yellow balls out of 10 = 2/10 = 20%.',
        },
        {
          id: 'b',
          fraction: { numerator: 8, denominator: 10, percentage: '80.0%' },
          label: '8 / 10 = 4 / 5 (80% Green)',
          isCorrect: false,
          feedbackText: '8/10 is the probability of Green.',
        },
        {
          id: 'c',
          fraction: { numerator: 2, denominator: 8, percentage: '25.0%' },
          label: '2 / 8 (Ratio of Yellow to Green)',
          isCorrect: false,
          feedbackText: '2/8 is the ratio, but probability requires dividing by total (10).',
        },
        {
          id: 'd',
          fraction: { numerator: 1, denominator: 10, percentage: '10.0%' },
          label: '1 / 10 (Single Ball Chance)',
          isCorrect: false,
          feedbackText: 'There are 2 yellow balls, not 1.',
        },
      ],
      correctAnswerId: 'a',
      explanation: '2 Yellow out of 10 Total = 2/10 = 1/5 = 20%. In 10 trials, experimental results will cluster around 20%!',
      points: 100,
      goldTickets: 1,
    },
    {
      id: 'drop_02',
      activityId: 'ball-drop',
      bloomLevel: 'apply',
      missionTitle: 'LAW OF LARGE NUMBERS',
      prompt: 'If a carnival chute has a winning probability of P(Win) = 1/4 (25%), how many wins would you EXPECT if you drop 40 balls down the tower?',
      helperNote: 'Expected Value = Total Drops × Probability of Winning',
      setup: {
        totalItems: 4,
        items: [
          { color: '#f59e0b', colorName: 'Win', count: 1 },
          { color: '#64748b', colorName: 'Loss', count: 3 },
        ],
        targetColor: '#f59e0b',
        theoreticalFraction: { numerator: 10, denominator: 40, percentage: '25.0%', decimal: 0.25 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 10, denominator: 40, percentage: '25.0%' },
          label: '10 Expected Wins (40 × 1/4)',
          isCorrect: true,
          feedbackText: '40 drops × 1/4 = 10 expected wins.',
        },
        {
          id: 'b',
          fraction: { numerator: 4, denominator: 40, percentage: '10.0%' },
          label: '4 Expected Wins',
          isCorrect: false,
          feedbackText: '4 wins would be 4/40 = 10%, which is too low.',
        },
        {
          id: 'c',
          fraction: { numerator: 20, denominator: 40, percentage: '50.0%' },
          label: '20 Expected Wins (Half)',
          isCorrect: false,
          feedbackText: '20 wins would require a 50% probability.',
        },
        {
          id: 'd',
          fraction: { numerator: 1, denominator: 40, percentage: '2.5%' },
          label: '1 Expected Win',
          isCorrect: false,
          feedbackText: '1/4 of 40 is 10.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'Expected Wins = 40 × (1/4) = 10 wins. As the number of trials increases, experimental results match expected value!',
      points: 100,
      goldTickets: 1,
    },
    {
      id: 'drop_03',
      activityId: 'ball-drop',
      bloomLevel: 'analyze',
      missionTitle: 'CENTER VS EDGE CHUTES',
      prompt: 'A Galton board peg tower funnels balls into 8 exit chutes: 6 CENTER chutes and 2 EDGE chutes. What is the probability of a ball landing in a CENTER chute?',
      helperNote: 'Center chutes = 6. Total chutes = 8.',
      setup: {
        totalItems: 8,
        items: [
          { color: '#2563eb', colorName: 'Center Chute', count: 6 },
          { color: '#dc2626', colorName: 'Edge Chute', count: 2 },
        ],
        targetColor: '#2563eb',
        theoreticalFraction: { numerator: 3, denominator: 4, percentage: '75.0%', decimal: 0.75 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 3, denominator: 4, percentage: '75.0%' },
          label: '6 / 8 = 3 / 4 (75% Center Chutes)',
          isCorrect: true,
          feedbackText: '6 Center chutes out of 8 = 6/8 = 3/4 = 75%.',
        },
        {
          id: 'b',
          fraction: { numerator: 1, denominator: 4, percentage: '25.0%' },
          label: '2 / 8 = 1 / 4 (25% Edge Chutes)',
          isCorrect: false,
          feedbackText: '2/8 is the probability of edge chutes.',
        },
        {
          id: 'c',
          fraction: { numerator: 1, denominator: 2, percentage: '50.0%' },
          label: '1 / 2 (Equal Chance)',
          isCorrect: false,
          feedbackText: 'Center chutes have more paths than edge chutes.',
        },
        {
          id: 'd',
          fraction: { numerator: 6, denominator: 2, percentage: '300%' },
          label: '6 / 2 (Chute Ratio)',
          isCorrect: false,
          feedbackText: '6/2 is the ratio, not the probability fraction.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'P(Center Chute) = 6/8 = 3/4 = 75%. Balls are 3 times more likely to drop into center bins!',
      points: 120,
      goldTickets: 1,
    },
    {
      id: 'drop_04',
      activityId: 'ball-drop',
      bloomLevel: 'understand',
      missionTitle: 'EVEN NUMBERED BINS',
      prompt: 'The ball drop tower has 6 collector bins numbered 1, 2, 3, 4, 5, 6. If a ball has an equal chance of landing in any bin, what is P(EVEN BIN)?',
      helperNote: 'Even bins: 2, 4, 6 (3 favorable bins out of 6).',
      setup: {
        totalItems: 6,
        items: [
          { color: '#16a34a', colorName: 'Even (2,4,6)', count: 3 },
          { color: '#f59e0b', colorName: 'Odd (1,3,5)', count: 3 },
        ],
        targetColor: '#16a34a',
        theoreticalFraction: { numerator: 1, denominator: 2, percentage: '50.0%', decimal: 0.5 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 1, denominator: 2, percentage: '50.0%' },
          label: '3 / 6 = 1 / 2 (50% Even Bins)',
          isCorrect: true,
          feedbackText: '3 Even bins (2, 4, 6) out of 6 Total = 3/6 = 1/2 = 50%.',
        },
        {
          id: 'b',
          fraction: { numerator: 1, denominator: 3, percentage: '33.3%' },
          label: '2 / 6 = 1 / 3',
          isCorrect: false,
          feedbackText: 'There are 3 even numbers (2, 4, 6), not 2.',
        },
        {
          id: 'c',
          fraction: { numerator: 2, denominator: 3, percentage: '66.7%' },
          label: '4 / 6 = 2 / 3',
          isCorrect: false,
          feedbackText: 'Only 3 of the 6 bins are even.',
        },
        {
          id: 'd',
          fraction: { numerator: 1, denominator: 6, percentage: '16.7%' },
          label: '1 / 6 (Single Bin)',
          isCorrect: false,
          feedbackText: '1/6 is the chance of one specific number.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'Bins 2, 4, and 6 are even (3 bins). P(Even) = 3/6 = 1/2 = 50%.',
      points: 120,
      goldTickets: 1,
    },
    {
      id: 'drop_05',
      activityId: 'ball-drop',
      bloomLevel: 'evaluate',
      missionTitle: 'EXPERIMENTAL VARIANCE ANALYSIS',
      prompt: 'A machine has theoretical P(Gold) = 2/10 (20%). In 10 experimental trials, 4 Gold balls dropped (40%). What explains this result?',
      helperNote: 'Think about sample size and random fluctuation.',
      setup: {
        totalItems: 10,
        items: [
          { color: '#f59e0b', colorName: 'Gold', count: 4 },
          { color: '#64748b', colorName: 'Silver', count: 6 },
        ],
        targetColor: '#f59e0b',
        theoreticalFraction: { numerator: 2, denominator: 10, percentage: '20.0%', decimal: 0.2 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 2, denominator: 10, percentage: '20.0%' },
          label: 'Small sample size causes short-term random variance',
          isCorrect: true,
          feedbackText: 'With only 10 trials, random variation is normal. Over 1,000 trials, it converges to 20%.',
        },
        {
          id: 'b',
          fraction: { numerator: 4, denominator: 10, percentage: '40.0%' },
          label: 'The theoretical probability was calculated wrong',
          isCorrect: false,
          feedbackText: 'The machine still has 2/10 theoretical odds.',
        },
        {
          id: 'c',
          fraction: { numerator: 10, denominator: 10, percentage: '100%' },
          label: 'Every 10-trial test will always result in 4 Gold balls',
          isCorrect: false,
          feedbackText: 'Each set of 10 trials will have different random outcomes.',
        },
        {
          id: 'd',
          fraction: { numerator: 0, denominator: 10, percentage: '0%' },
          label: 'Theoretical probability only applies to coins',
          isCorrect: false,
          feedbackText: 'Theoretical probability applies to all random experiments.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'In small samples (like 10 trials), natural variance occurs. Over hundreds of drops, experimental frequency approaches theoretical probability (Law of Large Numbers).',
      points: 150,
      goldTickets: 2,
    },
  ],

  // ═══════════════════════════════════════════════════════════════════
  // 4. THE PROBABILITY LAB (5 Challenges)
  // ═══════════════════════════════════════════════════════════════════
  'probability-lab': [
    {
      id: 'lab_01',
      activityId: 'probability-lab',
      bloomLevel: 'create',
      missionTitle: 'CHAMBER CALIBRATION: 3/5 PROBABILITY',
      prompt: 'The laboratory chamber needs exactly 5 balls loaded so that P(BLUE) = 3/5 (60%). Which combination of 3D balls satisfies this condition?',
      helperNote: 'Target: 3 Blue balls out of 5 total.',
      setup: {
        totalItems: 5,
        items: [
          { color: '#2563eb', colorName: 'Blue', count: 3 },
          { color: '#dc2626', colorName: 'Red', count: 2 },
        ],
        targetColor: '#2563eb',
        theoreticalFraction: { numerator: 3, denominator: 5, percentage: '60.0%', decimal: 0.6 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 3, denominator: 5, percentage: '60.0%' },
          label: '3 Blue Balls + 2 Red Balls (5 Total)',
          isCorrect: true,
          feedbackText: '3 Blue out of 5 Total gives P(Blue) = 3/5 = 60%.',
        },
        {
          id: 'b',
          fraction: { numerator: 2, denominator: 5, percentage: '40.0%' },
          label: '2 Blue Balls + 3 Red Balls (5 Total)',
          isCorrect: false,
          feedbackText: 'This would give P(Blue) = 2/5 = 40%.',
        },
        {
          id: 'c',
          fraction: { numerator: 3, denominator: 8, percentage: '37.5%' },
          label: '3 Blue Balls + 5 Red Balls (8 Total)',
          isCorrect: false,
          feedbackText: 'This gives 8 total balls, so P(Blue) = 3/8.',
        },
        {
          id: 'd',
          fraction: { numerator: 1, denominator: 5, percentage: '20.0%' },
          label: '1 Blue Ball + 4 Red Balls (5 Total)',
          isCorrect: false,
          feedbackText: 'This gives P(Blue) = 1/5 = 20%.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'To achieve P(Blue) = 3/5, 3 out of every 5 items in the chamber must be Blue.',
      points: 100,
      goldTickets: 1,
    },
    {
      id: 'lab_02',
      activityId: 'probability-lab',
      bloomLevel: 'apply',
      missionTitle: 'SCALING TO 16 SAMPLES',
      prompt: 'You need to configure a 16-ball chamber such that P(GREEN) = 25% (1/4). How many GREEN balls must be loaded?',
      helperNote: 'Calculate 1/4 of 16 balls: 16 × (1/4) = ?',
      setup: {
        totalItems: 16,
        items: [
          { color: '#16a34a', colorName: 'Green', count: 4 },
          { color: '#64748b', colorName: 'Other', count: 12 },
        ],
        targetColor: '#16a34a',
        theoreticalFraction: { numerator: 4, denominator: 16, percentage: '25.0%', decimal: 0.25 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 4, denominator: 16, percentage: '25.0%' },
          label: '4 Green Balls (4 / 16 = 25%)',
          isCorrect: true,
          feedbackText: '4 Green balls out of 16 = 4/16 = 1/4 = 25%.',
        },
        {
          id: 'b',
          fraction: { numerator: 8, denominator: 16, percentage: '50.0%' },
          label: '8 Green Balls (50%)',
          isCorrect: false,
          feedbackText: '8/16 = 50%, which is double the target of 25%.',
        },
        {
          id: 'c',
          fraction: { numerator: 2, denominator: 16, percentage: '12.5%' },
          label: '2 Green Balls (12.5%)',
          isCorrect: false,
          feedbackText: '2/16 = 12.5%, which is too low.',
        },
        {
          id: 'd',
          fraction: { numerator: 6, denominator: 16, percentage: '37.5%' },
          label: '6 Green Balls (37.5%)',
          isCorrect: false,
          feedbackText: '6/16 = 3/8 = 37.5%.',
        },
      ],
      correctAnswerId: 'a',
      explanation: '1/4 of 16 = 4 Green balls. Therefore, loading 4 Green balls gives exactly P(Green) = 4/16 = 25%.',
      points: 100,
      goldTickets: 1,
    },
    {
      id: 'lab_03',
      activityId: 'probability-lab',
      bloomLevel: 'analyze',
      missionTitle: 'ALTERING SAMPLE RATIOS',
      prompt: 'A chamber currently has 4 RED and 4 BLUE balls (8 total, 50% Red). How many RED balls must you ADD so that P(Red) becomes 60% (6/10)?',
      helperNote: 'If you add 2 Red balls: Total becomes 8 + 2 = 10 balls. Red becomes 4 + 2 = 6 balls.',
      setup: {
        totalItems: 10,
        items: [
          { color: '#dc2626', colorName: 'Red', count: 6 },
          { color: '#2563eb', colorName: 'Blue', count: 4 },
        ],
        targetColor: '#dc2626',
        theoreticalFraction: { numerator: 6, denominator: 10, percentage: '60.0%', decimal: 0.6 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 6, denominator: 10, percentage: '60.0%' },
          label: 'Add 2 Red Balls (6 Red out of 10 Total = 60%)',
          isCorrect: true,
          feedbackText: '4 + 2 = 6 Red balls. 8 + 2 = 10 total. 6/10 = 60%.',
        },
        {
          id: 'b',
          fraction: { numerator: 5, denominator: 9, percentage: '55.6%' },
          label: 'Add 1 Red Ball (5/9 ≈ 55.6%)',
          isCorrect: false,
          feedbackText: 'Adding 1 Red ball gives 5/9 ≈ 55.6%, not 60%.',
        },
        {
          id: 'c',
          fraction: { numerator: 7, denominator: 11, percentage: '63.6%' },
          label: 'Add 3 Red Balls (7/11 ≈ 63.6%)',
          isCorrect: false,
          feedbackText: 'Adding 3 Red balls gives 7/11 ≈ 63.6%.',
        },
        {
          id: 'd',
          fraction: { numerator: 8, denominator: 12, percentage: '66.7%' },
          label: 'Add 4 Red Balls (8/12 = 66.7%)',
          isCorrect: false,
          feedbackText: 'Adding 4 Red balls gives 8/12 = 66.7%.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'Adding 2 Red balls gives 6 Red out of 10 total balls: P(Red) = 6/10 = 60%.',
      points: 120,
      goldTickets: 1,
    },
    {
      id: 'lab_04',
      activityId: 'probability-lab',
      bloomLevel: 'understand',
      missionTitle: 'EQUAL LIKELIHOOD BALANCE',
      prompt: 'To make 3 colors (RED, GREEN, YELLOW) equally likely in a 15-ball alchemical vessel, how many of EACH color must be present?',
      helperNote: 'Equally likely with 3 colors: 15 ÷ 3 = ?',
      setup: {
        totalItems: 15,
        items: [
          { color: '#dc2626', colorName: 'Red', count: 5 },
          { color: '#16a34a', colorName: 'Green', count: 5 },
          { color: '#eab308', colorName: 'Yellow', count: 5 },
        ],
        targetColor: '#16a34a',
        theoreticalFraction: { numerator: 1, denominator: 3, percentage: '33.3%', decimal: 0.333 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 5, denominator: 15, percentage: '33.3%' },
          label: '5 of each color (P = 5/15 = 1/3)',
          isCorrect: true,
          feedbackText: '5 Red, 5 Green, 5 Yellow gives P = 1/3 for each color.',
        },
        {
          id: 'b',
          fraction: { numerator: 6, denominator: 15, percentage: '40.0%' },
          label: '6 Red, 5 Green, 4 Yellow',
          isCorrect: false,
          feedbackText: 'Red would have a higher probability than Yellow.',
        },
        {
          id: 'c',
          fraction: { numerator: 7, denominator: 15, percentage: '46.7%' },
          label: '7 Red, 7 Green, 1 Yellow',
          isCorrect: false,
          feedbackText: 'Yellow would be much less likely.',
        },
        {
          id: 'd',
          fraction: { numerator: 3, denominator: 15, percentage: '20.0%' },
          label: '3 of each color (9 Total)',
          isCorrect: false,
          feedbackText: '3 of each would only be 9 total balls, not 15.',
        },
      ],
      correctAnswerId: 'a',
      explanation: '15 / 3 colors = 5 balls each. Every color has P = 5/15 = 1/3 ≈ 33.3%.',
      points: 120,
      goldTickets: 1,
    },
    {
      id: 'lab_05',
      activityId: 'probability-lab',
      bloomLevel: 'apply',
      missionTitle: 'COMPOUND SAMPLE SPACES',
      prompt: 'The alchemical condenser contains 7 CRYSTAL, 3 EMBER, and 10 VOID elements (20 total). What is P(NOT VOID)?',
      helperNote: 'Non-Void elements = Crystal (7) + Ember (3) = 10.',
      setup: {
        totalItems: 20,
        items: [
          { color: '#38bdf8', colorName: 'Crystal', count: 7 },
          { color: '#f97316', colorName: 'Ember', count: 3 },
          { color: '#1e1b4b', colorName: 'Void', count: 10 },
        ],
        targetColor: '#38bdf8',
        theoreticalFraction: { numerator: 1, denominator: 2, percentage: '50.0%', decimal: 0.5 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 10, denominator: 20, percentage: '50.0%' },
          label: '10 / 20 = 1 / 2 (50% Not Void)',
          isCorrect: true,
          feedbackText: '7 Crystal + 3 Ember = 10 non-void elements out of 20 = 10/20 = 50%.',
        },
        {
          id: 'b',
          fraction: { numerator: 10, denominator: 20, percentage: '50.0%' },
          label: '7 / 20 = 35% (Crystal only)',
          isCorrect: false,
          feedbackText: 'Ember is also not void.',
        },
        {
          id: 'c',
          fraction: { numerator: 3, denominator: 20, percentage: '15.0%' },
          label: '3 / 20 = 15% (Ember only)',
          isCorrect: false,
          feedbackText: 'Crystal is also not void.',
        },
        {
          id: 'd',
          fraction: { numerator: 17, denominator: 20, percentage: '85.0%' },
          label: '17 / 20 = 85%',
          isCorrect: false,
          feedbackText: 'There are 10 non-void elements, not 17.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'Non-void items = 7 + 3 = 10. P(Not Void) = 10/20 = 1/2 = 50%.',
      points: 150,
      goldTickets: 2,
    },
  ],

  // ═══════════════════════════════════════════════════════════════════
  // 5. CARNIVAL GAME BUILDER (5 Challenges)
  // ═══════════════════════════════════════════════════════════════════
  'game-builder': [
    {
      id: 'build_01',
      activityId: 'game-builder',
      bloomLevel: 'create',
      missionTitle: 'CONSTRUCT A WINNING GAME: 3/10',
      prompt: 'Construct a carnival pegboard game with 10 slots where the probability of a player winning a prize is exactly 3/10 (30%). How many WINNING slots must be placed?',
      helperNote: 'Total slots = 10. Winning slots = ?',
      setup: {
        totalItems: 10,
        items: [
          { color: '#16a34a', colorName: 'Win', count: 3 },
          { color: '#dc2626', colorName: 'Try Again', count: 7 },
        ],
        targetColor: '#16a34a',
        theoreticalFraction: { numerator: 3, denominator: 10, percentage: '30.0%', decimal: 0.3 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 3, denominator: 10, percentage: '30.0%' },
          label: '3 Winning Slots + 7 Losing Slots (10 Total)',
          isCorrect: true,
          feedbackText: '3 Winning slots out of 10 = 3/10 = 30%.',
        },
        {
          id: 'b',
          fraction: { numerator: 4, denominator: 10, percentage: '40.0%' },
          label: '4 Winning Slots + 6 Losing Slots (10 Total)',
          isCorrect: false,
          feedbackText: 'This gives P(Win) = 4/10 = 40%.',
        },
        {
          id: 'c',
          fraction: { numerator: 1, denominator: 3, percentage: '33.3%' },
          label: '1 Winning Slot + 2 Losing Slots (3 Total)',
          isCorrect: false,
          feedbackText: 'The board requires 10 slots in total.',
        },
        {
          id: 'd',
          fraction: { numerator: 7, denominator: 10, percentage: '70.0%' },
          label: '7 Winning Slots + 3 Losing Slots (10 Total)',
          isCorrect: false,
          feedbackText: 'This gives 70% win chance, which is too high.',
        },
      ],
      correctAnswerId: 'a',
      explanation: '3 winning slots out of 10 total slots satisfies P(Win) = 3/10 = 30%.',
      points: 100,
      goldTickets: 1,
    },
    {
      id: 'build_02',
      activityId: 'game-builder',
      bloomLevel: 'apply',
      missionTitle: 'DESIGNING A 1/6 ODDS BOARD',
      prompt: 'You are building a 12-slot prize board. To make the probability of winning a plush bear exactly 1/6, how many WINNING slots should you build?',
      helperNote: 'Calculate 1/6 of 12 slots: 12 × (1/6) = ?',
      setup: {
        totalItems: 12,
        items: [
          { color: '#16a34a', colorName: 'Win Plush Bear', count: 2 },
          { color: '#dc2626', colorName: 'No Prize', count: 10 },
        ],
        targetColor: '#16a34a',
        theoreticalFraction: { numerator: 1, denominator: 6, percentage: '16.7%', decimal: 0.167 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 2, denominator: 12, percentage: '16.7%' },
          label: '2 Winning Slots (2 / 12 = 1 / 6)',
          isCorrect: true,
          feedbackText: '2 winning slots out of 12 = 2/12 = 1/6 ≈ 16.7%.',
        },
        {
          id: 'b',
          fraction: { numerator: 1, denominator: 12, percentage: '8.3%' },
          label: '1 Winning Slot (1 / 12)',
          isCorrect: false,
          feedbackText: '1/12 is half of 1/6.',
        },
        {
          id: 'c',
          fraction: { numerator: 6, denominator: 12, percentage: '50.0%' },
          label: '6 Winning Slots (1 / 2)',
          isCorrect: false,
          feedbackText: '6/12 is 50%, not 1/6.',
        },
        {
          id: 'd',
          fraction: { numerator: 3, denominator: 12, percentage: '25.0%' },
          label: '3 Winning Slots (1 / 4)',
          isCorrect: false,
          feedbackText: '3/12 = 1/4 = 25%.',
        },
      ],
      correctAnswerId: 'a',
      explanation: '1/6 of 12 slots = 2 winning slots. P(Win) = 2/12 = 1/6 ≈ 16.7%.',
      points: 100,
      goldTickets: 1,
    },
    {
      id: 'build_03',
      activityId: 'game-builder',
      bloomLevel: 'analyze',
      missionTitle: 'JACKPOT VS MINOR PRIZE SLOTS',
      prompt: 'A carnival wheel has 20 slots: 1 GRAND JACKPOT, 4 MINOR PRIZES, and 15 NO PRIZE. What is the probability that a player wins ANY prize?',
      helperNote: 'Total prize slots = 1 (Grand) + 4 (Minor) = 5 prize slots out of 20 total.',
      setup: {
        totalItems: 20,
        items: [
          { color: '#f59e0b', colorName: 'Grand Jackpot', count: 1 },
          { color: '#3b82f6', colorName: 'Minor Prize', count: 4 },
          { color: '#64748b', colorName: 'No Prize', count: 15 },
        ],
        targetColor: '#f59e0b',
        theoreticalFraction: { numerator: 1, denominator: 4, percentage: '25.0%', decimal: 0.25 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 5, denominator: 20, percentage: '25.0%' },
          label: '5 / 20 = 1 / 4 (25% Any Prize)',
          isCorrect: true,
          feedbackText: '1 Jackpot + 4 Minor = 5 winning slots out of 20 = 5/20 = 25%.',
        },
        {
          id: 'b',
          fraction: { numerator: 1, denominator: 20, percentage: '5.0%' },
          label: '1 / 20 = 5% (Grand Jackpot only)',
          isCorrect: false,
          feedbackText: 'This ignores the 4 minor prizes.',
        },
        {
          id: 'c',
          fraction: { numerator: 4, denominator: 20, percentage: '20.0%' },
          label: '4 / 20 = 20% (Minor Prize only)',
          isCorrect: false,
          feedbackText: 'This ignores the grand jackpot.',
        },
        {
          id: 'd',
          fraction: { numerator: 15, denominator: 20, percentage: '75.0%' },
          label: '15 / 20 = 75% (No Prize)',
          isCorrect: false,
          feedbackText: '15/20 is the probability of winning nothing.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'Total winning slots = 1 + 4 = 5. P(Any Prize) = 5/20 = 1/4 = 25%.',
      points: 120,
      goldTickets: 1,
    },
    {
      id: 'build_04',
      activityId: 'game-builder',
      bloomLevel: 'apply',
      missionTitle: 'DOUBLING WINNING CHANCES',
      prompt: 'A game currently has 2 winning slots out of 10 (20%). To DOUBLE the probability of winning to 40% while keeping 10 total slots, what change is needed?',
      helperNote: 'Target: 40% of 10 slots = 4 winning slots.',
      setup: {
        totalItems: 10,
        items: [
          { color: '#16a34a', colorName: 'Win', count: 4 },
          { color: '#dc2626', colorName: 'Loss', count: 6 },
        ],
        targetColor: '#16a34a',
        theoreticalFraction: { numerator: 4, denominator: 10, percentage: '40.0%', decimal: 0.4 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 4, denominator: 10, percentage: '40.0%' },
          label: 'Replace 2 losing slots with 2 winning slots (4 Wins / 10)',
          isCorrect: true,
          feedbackText: 'Changing to 4 winning slots out of 10 gives 4/10 = 40%.',
        },
        {
          id: 'b',
          fraction: { numerator: 3, denominator: 10, percentage: '30.0%' },
          label: 'Add 1 winning slot (3 Wins / 10 = 30%)',
          isCorrect: false,
          feedbackText: '3/10 is only 30%, not double (40%).',
        },
        {
          id: 'c',
          fraction: { numerator: 5, denominator: 10, percentage: '50.0%' },
          label: 'Make 5 winning slots (50%)',
          isCorrect: false,
          feedbackText: '5/10 is 50%, not 40%.',
        },
        {
          id: 'd',
          fraction: { numerator: 2, denominator: 5, percentage: '40.0%' },
          label: 'Remove 5 losing slots (2 Wins / 5 Total)',
          isCorrect: false,
          feedbackText: 'The board must keep 10 total slots.',
        },
      ],
      correctAnswerId: 'a',
      explanation: '40% of 10 slots = 4 winning slots. Replace 2 losing slots to have 4 winning slots total.',
      points: 120,
      goldTickets: 1,
    },
    {
      id: 'build_05',
      activityId: 'game-builder',
      bloomLevel: 'create',
      missionTitle: 'EQUALIZING A BIASED BOARD',
      prompt: 'A carnival board has 9 losing slots and only 1 winning slot (10 total). To transform this into a FAIR 50/50 game without removing slots, how many winning slots must be ADDED?',
      helperNote: 'If you have 9 losing slots, you need 9 winning slots for a 50/50 chance! 9 - 1 = ?',
      setup: {
        totalItems: 18,
        items: [
          { color: '#16a34a', colorName: 'Win', count: 9 },
          { color: '#dc2626', colorName: 'Loss', count: 9 },
        ],
        targetColor: '#16a34a',
        theoreticalFraction: { numerator: 1, denominator: 2, percentage: '50.0%', decimal: 0.5 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 9, denominator: 18, percentage: '50.0%' },
          label: 'Add 8 Winning Slots (9 Wins + 9 Losses = 18 Total = 50%)',
          isCorrect: true,
          feedbackText: '1 + 8 = 9 winning slots. 9 wins out of 18 slots = 50% (Fair Game).',
        },
        {
          id: 'b',
          fraction: { numerator: 5, denominator: 14, percentage: '35.7%' },
          label: 'Add 4 Winning Slots (5 Wins / 14 Total)',
          isCorrect: false,
          feedbackText: '5/14 is only 35.7%, not 50%.',
        },
        {
          id: 'c',
          fraction: { numerator: 9, denominator: 10, percentage: '90.0%' },
          label: 'Add 9 Winning Slots (10 Wins / 19 Total)',
          isCorrect: false,
          feedbackText: '10/19 ≈ 52.6%, not exactly 50%.',
        },
        {
          id: 'd',
          fraction: { numerator: 1, denominator: 2, percentage: '50.0%' },
          label: 'Add 1 Winning Slot',
          isCorrect: false,
          feedbackText: '2 wins out of 11 is only 18.2%.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'There are 9 losing slots, so we need 9 winning slots. Since 1 already exists, add 8 winning slots (9/18 = 50%).',
      points: 150,
      goldTickets: 2,
    },
  ],

  // ═══════════════════════════════════════════════════════════════════
  // 6. GRAND CARNIVAL FINALE (5 Challenges)
  // ═══════════════════════════════════════════════════════════════════
  'grand-carnival': [
    {
      id: 'grand_01',
      activityId: 'grand-carnival',
      bloomLevel: 'evaluate',
      missionTitle: 'THE GRAND CARNIVAL COMPARISON',
      prompt:
        'Compare three carnival prize games:\n• Game A: 4 wins out of 10 (4/10)\n• Game B: 1 win out of 3 (1/3)\n• Game C: 2 wins out of 5 (2/5)\nWhich game gives you the LOWEST probability of winning?',
      helperNote: 'Convert all fractions to percentages to compare accurately!',
      setup: {
        totalItems: 3,
        items: [
          { color: '#dc2626', colorName: 'Game B (1/3)', count: 1 },
          { color: '#2563eb', colorName: 'Game A (4/10)', count: 1 },
          { color: '#16a34a', colorName: 'Game C (2/5)', count: 1 },
        ],
        targetColor: '#dc2626',
        theoreticalFraction: { numerator: 1, denominator: 3, percentage: '33.3%', decimal: 0.333 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 1, denominator: 3, percentage: '33.3%' },
          label: 'Game B (1/3 ≈ 33.3% is lower than 40%)',
          isCorrect: true,
          feedbackText: 'Game A = 40%, Game C = 40%, but Game B = 33.3% (Lowest!).',
        },
        {
          id: 'b',
          fraction: { numerator: 4, denominator: 10, percentage: '40.0%' },
          label: 'Game A (4/10 = 40%)',
          isCorrect: false,
          feedbackText: '4/10 = 40%, which is higher than Game B (33.3%).',
        },
        {
          id: 'c',
          fraction: { numerator: 2, denominator: 5, percentage: '40.0%' },
          label: 'Game C (2/5 = 40%)',
          isCorrect: false,
          feedbackText: '2/5 = 40%, which is tied with Game A.',
        },
        {
          id: 'd',
          fraction: { numerator: 3, denominator: 3, percentage: '100%' },
          label: 'All games have equal winning chances',
          isCorrect: false,
          feedbackText: 'Game B is 33.3% while Games A & C are 40%.',
        },
      ],
      correctAnswerId: 'a',
      explanation: '4/10 = 40% and 2/5 = 40%. Game B is 1/3 ≈ 33.3%, which is the lowest probability of winning.',
      points: 150,
      goldTickets: 2,
    },
    {
      id: 'grand_02',
      activityId: 'grand-carnival',
      bloomLevel: 'apply',
      missionTitle: 'TICKET VALUE EXPECTATION',
      prompt: 'A carnival attraction costs 1 token to play. You have a 1/5 (20%) chance of winning 10 tokens, and 4/5 (80%) chance of winning 0 tokens. What is the expected token payout per play?',
      helperNote: 'Expected Value = (1/5 × 10) + (4/5 × 0) = ?',
      setup: {
        totalItems: 5,
        items: [
          { color: '#f59e0b', colorName: '10 Tokens Win', count: 1 },
          { color: '#64748b', colorName: '0 Tokens', count: 4 },
        ],
        targetColor: '#f59e0b',
        theoreticalFraction: { numerator: 2, denominator: 1, percentage: '200%', decimal: 2.0 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 2, denominator: 1, percentage: '2 Tokens' },
          label: '2 Tokens Expected Payout ((1/5 × 10) = 2)',
          isCorrect: true,
          feedbackText: '1/5 of 10 tokens = 2 tokens average payout per play.',
        },
        {
          id: 'b',
          fraction: { numerator: 1, denominator: 1, percentage: '1 Token' },
          label: '1 Token Expected Payout',
          isCorrect: false,
          feedbackText: '1/5 × 10 = 2, not 1.',
        },
        {
          id: 'c',
          fraction: { numerator: 10, denominator: 1, percentage: '10 Tokens' },
          label: '10 Tokens Expected Payout',
          isCorrect: false,
          feedbackText: 'You do not win 10 tokens on every play.',
        },
        {
          id: 'd',
          fraction: { numerator: 0, denominator: 1, percentage: '0 Tokens' },
          label: '0 Tokens Expected Payout',
          isCorrect: false,
          feedbackText: 'The average payout is positive.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'Expected Value = (1/5 × 10) + (4/5 × 0) = 2 + 0 = 2 tokens per play.',
      points: 150,
      goldTickets: 2,
    },
    {
      id: 'grand_03',
      activityId: 'grand-carnival',
      bloomLevel: 'analyze',
      missionTitle: 'INDEPENDENT DUAL SPINNER',
      prompt: 'In a 2-stage carnival challenge, you spin Spinner A (1/2 chance of Gold) and Spinner B (1/3 chance of Star). What is the probability of winning BOTH (Gold AND Star)?',
      helperNote: 'For independent events: P(A and B) = P(A) × P(B)',
      setup: {
        totalItems: 6,
        items: [
          { color: '#f59e0b', colorName: 'Both Gold & Star', count: 1 },
          { color: '#64748b', colorName: 'Other Outcomes', count: 5 },
        ],
        targetColor: '#f59e0b',
        theoreticalFraction: { numerator: 1, denominator: 6, percentage: '16.7%', decimal: 0.167 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 1, denominator: 6, percentage: '16.7%' },
          label: '1 / 6 (1/2 × 1/3 = 1/6 ≈ 16.7%)',
          isCorrect: true,
          feedbackText: 'Multiply probabilities: 1/2 × 1/3 = 1/6 ≈ 16.7%.',
        },
        {
          id: 'b',
          fraction: { numerator: 5, denominator: 6, percentage: '83.3%' },
          label: '5 / 6 (1/2 + 1/3)',
          isCorrect: false,
          feedbackText: 'Probabilities of independent compound events multiply, not add.',
        },
        {
          id: 'c',
          fraction: { numerator: 1, denominator: 5, percentage: '20.0%' },
          label: '1 / 5 (2 + 3 = 5)',
          isCorrect: false,
          feedbackText: 'Sample space is 2 × 3 = 6 possible outcomes.',
        },
        {
          id: 'd',
          fraction: { numerator: 2, denominator: 3, percentage: '66.7%' },
          label: '2 / 3 (66.7% Chance)',
          isCorrect: false,
          feedbackText: 'Winning both is less likely than winning either one alone.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'P(Gold AND Star) = P(Gold) × P(Star) = (1/2) × (1/3) = 1/6 ≈ 16.7%.',
      points: 180,
      goldTickets: 2,
    },
    {
      id: 'grand_04',
      activityId: 'grand-carnival',
      bloomLevel: 'evaluate',
      missionTitle: 'HIGHEST CHANCE ATTRACTION',
      prompt: 'You have only one gold ticket remaining! Which attraction gives the HIGHEST probability of winning:\n• Attraction X: 7 wins in 12 plays (7/12 ≈ 58.3%)\n• Attraction Y: 3 wins in 5 plays (3/5 = 60.0%)\n• Attraction Z: 5 wins in 8 plays (5/8 = 62.5%)',
      helperNote: 'Compare: 58.3% vs 60.0% vs 62.5%',
      setup: {
        totalItems: 3,
        items: [
          { color: '#16a34a', colorName: 'Attraction Z (5/8)', count: 1 },
          { color: '#2563eb', colorName: 'Attraction Y (3/5)', count: 1 },
          { color: '#ea580c', colorName: 'Attraction X (7/12)', count: 1 },
        ],
        targetColor: '#16a34a',
        theoreticalFraction: { numerator: 5, denominator: 8, percentage: '62.5%', decimal: 0.625 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 5, denominator: 8, percentage: '62.5%' },
          label: 'Attraction Z (5/8 = 62.5% is the Highest)',
          isCorrect: true,
          feedbackText: '5/8 = 62.5% > 3/5 (60%) > 7/12 (58.3%). Attraction Z is the best!',
        },
        {
          id: 'b',
          fraction: { numerator: 3, denominator: 5, percentage: '60.0%' },
          label: 'Attraction Y (3/5 = 60%)',
          isCorrect: false,
          feedbackText: '60.0% is less than 62.5%.',
        },
        {
          id: 'c',
          fraction: { numerator: 7, denominator: 12, percentage: '58.3%' },
          label: 'Attraction X (7/12 ≈ 58.3%)',
          isCorrect: false,
          feedbackText: '58.3% is the lowest of the three.',
        },
        {
          id: 'd',
          fraction: { numerator: 1, denominator: 1, percentage: '100%' },
          label: 'All attractions have identical winning odds',
          isCorrect: false,
          feedbackText: 'The probabilities are 58.3%, 60.0%, and 62.5%.',
        },
      ],
      correctAnswerId: 'a',
      explanation: '7/12 ≈ 58.3%, 3/5 = 60.0%, and 5/8 = 62.5%. Attraction Z offers the highest probability.',
      points: 180,
      goldTickets: 2,
    },
    {
      id: 'grand_05',
      activityId: 'grand-carnival',
      bloomLevel: 'create',
      missionTitle: 'CARNIVAL GRAND MASTER RIDDLE',
      prompt: 'A master bag contains 30 balls in 4 colors. P(Red) = 1/3, P(Blue) = 2/5, P(Green) = 1/6, and the remaining balls are GOLD. What is the probability of drawing a GOLD ball?',
      helperNote: 'Find common denominator (30): Red = 10/30, Blue = 12/30, Green = 5/30. Gold = ?',
      setup: {
        totalItems: 30,
        items: [
          { color: '#dc2626', colorName: 'Red', count: 10 },
          { color: '#2563eb', colorName: 'Blue', count: 12 },
          { color: '#16a34a', colorName: 'Green', count: 5 },
          { color: '#f59e0b', colorName: 'Gold', count: 3 },
        ],
        targetColor: '#f59e0b',
        theoreticalFraction: { numerator: 1, denominator: 10, percentage: '10.0%', decimal: 0.1 },
      },
      choices: [
        {
          id: 'a',
          fraction: { numerator: 3, denominator: 30, percentage: '10.0%' },
          label: '3 / 30 = 1 / 10 (10% Gold Balls)',
          isCorrect: true,
          feedbackText: '10 (Red) + 12 (Blue) + 5 (Green) = 27 balls. 30 - 27 = 3 Gold balls = 3/30 = 10%.',
        },
        {
          id: 'b',
          fraction: { numerator: 5, denominator: 30, percentage: '16.7%' },
          label: '5 / 30 = 1 / 6 (Green chance)',
          isCorrect: false,
          feedbackText: '5/30 is the probability of Green.',
        },
        {
          id: 'c',
          fraction: { numerator: 2, denominator: 30, percentage: '6.7%' },
          label: '2 / 30 (6.7% Chance)',
          isCorrect: false,
          feedbackText: '30 - (10 + 12 + 5) = 3 Gold balls, not 2.',
        },
        {
          id: 'd',
          fraction: { numerator: 4, denominator: 30, percentage: '13.3%' },
          label: '4 / 30 (13.3% Chance)',
          isCorrect: false,
          feedbackText: '30 - 27 = 3 balls.',
        },
      ],
      correctAnswerId: 'a',
      explanation: 'Red = 10, Blue = 12, Green = 5. Total = 27 balls. Remaining Gold = 30 - 27 = 3 balls. P(Gold) = 3/30 = 1/10 = 10%.',
      points: 200,
      goldTickets: 3,
    },
  ],
};
