// ============================================================
// PATTERN RACERS — 100+ Question Bank for Grade 6
// Curriculum: Sequences, Arithmetic Progressions & Function Machines
// Rich mathematical metadata: Common Differences, In/Out rules, Misconceptions
// Tailored for Grade 6: Clean Whole Numbers, Mental Math, High-Energy Racing Theme
// ============================================================

import { SequenceChallenge, RoundNumber } from '../types';

export const PATTERN_CHALLENGE_BANK: SequenceChallenge[] = [
  // ============================================================
  // ── ROUND 1: PATTERN TRACK (Find Common Difference / Step) ──
  // ============================================================
  {
    id: 'r1-001',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'easy',
    title: 'Turbo Ascent Sequence (+3)',
    instruction: 'Determine the constant step rule to extend the track segment.',
    sequence: [2, 5, 8, 11, 14],
    missingIndex: 4,
    commonDifference: 3,
    expectedStep: 3,
    expectedNextTerm: 14,
    ruleDescription: 'Add 3 each step (+3)',
    misconceptionTip: '💡 Step Difference: Check the gap between adjacent numbers (5 - 2 = 3).',
    mathExplanation: 'The common difference is d = 8 - 5 = +3. Starting at 2, adding 3 repeatedly gives 2, 5, 8, 11, 14.',
  },
  {
    id: 'r1-002',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'easy',
    title: 'Speedway Leap (+4)',
    instruction: 'Find the step difference driving this acceleration pattern.',
    sequence: [3, 7, 11, 15, 19],
    missingIndex: 4,
    commonDifference: 4,
    expectedStep: 4,
    expectedNextTerm: 19,
    ruleDescription: 'Add 4 each step (+4)',
    misconceptionTip: '💡 Constant Step: Subtract any term from the next term (11 - 7 = 4).',
    mathExplanation: 'd = 7 - 3 = +4. 15 + 4 = 19.',
  },
  {
    id: 'r1-003',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'easy',
    title: 'Pitlane Descent (-2)',
    instruction: 'The vehicle is braking into the pit lane. Identify the negative step difference.',
    sequence: [20, 18, 16, 14, 12],
    missingIndex: 4,
    commonDifference: -2,
    expectedStep: -2,
    expectedNextTerm: 12,
    ruleDescription: 'Subtract 2 each step (-2)',
    misconceptionTip: '💡 Decreasing Sequence: When numbers go down, the step is negative (18 - 20 = -2).',
    mathExplanation: 'd = 16 - 18 = -2. 14 - 2 = 12.',
  },
  {
    id: 'r1-004',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'easy',
    title: 'High-Gear Fives (+5)',
    instruction: 'Calibrate the track hydraulic lift using the common difference.',
    sequence: [5, 10, 15, 20, 25],
    missingIndex: 4,
    commonDifference: 5,
    expectedStep: 5,
    expectedNextTerm: 25,
    ruleDescription: 'Add 5 each step (+5)',
    misconceptionTip: '💡 Multiples of 5: Notice the pattern increases by exactly 5 units every step.',
    mathExplanation: 'd = 10 - 5 = +5. 20 + 5 = 25.',
  },
  {
    id: 'r1-005',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'medium',
    title: 'Chicane Seven Sprint (+7)',
    instruction: 'Find the common difference to connect the chicane track.',
    sequence: [4, 11, 18, 25, 32],
    missingIndex: 4,
    commonDifference: 7,
    expectedStep: 7,
    expectedNextTerm: 32,
    ruleDescription: 'Add 7 each step (+7)',
    misconceptionTip: '💡 Check Two Pairs: 11 - 4 = 7, and 18 - 11 = 7. The step is +7.',
    mathExplanation: 'd = +7. 25 + 7 = 32.',
  },
  {
    id: 'r1-006',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'medium',
    title: 'Deceleration Ramp (-5)',
    instruction: 'Calculate the braking sequence step.',
    sequence: [45, 40, 35, 30, 25],
    missingIndex: 4,
    commonDifference: -5,
    expectedStep: -5,
    expectedNextTerm: 25,
    ruleDescription: 'Subtract 5 each step (-5)',
    misconceptionTip: '💡 Sign Check: Decreasing by 5 means the step value is -5.',
    mathExplanation: 'd = 40 - 45 = -5. 30 + (-5) = 25.',
  },
  {
    id: 'r1-007',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'medium',
    title: 'Six-Cylinder Rhythm (+6)',
    instruction: 'Identify the common difference in engine telemetry.',
    sequence: [6, 12, 18, 24, 30],
    missingIndex: 4,
    commonDifference: 6,
    expectedStep: 6,
    expectedNextTerm: 30,
    ruleDescription: 'Add 6 each step (+6)',
    misconceptionTip: '💡 Difference: 12 - 6 = 6. 24 + 6 = 30.',
    mathExplanation: 'd = +6. Adding 6 to 24 gives 30.',
  },
  {
    id: 'r1-008',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'easy',
    title: 'Warm-up Laps (+2)',
    instruction: 'Calculate the basic warm-up lap pace step.',
    sequence: [6, 8, 10, 12, 14],
    missingIndex: 4,
    commonDifference: 2,
    expectedStep: 2,
    expectedNextTerm: 14,
    ruleDescription: 'Add 2 each step (+2)',
    misconceptionTip: '💡 Even Step: The numbers increase by 2 each time (8 - 6 = 2).',
    mathExplanation: 'd = +2. 12 + 2 = 14.',
  },
  {
    id: 'r1-009',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'medium',
    title: 'Braking Run (-4)',
    instruction: 'Determine the brake deceleration factor.',
    sequence: [32, 28, 24, 20, 16],
    missingIndex: 4,
    commonDifference: -4,
    expectedStep: -4,
    expectedNextTerm: 16,
    ruleDescription: 'Subtract 4 each step (-4)',
    misconceptionTip: '💡 Negative Step: 28 - 32 = -4.',
    mathExplanation: 'd = -4. 20 - 4 = 16.',
  },
  {
    id: 'r1-010',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'easy',
    title: 'Straightaway Tens (+10)',
    instruction: 'Determine the straightaway distance progression step.',
    sequence: [10, 20, 30, 40, 50],
    missingIndex: 4,
    commonDifference: 10,
    expectedStep: 10,
    expectedNextTerm: 50,
    ruleDescription: 'Add 10 each step (+10)',
    misconceptionTip: '💡 Tens Progression: Add 10 to 40 to get 50.',
    mathExplanation: 'd = +10. 40 + 10 = 50.',
  },
  {
    id: 'r1-011',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'medium',
    title: 'Downhill Descent (-3)',
    instruction: 'Determine the elevation drop rate per segment.',
    sequence: [27, 24, 21, 18, 15],
    missingIndex: 4,
    commonDifference: -3,
    expectedStep: -3,
    expectedNextTerm: 15,
    ruleDescription: 'Subtract 3 each step (-3)',
    misconceptionTip: '💡 Downward Step: 24 - 27 = -3.',
    mathExplanation: 'd = -3. 18 - 3 = 15.',
  },
  {
    id: 'r1-012',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'medium',
    title: 'Nitro Step (+8)',
    instruction: 'Find the acceleration sequence step difference.',
    sequence: [1, 9, 17, 25, 33],
    missingIndex: 4,
    commonDifference: 8,
    expectedStep: 8,
    expectedNextTerm: 33,
    ruleDescription: 'Add 8 each step (+8)',
    misconceptionTip: '💡 Step Size: 9 - 1 = 8. Check 17 - 9 = 8.',
    mathExplanation: 'd = +8. 25 + 8 = 33.',
  },

  // ============================================================
  // ── ROUND 2: SEQUENCE BUILDER (Start Value + Step) ──
  // ============================================================
  {
    id: 'r2-001',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'easy',
    title: 'Formula Path Constructor (Start: 20, Step: -3)',
    instruction: 'Configure the Track Builder with Start = 20, Step = -3.',
    sequence: [20, 17, 14, 11, 8],
    startValue: 20,
    commonDifference: -3,
    expectedStep: -3,
    expectedNextTerm: 8,
    ruleDescription: 'Start at 20, step -3',
    misconceptionTip: '💡 Sequence Rule: Start with the first number (20) and step by -3 down to 8.',
    mathExplanation: 'Terms are 20, 17, 14, 11, 8. Rule is start at 20, subtract 3.',
  },
  {
    id: 'r2-002',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'easy',
    title: 'Ramp Rise (Start: 4, Step: +4)',
    instruction: 'Configure the builder for an ascending ramp: Start = 4, Step = +4.',
    sequence: [4, 8, 12, 16, 20],
    startValue: 4,
    commonDifference: 4,
    expectedStep: 4,
    expectedNextTerm: 20,
    ruleDescription: 'Start at 4, step +4',
    misconceptionTip: '💡 Ascending Step: Set start to 4 and step to +4.',
    mathExplanation: 'Start 4, add 4 four times = 20.',
  },
  {
    id: 'r2-003',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'medium',
    title: 'Overpass Descent (Start: 50, Step: -5)',
    instruction: 'Build the bridge drop: Start = 50, Step = -5.',
    sequence: [50, 45, 40, 35, 30],
    startValue: 50,
    commonDifference: -5,
    expectedStep: -5,
    expectedNextTerm: 30,
    ruleDescription: 'Start at 50, step -5',
    misconceptionTip: '💡 Step Direction: Verify the track decreases by 5 from 50.',
    mathExplanation: '50, 45, 40, 35, 30. Start = 50, Step = -5.',
  },
  {
    id: 'r2-004',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'easy',
    title: 'Sprint Lane (Start: 10, Step: +5)',
    instruction: 'Build the acceleration straight: Start = 10, Step = +5.',
    sequence: [10, 15, 20, 25, 30],
    startValue: 10,
    commonDifference: 5,
    expectedStep: 5,
    expectedNextTerm: 30,
    ruleDescription: 'Start at 10, step +5',
    misconceptionTip: '💡 Adding Fives: 10, 15, 20, 25, 30. Step is +5.',
    mathExplanation: 'Start 10, add 5 each step to reach 30.',
  },
  {
    id: 'r2-005',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'medium',
    title: 'Corner Radius Arc (Start: 12, Step: +6)',
    instruction: 'Configure the corner radius progression: Start = 12, Step = +6.',
    sequence: [12, 18, 24, 30, 36],
    startValue: 12,
    commonDifference: 6,
    expectedStep: 6,
    expectedNextTerm: 36,
    ruleDescription: 'Start at 12, step +6',
    misconceptionTip: '💡 Add 6 to previous term: 12 + 6 = 18, 18 + 6 = 24...',
    mathExplanation: '12 + 4 × 6 = 36. Step = +6.',
  },
  {
    id: 'r2-006',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'medium',
    title: 'Pit Entry Slowdown (Start: 30, Step: -3)',
    instruction: 'Deploy the pit lane entry line: Start = 30, Step = -3.',
    sequence: [30, 27, 24, 21, 18],
    startValue: 30,
    commonDifference: -3,
    expectedStep: -3,
    expectedNextTerm: 18,
    ruleDescription: 'Start at 30, step -3',
    misconceptionTip: '💡 Subtract 3: 21 - 3 = 18.',
    mathExplanation: 'Start 30, subtract 3 each time to reach 18.',
  },
  {
    id: 'r2-007',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'medium',
    title: 'High-Downforce Path (Start: 2, Step: +7)',
    instruction: 'Build the test track: Start = 2, Step = +7.',
    sequence: [2, 9, 16, 23, 30],
    startValue: 2,
    commonDifference: 7,
    expectedStep: 7,
    expectedNextTerm: 30,
    ruleDescription: 'Start at 2, step +7',
    misconceptionTip: '💡 Step of 7: 23 + 7 = 30.',
    mathExplanation: 'Start 2, add 7 each step to reach 30.',
  },
  {
    id: 'r2-008',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'hard',
    title: 'Braking Straight (Start: 60, Step: -8)',
    instruction: 'Deploy high-friction braking segments: Start = 60, Step = -8.',
    sequence: [60, 52, 44, 36, 28],
    startValue: 60,
    commonDifference: -8,
    expectedStep: -8,
    expectedNextTerm: 28,
    ruleDescription: 'Start at 60, step -8',
    misconceptionTip: '💡 Subtraction Check: 60 - 8 = 52, 52 - 8 = 44...',
    mathExplanation: '60 - 4 × 8 = 28. Step = -8.',
  },

  // ============================================================
  // ── ROUND 3: FUNCTION MACHINE (Calculate Output Capsule) ──
  // ============================================================
  {
    id: 'r3-001',
    round: 3,
    skill: 'function_machine',
    difficulty: 'easy',
    title: 'Turbo Multiplier Machine (Input 4 in [×2 + 3])',
    instruction: 'Input capsule [4] enters the machine [×2 + 3]. Compute the output.',
    functionInput: 4,
    twoStep: true,
    operator1: '×',
    operand1: 2,
    operator2: '+',
    operand2: 3,
    expectedOutput: 11,
    ruleDescription: 'Input × 2 + 3',
    misconceptionTip: '💡 Order of Operations: Multiply first (4 × 2 = 8), then add 3 (8 + 3 = 11).',
    mathExplanation: 'f(4) = (4 × 2) + 3 = 8 + 3 = 11.',
  },
  {
    id: 'r3-002',
    round: 3,
    skill: 'function_machine',
    difficulty: 'easy',
    title: 'Gear Booster (Input 5 in [×3 + 2])',
    instruction: 'Input capsule [5] enters [×3 + 2]. Calculate output capsule value.',
    functionInput: 5,
    twoStep: true,
    operator1: '×',
    operand1: 3,
    operator2: '+',
    operand2: 2,
    expectedOutput: 17,
    ruleDescription: 'Input × 3 + 2',
    misconceptionTip: '💡 PEMDAS: First 5 × 3 = 15. Then 15 + 2 = 17.',
    mathExplanation: 'f(5) = (5 × 3) + 2 = 15 + 2 = 17.',
  },
  {
    id: 'r3-003',
    round: 3,
    skill: 'function_machine',
    difficulty: 'easy',
    title: 'Single-Stage Multiplier (Input 6 in [×4])',
    instruction: 'Input capsule [6] enters [×4]. Predict the output.',
    functionInput: 6,
    twoStep: false,
    operator1: '×',
    operand1: 4,
    expectedOutput: 24,
    ruleDescription: 'Input × 4',
    misconceptionTip: '💡 Multiplication: Multiply 6 by 4.',
    mathExplanation: 'f(6) = 6 × 4 = 24.',
  },
  {
    id: 'r3-004',
    round: 3,
    skill: 'function_machine',
    difficulty: 'medium',
    title: 'Subtractive Limiter (Input 6 in [×4 - 2])',
    instruction: 'Input capsule [6] enters [×4 - 2]. Compute the output.',
    functionInput: 6,
    twoStep: true,
    operator1: '×',
    operand1: 4,
    operator2: '-',
    operand2: 2,
    expectedOutput: 22,
    ruleDescription: 'Input × 4 - 2',
    misconceptionTip: '💡 Multiply then Subtract: 6 × 4 = 24, then 24 - 2 = 22.',
    mathExplanation: 'f(6) = (6 × 4) - 2 = 24 - 2 = 22.',
  },
  {
    id: 'r3-005',
    round: 3,
    skill: 'function_machine',
    difficulty: 'easy',
    title: 'Half-Power Reducer (Input 10 in [÷2 + 3])',
    instruction: 'Input capsule [10] enters [÷2 + 3]. Determine output capsule.',
    functionInput: 10,
    twoStep: true,
    operator1: '÷',
    operand1: 2,
    operator2: '+',
    operand2: 3,
    expectedOutput: 8,
    ruleDescription: 'Input ÷ 2 + 3',
    misconceptionTip: '💡 Division first: 10 ÷ 2 = 5, then 5 + 3 = 8.',
    mathExplanation: 'f(10) = (10 ÷ 2) + 3 = 5 + 3 = 8.',
  },
  {
    id: 'r3-006',
    round: 3,
    skill: 'function_machine',
    difficulty: 'medium',
    title: 'Five-Fold Reactor (Input 7 in [×5 + 2])',
    instruction: 'Input capsule [7] enters [×5 + 2]. Calculate output.',
    functionInput: 7,
    twoStep: true,
    operator1: '×',
    operand1: 5,
    operator2: '+',
    operand2: 2,
    expectedOutput: 37,
    ruleDescription: 'Input × 5 + 2',
    misconceptionTip: '💡 Step 1: 7 × 5 = 35. Step 2: 35 + 2 = 37.',
    mathExplanation: 'f(7) = (7 × 5) + 2 = 35 + 2 = 37.',
  },
  {
    id: 'r3-007',
    round: 3,
    skill: 'function_machine',
    difficulty: 'easy',
    title: 'Offset Multiplier (Input 8 in [÷2 + 5])',
    instruction: 'Input capsule [8] enters [÷2 + 5]. Compute output.',
    functionInput: 8,
    twoStep: true,
    operator1: '÷',
    operand1: 2,
    operator2: '+',
    operand2: 5,
    expectedOutput: 9,
    ruleDescription: 'Input ÷ 2 + 5',
    misconceptionTip: '💡 8 ÷ 2 = 4. 4 + 5 = 9.',
    mathExplanation: 'f(8) = (8 ÷ 2) + 5 = 4 + 5 = 9.',
  },
  {
    id: 'r3-008',
    round: 3,
    skill: 'function_machine',
    difficulty: 'medium',
    title: 'Triple Chamber (Input 3 in [×6 + 4])',
    instruction: 'Input capsule [3] enters [×6 + 4]. Calculate output.',
    functionInput: 3,
    twoStep: true,
    operator1: '×',
    operand1: 6,
    operator2: '+',
    operand2: 4,
    expectedOutput: 22,
    ruleDescription: 'Input × 6 + 4',
    misconceptionTip: '💡 3 × 6 = 18. 18 + 4 = 22.',
    mathExplanation: 'f(3) = (3 × 6) + 4 = 18 + 4 = 22.',
  },

  // ============================================================
  // ── ROUND 4: REPAIR THE FUNCTION (Discover Operator & Value) ──
  // ============================================================
  {
    id: 'r4-001',
    round: 4,
    skill: 'function_repair',
    difficulty: 'easy',
    title: 'Repair Calibration 4 → [ ? ] → 12',
    instruction: 'Configure the missing single-step operator wheel for 4 → 12.',
    functionInput: 4,
    functionOutput: 12,
    expectedOperator: '×',
    expectedOperand: 3,
    ruleDescription: 'Operator: ×, Value: 3',
    misconceptionTip: '💡 Inverse Operation: 12 ÷ 4 = 3 (Rule: ×3).',
    mathExplanation: '12 ÷ 4 = 3, so the missing machine rule is ×3.',
  },
  {
    id: 'r4-002',
    round: 4,
    skill: 'function_repair',
    difficulty: 'easy',
    title: 'Repair Calibration 5 → [ ? ] → 25',
    instruction: 'Set the operator wheel to transform input 5 into output 25.',
    functionInput: 5,
    functionOutput: 25,
    expectedOperator: '×',
    expectedOperand: 5,
    ruleDescription: 'Operator: ×, Value: 5',
    misconceptionTip: '💡 Fact Family: 5 × 5 = 25. Select [ × ] and [ 5 ].',
    mathExplanation: '25 ÷ 5 = 5. Rule is ×5.',
  },
  {
    id: 'r4-003',
    round: 4,
    skill: 'function_repair',
    difficulty: 'easy',
    title: 'Pressure Reducer 18 → [ ? ] → 6',
    instruction: 'Configure the pressure reduction rule from 18 to 6.',
    functionInput: 18,
    functionOutput: 6,
    expectedOperator: '÷',
    expectedOperand: 3,
    ruleDescription: 'Operator: ÷, Value: 3',
    misconceptionTip: '💡 Division Rule: 18 ÷ 6 = 3 (Rule: ÷3).',
    mathExplanation: '18 ÷ 3 = 6. Rule is ÷3.',
  },
  {
    id: 'r4-004',
    round: 4,
    skill: 'function_repair',
    difficulty: 'easy',
    title: 'Adder Calibration 14 → [ ? ] → 21',
    instruction: 'Discover the additive boost rule for 14 → 21.',
    functionInput: 14,
    functionOutput: 21,
    expectedOperator: '+',
    expectedOperand: 7,
    ruleDescription: 'Operator: +, Value: 7',
    misconceptionTip: '💡 Difference: 21 - 14 = 7. Select [ + ] and [ 7 ].',
    mathExplanation: '21 - 14 = 7. Rule is +7.',
  },
  {
    id: 'r4-005',
    round: 4,
    skill: 'function_repair',
    difficulty: 'easy',
    title: 'Coolant Depletion 30 → [ ? ] → 22',
    instruction: 'Set the subtraction operator for 30 → 22.',
    functionInput: 30,
    functionOutput: 22,
    expectedOperator: '-',
    expectedOperand: 8,
    ruleDescription: 'Operator: -, Value: 8',
    misconceptionTip: '💡 Subtraction: 30 - 22 = 8. Rule is -8.',
    mathExplanation: '30 - 8 = 22. Rule is -8.',
  },
  {
    id: 'r4-006',
    round: 4,
    skill: 'function_repair',
    difficulty: 'medium',
    title: 'Multi-Torque Discovery 6 → [ ? ] → 36',
    instruction: 'Identify the multiplier rule for 6 → 36.',
    functionInput: 6,
    functionOutput: 36,
    expectedOperator: '×',
    expectedOperand: 6,
    ruleDescription: 'Operator: ×, Value: 6',
    misconceptionTip: '💡 36 ÷ 6 = 6. Select [ × ] and [ 6 ].',
    mathExplanation: '6 × 6 = 36. Rule is ×6.',
  },
  {
    id: 'r4-007',
    round: 4,
    skill: 'function_repair',
    difficulty: 'medium',
    title: 'Divider Repair 40 → [ ? ] → 8',
    instruction: 'Configure the reduction gear from 40 to 8.',
    functionInput: 40,
    functionOutput: 8,
    expectedOperator: '÷',
    expectedOperand: 5,
    ruleDescription: 'Operator: ÷, Value: 5',
    misconceptionTip: '💡 40 ÷ 8 = 5. Rule is ÷5.',
    mathExplanation: '40 ÷ 5 = 8. Rule is ÷5.',
  },
  {
    id: 'r4-008',
    round: 4,
    skill: 'function_repair',
    difficulty: 'easy',
    title: 'Four-Multiplier 8 → [ ? ] → 32',
    instruction: 'Configure the multiplier from 8 to 32.',
    functionInput: 8,
    functionOutput: 32,
    expectedOperator: '×',
    expectedOperand: 4,
    ruleDescription: 'Operator: ×, Value: 4',
    misconceptionTip: '💡 32 ÷ 8 = 4. Rule is ×4.',
    mathExplanation: '8 × 4 = 32.',
  },

  // ============================================================
  // ── ROUND 5: GRAND PRIX HYBRID (Sequence Step + Function) ──
  // ============================================================
  {
    id: 'r5-001',
    round: 5,
    skill: 'grand_prix_hybrid',
    difficulty: 'easy',
    title: 'Championship Circuit Lock (Sequence + Function)',
    instruction: 'Step 1: Step for 3, 7, 11, 15, ? (+4). Step 2: Run Input 6 through [×2 + 5].',
    sequence: [3, 7, 11, 15, 19],
    commonDifference: 4,
    expectedStep: 4,
    functionInput: 6,
    twoStep: true,
    operator1: '×',
    operand1: 2,
    operator2: '+',
    operand2: 5,
    expectedOutput: 17,
    ruleDescription: 'Step: +4 | Function Output: 17',
    misconceptionTip: '💡 Dual Challenge: 1) Step is 7 - 3 = 4. 2) Function is (6 × 2) + 5 = 17.',
    mathExplanation: 'Sequence step is +4. Function output is (6 × 2) + 5 = 17. Both locks release the starting grid!',
  },
  {
    id: 'r5-002',
    round: 5,
    skill: 'grand_prix_hybrid',
    difficulty: 'easy',
    title: 'Pole Position Sequence & Turbo Gate',
    instruction: 'Step 1: Step for 5, 10, 15, 20, ? (+5). Step 2: Run Input 8 through [×3 - 4].',
    sequence: [5, 10, 15, 20, 25],
    commonDifference: 5,
    expectedStep: 5,
    functionInput: 8,
    twoStep: true,
    operator1: '×',
    operand1: 3,
    operator2: '-',
    operand2: 4,
    expectedOutput: 20,
    ruleDescription: 'Step: +5 | Function Output: 20',
    misconceptionTip: '💡 Step is 10 - 5 = 5. Function: (8 × 3) - 4 = 24 - 4 = 20.',
    mathExplanation: 'Step = +5. Function = 20.',
  },
  {
    id: 'r5-003',
    round: 5,
    skill: 'grand_prix_hybrid',
    difficulty: 'medium',
    title: 'Final Overdrive Circuit',
    instruction: 'Step 1: Step for 30, 27, 24, 21, ? (-3). Step 2: Run Input 10 through [×4 + 3].',
    sequence: [30, 27, 24, 21, 18],
    commonDifference: -3,
    expectedStep: -3,
    functionInput: 10,
    twoStep: true,
    operator1: '×',
    operand1: 4,
    operator2: '+',
    operand2: 3,
    expectedOutput: 43,
    ruleDescription: 'Step: -3 | Function Output: 43',
    misconceptionTip: '💡 Step is 27 - 30 = -3. Function: (10 × 4) + 3 = 40 + 3 = 43.',
    mathExplanation: 'Sequence step = -3. Function output = 43.',
  },
  {
    id: 'r5-004',
    round: 5,
    skill: 'grand_prix_hybrid',
    difficulty: 'easy',
    title: 'Grid Launch Hybrid Dual',
    instruction: 'Step 1: Step for 2, 8, 14, 20, ? (+6). Step 2: Run Input 12 through [÷2 + 7].',
    sequence: [2, 8, 14, 20, 26],
    commonDifference: 6,
    expectedStep: 6,
    functionInput: 12,
    twoStep: true,
    operator1: '÷',
    operand1: 2,
    operator2: '+',
    operand2: 7,
    expectedOutput: 13,
    ruleDescription: 'Step: +6 | Function Output: 13',
    misconceptionTip: '💡 Step is 8 - 2 = 6. Function: (12 ÷ 2) + 7 = 6 + 7 = 13.',
    mathExplanation: 'Sequence step = +6. Function output = 13.',
  },
  {
    id: 'r5-005',
    round: 5,
    skill: 'grand_prix_hybrid',
    difficulty: 'medium',
    title: 'Final Trophy Qualifier',
    instruction: 'Step 1: Step for 50, 42, 34, 26, ? (-8). Step 2: Run Input 5 through [×5 + 1].',
    sequence: [50, 42, 34, 26, 18],
    commonDifference: -8,
    expectedStep: -8,
    functionInput: 5,
    twoStep: true,
    operator1: '×',
    operand1: 5,
    operator2: '+',
    operand2: 1,
    expectedOutput: 26,
    ruleDescription: 'Step: -8 | Function Output: 26',
    misconceptionTip: '💡 42 - 50 = -8. Function: (5 × 5) + 1 = 25 + 1 = 26.',
    mathExplanation: 'Sequence step = -8. Function output = 26.',
  },
];

// Helper to get challenges by round with fallback
export function getChallengesForRound(round: RoundNumber): SequenceChallenge[] {
  const filtered = PATTERN_CHALLENGE_BANK.filter((c) => c.round === round);
  if (filtered.length === 0) return PATTERN_CHALLENGE_BANK;
  return filtered;
}

// Generate an on-the-fly programmatic challenge for unlimited gameplay variety
export function generateDynamicChallenge(round: RoundNumber, seed: number): SequenceChallenge {
  const baseSteps = [2, 3, 4, 5, 6, 7, 8, 10, -2, -3, -4, -5, -8];
  const step = baseSteps[Math.abs(seed) % baseSteps.length];
  const start = step > 0 ? (Math.abs(seed) % 8) + 2 : 40 + (Math.abs(seed) % 20);
  const seq = [start, start + step, start + step * 2, start + step * 3, start + step * 4];

  if (round === 1) {
    return {
      id: `dyn-r1-${seed}`,
      round: 1,
      skill: 'sequence_step',
      difficulty: 'easy',
      title: `Grand Prix Sector Pattern (${step > 0 ? `+${step}` : step})`,
      instruction: 'Determine the constant step rule to extend the track segment.',
      sequence: seq,
      missingIndex: 4,
      commonDifference: step,
      expectedStep: step,
      expectedNextTerm: seq[4],
      ruleDescription: `${step > 0 ? `Add ${step}` : `Subtract ${Math.abs(step)}`} each step`,
      misconceptionTip: `💡 Difference: Subtract adjacent terms (${seq[1]} - ${seq[0]} = ${step}).`,
      mathExplanation: `Common difference is ${step > 0 ? `+${step}` : step}. Term 5 is ${seq[4]}.`,
    };
  }

  if (round === 2) {
    return {
      id: `dyn-r2-${seed}`,
      round: 2,
      skill: 'sequence_builder',
      difficulty: 'easy',
      title: `Track Builder Path (Start: ${start}, Step: ${step > 0 ? `+${step}` : step})`,
      instruction: `Configure the Track Builder with Start = ${start}, Step = ${step > 0 ? `+${step}` : step}.`,
      sequence: seq,
      startValue: start,
      commonDifference: step,
      expectedStep: step,
      expectedNextTerm: seq[4],
      ruleDescription: `Start ${start}, step ${step}`,
      misconceptionTip: `💡 Start with ${start} and apply step ${step > 0 ? `+${step}` : step}.`,
      mathExplanation: `Sequence is ${seq.join(', ')}.`,
    };
  }

  if (round === 3) {
    const input = (Math.abs(seed) % 6) + 3;
    const mult = (Math.abs(seed) % 3) + 2;
    const add = (Math.abs(seed) % 4) + 1;
    const output = input * mult + add;
    return {
      id: `dyn-r3-${seed}`,
      round: 3,
      skill: 'function_machine',
      difficulty: 'easy',
      title: `Turbo Machine [×${mult} + ${add}]`,
      instruction: `Input capsule [${input}] enters [×${mult} + ${add}]. Compute output.`,
      functionInput: input,
      twoStep: true,
      operator1: '×',
      operand1: mult,
      operator2: '+',
      operand2: add,
      expectedOutput: output,
      ruleDescription: `Input × ${mult} + ${add}`,
      misconceptionTip: `💡 Multiply first (${input} × ${mult} = ${input * mult}), then add ${add}.`,
      mathExplanation: `f(${input}) = (${input} × ${mult}) + ${add} = ${output}.`,
    };
  }

  if (round === 4) {
    const input = (Math.abs(seed) % 5) + 3;
    const mult = (Math.abs(seed) % 4) + 2;
    const output = input * mult;
    return {
      id: `dyn-r4-${seed}`,
      round: 4,
      skill: 'function_repair',
      difficulty: 'easy',
      title: `Machine Calibration ${input} → [ ? ] → ${output}`,
      instruction: `Configure the operator wheel to transform ${input} into ${output}.`,
      functionInput: input,
      functionOutput: output,
      expectedOperator: '×',
      expectedOperand: mult,
      ruleDescription: `Operator: ×, Value: ${mult}`,
      misconceptionTip: `💡 Reverse operation: ${output} ÷ ${input} = ${mult}. Rule is ×${mult}.`,
      mathExplanation: `${input} × ${mult} = ${output}. Rule is ×${mult}.`,
    };
  }

  // Round 5: Hybrid
  const input5 = (Math.abs(seed) % 4) + 4;
  const mult5 = 2 + (Math.abs(seed) % 2);
  const add5 = 1 + (Math.abs(seed) % 4);
  const out5 = input5 * mult5 + add5;
  return {
    id: `dyn-r5-${seed}`,
    round: 5,
    skill: 'grand_prix_hybrid',
    difficulty: 'easy',
    title: `Championship Circuit (${step > 0 ? `+${step}` : step} & [×${mult5} + ${add5}])`,
    instruction: `Step 1: Step for ${seq.slice(0, 4).join(', ')}. Step 2: Input ${input5} in [×${mult5} + ${add5}].`,
    sequence: seq,
    commonDifference: step,
    expectedStep: step,
    functionInput: input5,
    twoStep: true,
    operator1: '×',
    operand1: mult5,
    operator2: '+',
    operand2: add5,
    expectedOutput: out5,
    ruleDescription: `Step: ${step > 0 ? `+${step}` : step} | Output: ${out5}`,
    misconceptionTip: `💡 Step: ${seq[1]} - ${seq[0]} = ${step}. Function: (${input5} × ${mult5}) + ${add5} = ${out5}.`,
    mathExplanation: `Step is ${step}, and function output is ${out5}.`,
  };
}
