// ============================================================
// PATTERN RACERS — 100+ Question Bank for Grade 6
// Curriculum: Sequences, Arithmetic Progressions & Function Machines
// Rich mathematical metadata: Common Differences, In/Out rules, Misconceptions
// ============================================================

import { SequenceChallenge, RoundNumber } from '../types';

export const PATTERN_CHALLENGE_BANK: SequenceChallenge[] = [
  // ============================================================
  // ── ROUND 1: PATTERN TRACK (Find Common Difference / Step) ──
  // ============================================================
  {
    id: 'r1-001',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'easy',
    title: 'Turbo Ascent Sequence',
    instruction: 'Determine the constant step rule to extend the track segment.',
    sequence: [2, 5, 8, 11, 14],
    missingIndex: 4,
    commonDifference: 3,
    expectedStep: 3,
    expectedNextTerm: 14,
    ruleDescription: 'Add 3 each step (+3)',
    misconceptionTip: '💡 Step Difference: Check the gap between adjacent numbers (5 - 2 = 3).',
    mathExplanation: 'The common difference is d = 8 - 5 = +3. Starting at 2, adding 3 repeatedly gives 2, 5, 8, 11, 14.',
  },
  {
    id: 'r1-002',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'easy',
    title: 'Speedway Leap +4',
    instruction: 'Find the step difference driving this acceleration pattern.',
    sequence: [3, 7, 11, 15, 19],
    missingIndex: 4,
    commonDifference: 4,
    expectedStep: 4,
    expectedNextTerm: 19,
    ruleDescription: 'Add 4 each step (+4)',
    misconceptionTip: '💡 Constant Step: Subtract any term from the next term (11 - 7 = 4).',
    mathExplanation: 'd = 7 - 3 = +4. 15 + 4 = 19.',
  },
  {
    id: 'r1-003',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'easy',
    title: 'Pitlane Descent -2',
    instruction: 'The vehicle is braking. Identify the negative step difference.',
    sequence: [18, 16, 14, 12, 10],
    missingIndex: 4,
    commonDifference: -2,
    expectedStep: -2,
    expectedNextTerm: 10,
    ruleDescription: 'Subtract 2 each step (-2)',
    misconceptionTip: '💡 Decreasing Sequence: When numbers go down, the step is negative (16 - 18 = -2).',
    mathExplanation: 'd = 14 - 16 = -2. 12 - 2 = 10.',
  },
  {
    id: 'r1-004',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'easy',
    title: 'High-Gear Fives',
    instruction: 'Calibrate the track hydraulic lift using the common difference.',
    sequence: [5, 10, 15, 20, 25],
    missingIndex: 4,
    commonDifference: 5,
    expectedStep: 5,
    expectedNextTerm: 25,
    ruleDescription: 'Add 5 each step (+5)',
    misconceptionTip: '💡 Multiples of 5: Notice the pattern increases by exactly 5 units every interval.',
    mathExplanation: 'd = 10 - 5 = +5. 20 + 5 = 25.',
  },
  {
    id: 'r1-005',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'medium',
    title: 'Chicane Seven Sprint',
    instruction: 'Find the common difference to connect the chicane track.',
    sequence: [4, 11, 18, 25, 32],
    missingIndex: 4,
    commonDifference: 7,
    expectedStep: 7,
    expectedNextTerm: 32,
    ruleDescription: 'Add 7 each step (+7)',
    misconceptionTip: '💡 Check Two Pairs: 11 - 4 = 7, and 18 - 11 = 7. The step is +7.',
    mathExplanation: 'd = +7. 25 + 7 = 32.',
  },
  {
    id: 'r1-006',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'medium',
    title: 'Deceleration Ramp -5',
    instruction: 'Calculate the braking sequence step.',
    sequence: [45, 40, 35, 30, 25],
    missingIndex: 4,
    commonDifference: -5,
    expectedStep: -5,
    expectedNextTerm: 25,
    ruleDescription: 'Subtract 5 each step (-5)',
    misconceptionTip: '💡 Sign Trap: Decreasing by 5 means the step value is -5.',
    mathExplanation: 'd = 40 - 45 = -5. 30 + (-5) = 25.',
  },
  {
    id: 'r1-007',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'medium',
    title: 'Six-Cylinder Rhythm',
    instruction: 'Identify the common difference in engine telemetry.',
    sequence: [9, 15, 21, 27, 33],
    missingIndex: 4,
    commonDifference: 6,
    expectedStep: 6,
    expectedNextTerm: 33,
    ruleDescription: 'Add 6 each step (+6)',
    misconceptionTip: '💡 Difference: 15 - 9 = 6. 27 + 6 = 33.',
    mathExplanation: 'd = +6. Adding 6 to 27 gives 33.',
  },
  {
    id: 'r1-008',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'hard',
    title: 'Nitro Step +8',
    instruction: 'Find the aggressive acceleration sequence rule.',
    sequence: [1, 9, 17, 25, 33],
    missingIndex: 4,
    commonDifference: 8,
    expectedStep: 8,
    expectedNextTerm: 33,
    ruleDescription: 'Add 8 each step (+8)',
    misconceptionTip: '💡 Step Size: 9 - 1 = 8. Check 17 - 9 = 8.',
    mathExplanation: 'd = +8. 25 + 8 = 33.',
  },
  {
    id: 'r1-009',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'hard',
    title: 'Braking Run -4',
    instruction: 'Determine the brake deceleration factor.',
    sequence: [32, 28, 24, 20, 16],
    missingIndex: 4,
    commonDifference: -4,
    expectedStep: -4,
    expectedNextTerm: 16,
    ruleDescription: 'Subtract 4 each step (-4)',
    misconceptionTip: '💡 Negative Step: 28 - 32 = -4.',
    mathExplanation: 'd = -4. 20 - 4 = 16.',
  },
  {
    id: 'r1-010',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'hard',
    title: 'Precision Leap +9',
    instruction: 'Discover the large-gap linear pattern.',
    sequence: [7, 16, 25, 34, 43],
    missingIndex: 4,
    commonDifference: 9,
    expectedStep: 9,
    expectedNextTerm: 43,
    ruleDescription: 'Add 9 each step (+9)',
    misconceptionTip: '💡 Check the Units Digit: Notice the pattern increases by 9 every step.',
    mathExplanation: 'd = 16 - 7 = 9. 34 + 9 = 43.',
  },
  {
    id: 'r1-011',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'easy',
    title: 'Straightaway Tens',
    instruction: 'Determine the straightaway distance progression.',
    sequence: [10, 20, 30, 40, 50],
    missingIndex: 4,
    commonDifference: 10,
    expectedStep: 10,
    expectedNextTerm: 50,
    ruleDescription: 'Add 10 each step (+10)',
    misconceptionTip: '💡 Tens Progression: Add 10 to 40.',
    mathExplanation: 'd = +10. 40 + 10 = 50.',
  },
  {
    id: 'r1-012',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'medium',
    title: 'Downhill Descent -3',
    instruction: 'Determine the elevation drop rate.',
    sequence: [27, 24, 21, 18, 15],
    missingIndex: 4,
    commonDifference: -3,
    expectedStep: -3,
    expectedNextTerm: 15,
    ruleDescription: 'Subtract 3 each step (-3)',
    misconceptionTip: '💡 Downward Step: 24 - 27 = -3.',
    mathExplanation: 'd = -3. 18 - 3 = 15.',
  },
  {
    id: 'r1-013',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'hard',
    title: 'Grand Prix Prime Offset +11',
    instruction: 'Calculate the step difference for the high-speed section.',
    sequence: [6, 17, 28, 39, 50],
    missingIndex: 4,
    commonDifference: 11,
    expectedStep: 11,
    expectedNextTerm: 50,
    ruleDescription: 'Add 11 each step (+11)',
    misconceptionTip: '💡 Two-Digit Step: 17 - 6 = 11. 39 + 11 = 50.',
    mathExplanation: 'd = +11. 39 + 11 = 50.',
  },
  {
    id: 'r1-014',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'medium',
    title: 'Countdown Drop -6',
    instruction: 'Identify the countdown interval.',
    sequence: [50, 44, 38, 32, 26],
    missingIndex: 4,
    commonDifference: -6,
    expectedStep: -6,
    expectedNextTerm: 26,
    ruleDescription: 'Subtract 6 each step (-6)',
    misconceptionTip: '💡 Drop of 6: 44 - 50 = -6.',
    mathExplanation: 'd = -6. 32 - 6 = 26.',
  },
  {
    id: 'r1-015',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'hard',
    title: 'Dynamic Boost +12',
    instruction: 'Identify the boost progression step.',
    sequence: [8, 20, 32, 44, 56],
    missingIndex: 4,
    commonDifference: 12,
    expectedStep: 12,
    expectedNextTerm: 56,
    ruleDescription: 'Add 12 each step (+12)',
    misconceptionTip: '💡 Dozen Step: 20 - 8 = 12.',
    mathExplanation: 'd = +12. 44 + 12 = 56.',
  },
  {
    id: 'r1-016',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'easy',
    title: 'Warm-up Laps +2',
    instruction: 'Calculate the basic warm-up lap pace.',
    sequence: [6, 8, 10, 12, 14],
    missingIndex: 4,
    commonDifference: 2,
    expectedStep: 2,
    expectedNextTerm: 14,
    ruleDescription: 'Add 2 each step (+2)',
    misconceptionTip: '💡 Even Step: Gaps of 2.',
    mathExplanation: 'd = +2. 12 + 2 = 14.',
  },
  {
    id: 'r1-017',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'medium',
    title: 'Fuel Consumption -7',
    instruction: 'Determine the fuel depletion rate per lap.',
    sequence: [63, 56, 49, 42, 35],
    missingIndex: 4,
    commonDifference: -7,
    expectedStep: -7,
    expectedNextTerm: 35,
    ruleDescription: 'Subtract 7 each step (-7)',
    misconceptionTip: '💡 Multiples of 7 decreasing: 56 - 63 = -7.',
    mathExplanation: 'd = -7. 42 - 7 = 35.',
  },
  {
    id: 'r1-018',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'hard',
    title: 'Precision Sprints +15',
    instruction: 'Find the high acceleration interval.',
    sequence: [5, 20, 35, 50, 65],
    missingIndex: 4,
    commonDifference: 15,
    expectedStep: 15,
    expectedNextTerm: 65,
    ruleDescription: 'Add 15 each step (+15)',
    misconceptionTip: '💡 15-Unit Step: 20 - 5 = 15. 50 + 15 = 65.',
    mathExplanation: 'd = +15. 50 + 15 = 65.',
  },
  {
    id: 'r1-019',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'medium',
    title: 'Reverse Brake -8',
    instruction: 'Calculate the rapid slowdown sequence step.',
    sequence: [80, 72, 64, 56, 48],
    missingIndex: 4,
    commonDifference: -8,
    expectedStep: -8,
    expectedNextTerm: 48,
    ruleDescription: 'Subtract 8 each step (-8)',
    misconceptionTip: '💡 Eights down: 72 - 80 = -8.',
    mathExplanation: 'd = -8. 56 - 8 = 48.',
  },
  {
    id: 'r1-020',
    round: 1,
    skill: 'sequence_step',
    difficulty: 'hard',
    title: 'Telemetry Pulse +13',
    instruction: 'Determine the sensor pulse rate sequence.',
    sequence: [12, 25, 38, 51, 64],
    missingIndex: 4,
    commonDifference: 13,
    expectedStep: 13,
    expectedNextTerm: 64,
    ruleDescription: 'Add 13 each step (+13)',
    misconceptionTip: '💡 Step difference: 25 - 12 = 13. 51 + 13 = 64.',
    mathExplanation: 'd = +13. 51 + 13 = 64.',
  },

  // ============================================================
  // ── ROUND 2: SEQUENCE BUILDER (Start Value + Step + Direction) ──
  // ============================================================
  {
    id: 'r2-001',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'easy',
    title: 'Formula Path Constructor 20 → 8',
    instruction: 'Configure the Track Builder with Start = 20, Step = -3.',
    sequence: [20, 17, 14, 11, 8],
    startValue: 20,
    commonDifference: -3,
    expectedStep: -3,
    expectedNextTerm: 8,
    ruleDescription: 'Start at 20, step -3',
    misconceptionTip: '💡 Sequence Rule: Start with the first number (20) and step by -3 down to 8.',
    mathExplanation: 'Terms are 20, 17, 14, 11, 8. Rule is start 20, subtract 3.',
  },
  {
    id: 'r2-002',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'easy',
    title: 'Ramp Rise 4 → 20',
    instruction: 'Configure the builder for an ascending ramp: Start = 4, Step = +4.',
    sequence: [4, 8, 12, 16, 20],
    startValue: 4,
    commonDifference: 4,
    expectedStep: 4,
    expectedNextTerm: 20,
    ruleDescription: 'Start at 4, step +4',
    misconceptionTip: '💡 Ascending Step: Set direction to increasing and step to 4.',
    mathExplanation: 'Start 4, add 4 four times = 20.',
  },
  {
    id: 'r2-003',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'medium',
    title: 'Overpass Descent 50 → 30',
    instruction: 'Build the bridge drop: Start = 50, Step = -5.',
    sequence: [50, 45, 40, 35, 30],
    startValue: 50,
    commonDifference: -5,
    expectedStep: -5,
    expectedNextTerm: 30,
    ruleDescription: 'Start at 50, step -5',
    misconceptionTip: '💡 Step Direction: Verify whether the track goes down (-5) from 50.',
    mathExplanation: '50, 45, 40, 35, 30. Step = -5.',
  },
  {
    id: 'r2-004',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'medium',
    title: 'Curve Extension 15 → 39',
    instruction: 'Configure the corner radius progression: Start = 15, Step = +6.',
    sequence: [15, 21, 27, 33, 39],
    startValue: 15,
    commonDifference: 6,
    expectedStep: 6,
    expectedNextTerm: 39,
    ruleDescription: 'Start at 15, step +6',
    misconceptionTip: '💡 Add 6 to previous term: 15 + 6 = 21, 21 + 6 = 27...',
    mathExplanation: '15 + 4 × 6 = 39.',
  },
  {
    id: 'r2-005',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'hard',
    title: 'Championship Straight 100 → 68',
    instruction: 'Deploy high-friction braking segments: Start = 100, Step = -8.',
    sequence: [100, 92, 84, 76, 68],
    startValue: 100,
    commonDifference: -8,
    expectedStep: -8,
    expectedNextTerm: 68,
    ruleDescription: 'Start at 100, step -8',
    misconceptionTip: '💡 Subtraction Check: 100 - 8 = 92, 92 - 8 = 84...',
    mathExplanation: '100 - 4 × 8 = 68.',
  },
  {
    id: 'r2-006',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'easy',
    title: 'Sprint Lane 10 → 38',
    instruction: 'Build the acceleration straight: Start = 10, Step = +7.',
    sequence: [10, 17, 24, 31, 38],
    startValue: 10,
    commonDifference: 7,
    expectedStep: 7,
    expectedNextTerm: 38,
    ruleDescription: 'Start at 10, step +7',
    misconceptionTip: '💡 Adding Sevens: 31 + 7 = 38.',
    mathExplanation: 'Start 10, add 7 each step to reach 38.',
  },
  {
    id: 'r2-007',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'medium',
    title: 'Elevation Drop 72 → 36',
    instruction: 'Configure the downhill slope: Start = 72, Step = -9.',
    sequence: [72, 63, 54, 45, 36],
    startValue: 72,
    commonDifference: -9,
    expectedStep: -9,
    expectedNextTerm: 36,
    ruleDescription: 'Start at 72, step -9',
    misconceptionTip: '💡 Nines down: 72 - 9 = 63, 45 - 9 = 36.',
    mathExplanation: '72, 63, 54, 45, 36. Step = -9.',
  },
  {
    id: 'r2-008',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'hard',
    title: 'Speedway Expansion 11 → 59',
    instruction: 'Assemble the multi-lane straight: Start = 11, Step = +12.',
    sequence: [11, 23, 35, 47, 59],
    startValue: 11,
    commonDifference: 12,
    expectedStep: 12,
    expectedNextTerm: 59,
    ruleDescription: 'Start at 11, step +12',
    misconceptionTip: '💡 Adding 12: 47 + 12 = 59.',
    mathExplanation: 'Start 11, step +12 gives 11, 23, 35, 47, 59.',
  },
  {
    id: 'r2-009',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'easy',
    title: 'Pit Entry 30 → 18',
    instruction: 'Deploy the pit lane entry line: Start = 30, Step = -3.',
    sequence: [30, 27, 24, 21, 18],
    startValue: 30,
    commonDifference: -3,
    expectedStep: -3,
    expectedNextTerm: 18,
    ruleDescription: 'Start at 30, step -3',
    misconceptionTip: '💡 Subtract 3: 21 - 3 = 18.',
    mathExplanation: 'Start 30, subtract 3 each time.',
  },
  {
    id: 'r2-010',
    round: 2,
    skill: 'sequence_builder',
    difficulty: 'hard',
    title: 'High-Downforce Path 2 → 58',
    instruction: 'Build the aerodynamic test track: Start = 2, Step = +14.',
    sequence: [2, 16, 30, 44, 58],
    startValue: 2,
    commonDifference: 14,
    expectedStep: 14,
    expectedNextTerm: 58,
    ruleDescription: 'Start at 2, step +14',
    misconceptionTip: '💡 Step of 14: 44 + 14 = 58.',
    mathExplanation: 'Start 2, add 14 each step.',
  },

  // ============================================================
  // ── ROUND 3: FUNCTION MACHINE (Input Capsule → [Rule] → Output) ──
  // ============================================================
  {
    id: 'r3-001',
    round: 3,
    skill: 'function_machine',
    difficulty: 'easy',
    title: 'Turbo Multiplier Machine (×2 + 3)',
    instruction: 'Input capsule [5] enters the machine [×2 + 3]. Compute the output.',
    functionInput: 5,
    twoStep: true,
    operator1: '×',
    operand1: 2,
    operator2: '+',
    operand2: 3,
    expectedOutput: 13,
    ruleDescription: 'Input × 2 + 3',
    misconceptionTip: '💡 Order of Operations: Multiply first (5 × 2 = 10), then add 3 (10 + 3 = 13).',
    mathExplanation: 'f(5) = (5 × 2) + 3 = 10 + 3 = 13.',
  },
  {
    id: 'r3-002',
    round: 3,
    skill: 'function_machine',
    difficulty: 'easy',
    title: 'Gear Booster (×3 + 1)',
    instruction: 'Input capsule [4] enters [×3 + 1]. Calculate output capsule value.',
    functionInput: 4,
    twoStep: true,
    operator1: '×',
    operand1: 3,
    operator2: '+',
    operand2: 1,
    expectedOutput: 13,
    ruleDescription: 'Input × 3 + 1',
    misconceptionTip: '💡 PEMDAS: First 4 × 3 = 12. Then 12 + 1 = 13.',
    mathExplanation: 'f(4) = (4 × 3) + 1 = 12 + 1 = 13.',
  },
  {
    id: 'r3-003',
    round: 3,
    skill: 'function_machine',
    difficulty: 'easy',
    title: 'Single-Stage Multiplier (×4)',
    instruction: 'Input capsule [7] enters [×4]. Predict the output.',
    functionInput: 7,
    twoStep: false,
    operator1: '×',
    operand1: 4,
    expectedOutput: 28,
    ruleDescription: 'Input × 4',
    misconceptionTip: '💡 Multiplication: Multiply 7 by 4.',
    mathExplanation: 'f(7) = 7 × 4 = 28.',
  },
  {
    id: 'r3-004',
    round: 3,
    skill: 'function_machine',
    difficulty: 'medium',
    title: 'Subtractive Limiter (×4 - 5)',
    instruction: 'Input capsule [6] enters [×4 - 5]. Compute the output.',
    functionInput: 6,
    twoStep: true,
    operator1: '×',
    operand1: 4,
    operator2: '-',
    operand2: 5,
    expectedOutput: 19,
    ruleDescription: 'Input × 4 - 5',
    misconceptionTip: '💡 Multiply then Subtract: 6 × 4 = 24, then 24 - 5 = 19.',
    mathExplanation: 'f(6) = (6 × 4) - 5 = 24 - 5 = 19.',
  },
  {
    id: 'r3-005',
    round: 3,
    skill: 'function_machine',
    difficulty: 'medium',
    title: 'Half-Power Reducer (÷2 + 7)',
    instruction: 'Input capsule [12] enters [÷2 + 7]. Determine output capsule.',
    functionInput: 12,
    twoStep: true,
    operator1: '÷',
    operand1: 2,
    operator2: '+',
    operand2: 7,
    expectedOutput: 13,
    ruleDescription: 'Input ÷ 2 + 7',
    misconceptionTip: '💡 Division first: 12 ÷ 2 = 6, then 6 + 7 = 13.',
    mathExplanation: 'f(12) = (12 ÷ 2) + 7 = 6 + 7 = 13.',
  },
  {
    id: 'r3-006',
    round: 3,
    skill: 'function_machine',
    difficulty: 'hard',
    title: 'Five-Fold Reactor (×5 - 8)',
    instruction: 'Input capsule [8] enters [×5 - 8]. Calculate the final charge.',
    functionInput: 8,
    twoStep: true,
    operator1: '×',
    operand1: 5,
    operator2: '-',
    operand2: 8,
    expectedOutput: 32,
    ruleDescription: 'Input × 5 - 8',
    misconceptionTip: '💡 Step 1: 8 × 5 = 40. Step 2: 40 - 8 = 32.',
    mathExplanation: 'f(8) = (8 × 5) - 8 = 40 - 8 = 32.',
  },
  {
    id: 'r3-007',
    round: 3,
    skill: 'function_machine',
    difficulty: 'medium',
    title: 'Linear Scale (×3 - 4)',
    instruction: 'Input capsule [9] enters [×3 - 4]. Compute output.',
    functionInput: 9,
    twoStep: true,
    operator1: '×',
    operand1: 3,
    operator2: '-',
    operand2: 4,
    expectedOutput: 23,
    ruleDescription: 'Input × 3 - 4',
    misconceptionTip: '💡 9 × 3 = 27. 27 - 4 = 23.',
    mathExplanation: 'f(9) = (9 × 3) - 4 = 27 - 4 = 23.',
  },
  {
    id: 'r3-008',
    round: 3,
    skill: 'function_machine',
    difficulty: 'hard',
    title: 'Triple Chamber (×6 + 5)',
    instruction: 'Input capsule [7] enters [×6 + 5]. Calculate output.',
    functionInput: 7,
    twoStep: true,
    operator1: '×',
    operand1: 6,
    operator2: '+',
    operand2: 5,
    expectedOutput: 47,
    ruleDescription: 'Input × 6 + 5',
    misconceptionTip: '💡 7 × 6 = 42. 42 + 5 = 47.',
    mathExplanation: 'f(7) = (7 × 6) + 5 = 42 + 5 = 47.',
  },
  {
    id: 'r3-009',
    round: 3,
    skill: 'function_machine',
    difficulty: 'easy',
    title: 'Offset Multiplier (×2 + 9)',
    instruction: 'Input capsule [6] enters [×2 + 9]. Compute output.',
    functionInput: 6,
    twoStep: true,
    operator1: '×',
    operand1: 2,
    operator2: '+',
    operand2: 9,
    expectedOutput: 21,
    ruleDescription: 'Input × 2 + 9',
    misconceptionTip: '💡 6 × 2 = 12. 12 + 9 = 21.',
    mathExplanation: 'f(6) = (6 × 2) + 9 = 12 + 9 = 21.',
  },
  {
    id: 'r3-010',
    round: 3,
    skill: 'function_machine',
    difficulty: 'hard',
    title: 'Division Offset (÷3 + 15)',
    instruction: 'Input capsule [24] enters [÷3 + 15]. Calculate output.',
    functionInput: 24,
    twoStep: true,
    operator1: '÷',
    operand1: 3,
    operator2: '+',
    operand2: 15,
    expectedOutput: 23,
    ruleDescription: 'Input ÷ 3 + 15',
    misconceptionTip: '💡 Divide first: 24 ÷ 3 = 8. 8 + 15 = 23.',
    mathExplanation: 'f(24) = (24 ÷ 3) + 15 = 8 + 15 = 23.',
  },

  // ============================================================
  // ── ROUND 4: REPAIR THE FUNCTION (Discover Operator & Operand) ──
  // ============================================================
  {
    id: 'r4-001',
    round: 4,
    skill: 'function_repair',
    difficulty: 'easy',
    title: 'Repair Calibration 6 → [ ? ] → 18',
    instruction: 'Configure the missing single-step operator wheel for 6 → 18.',
    functionInput: 6,
    functionOutput: 18,
    expectedOperator: '×',
    expectedOperand: 3,
    ruleDescription: 'Operator: ×, Value: 3',
    misconceptionTip: '💡 Reverse Operation: To find what multiplies 6 to give 18, do 18 ÷ 6 = 3 (Rule: ×3).',
    mathExplanation: '18 ÷ 6 = 3, so the missing machine rule is ×3.',
  },
  {
    id: 'r4-002',
    round: 4,
    skill: 'function_repair',
    difficulty: 'easy',
    title: 'Repair Calibration 8 → [ ? ] → 32',
    instruction: 'Set the operator wheel to transform input 8 into output 32.',
    functionInput: 8,
    functionOutput: 32,
    expectedOperator: '×',
    expectedOperand: 4,
    ruleDescription: 'Operator: ×, Value: 4',
    misconceptionTip: '💡 Fact Family: 8 × 4 = 32. Select [ × ] and [ 4 ].',
    mathExplanation: '32 ÷ 8 = 4. Rule is ×4.',
  },
  {
    id: 'r4-003',
    round: 4,
    skill: 'function_repair',
    difficulty: 'easy',
    title: 'Pressure Reducer 45 → [ ? ] → 9',
    instruction: 'Configure the pressure reduction rule from 45 to 9.',
    functionInput: 45,
    functionOutput: 9,
    expectedOperator: '÷',
    expectedOperand: 5,
    ruleDescription: 'Operator: ÷, Value: 5',
    misconceptionTip: '💡 Division Rule: Since output is smaller than input, divide 45 ÷ 9 = 5 (Rule: ÷5).',
    mathExplanation: '45 ÷ 5 = 9. Rule is ÷5.',
  },
  {
    id: 'r4-004',
    round: 4,
    skill: 'function_repair',
    difficulty: 'medium',
    title: 'Adder Calibration 14 → [ ? ] → 29',
    instruction: 'Discover the additive boost rule for 14 → 29.',
    functionInput: 14,
    functionOutput: 29,
    expectedOperator: '+',
    expectedOperand: 15,
    ruleDescription: 'Operator: +, Value: 15',
    misconceptionTip: '💡 Difference: 29 - 14 = 15. Select [ + ] and [ 15 ].',
    mathExplanation: '29 - 14 = 15. Rule is +15.',
  },
  {
    id: 'r4-005',
    round: 4,
    skill: 'function_repair',
    difficulty: 'medium',
    title: 'Coolant Depletion 50 → [ ? ] → 37',
    instruction: 'Set the subtraction operator for 50 → 37.',
    functionInput: 50,
    functionOutput: 37,
    expectedOperator: '-',
    expectedOperand: 13,
    ruleDescription: 'Operator: -, Value: 13',
    misconceptionTip: '💡 Subtraction: 50 - 37 = 13. Rule is -13.',
    mathExplanation: '50 - 13 = 37. Rule is -13.',
  },
  {
    id: 'r4-006',
    round: 4,
    skill: 'function_repair',
    difficulty: 'hard',
    title: 'Multi-Torque Discovery 7 → [ ? ] → 49',
    instruction: 'Identify the square multiplier rule.',
    functionInput: 7,
    functionOutput: 49,
    expectedOperator: '×',
    expectedOperand: 7,
    ruleDescription: 'Operator: ×, Value: 7',
    misconceptionTip: '💡 49 ÷ 7 = 7. Select [ × ] and [ 7 ].',
    mathExplanation: '7 × 7 = 49. Rule is ×7.',
  },
  {
    id: 'r4-007',
    round: 4,
    skill: 'function_repair',
    difficulty: 'medium',
    title: 'Divider Repair 64 → [ ? ] → 8',
    instruction: 'Configure the high-reduction gear from 64 to 8.',
    functionInput: 64,
    functionOutput: 8,
    expectedOperator: '÷',
    expectedOperand: 8,
    ruleDescription: 'Operator: ÷, Value: 8',
    misconceptionTip: '💡 64 ÷ 8 = 8. Rule is ÷8.',
    mathExplanation: '64 ÷ 8 = 8. Rule is ÷8.',
  },
  {
    id: 'r4-008',
    round: 4,
    skill: 'function_repair',
    difficulty: 'hard',
    title: 'Nine-Multiplier 9 → [ ? ] → 81',
    instruction: 'Configure the max-output transformer from 9 to 81.',
    functionInput: 9,
    functionOutput: 81,
    expectedOperator: '×',
    expectedOperand: 9,
    ruleDescription: 'Operator: ×, Value: 9',
    misconceptionTip: '💡 81 ÷ 9 = 9. Rule is ×9.',
    mathExplanation: '9 × 9 = 81.',
  },
  {
    id: 'r4-009',
    round: 4,
    skill: 'function_repair',
    difficulty: 'easy',
    title: 'Six-Multiplication 5 → [ ? ] → 30',
    instruction: 'Configure the booster wheel for 5 → 30.',
    functionInput: 5,
    functionOutput: 30,
    expectedOperator: '×',
    expectedOperand: 6,
    ruleDescription: 'Operator: ×, Value: 6',
    misconceptionTip: '💡 30 ÷ 5 = 6. Select [ × ] and [ 6 ].',
    mathExplanation: '5 × 6 = 30.',
  },
  {
    id: 'r4-010',
    round: 4,
    skill: 'function_repair',
    difficulty: 'hard',
    title: 'Divider Unit 72 → [ ? ] → 12',
    instruction: 'Calibrate gear reduction for 72 → 12.',
    functionInput: 72,
    functionOutput: 12,
    expectedOperator: '÷',
    expectedOperand: 6,
    ruleDescription: 'Operator: ÷, Value: 6',
    misconceptionTip: '💡 72 ÷ 12 = 6. Rule is ÷6.',
    mathExplanation: '72 ÷ 6 = 12.',
  },

  // ============================================================
  // ── ROUND 5: GRAND PRIX (Hybrid Sequence + Multi-Step Function) ──
  // ============================================================
  {
    id: 'r5-001',
    round: 5,
    skill: 'grand_prix_hybrid',
    difficulty: 'medium',
    title: 'Championship Circuit Lock (Sequence + Function)',
    instruction: 'Step 1: Find step for 4, 7, 10, 13, ? (+3). Step 2: Run Input 8 through [×2 + 1].',
    sequence: [4, 7, 10, 13, 16],
    commonDifference: 3,
    expectedStep: 3,
    functionInput: 8,
    twoStep: true,
    operator1: '×',
    operand1: 2,
    operator2: '+',
    operand2: 1,
    expectedOutput: 17,
    ruleDescription: 'Step: +3 | Function Output: 17',
    misconceptionTip: '💡 Dual Challenge: 1) Sequence step is 7 - 4 = 3. 2) Function is (8 × 2) + 1 = 17.',
    mathExplanation: 'Sequence step is +3. Function output is (8 × 2) + 1 = 17. Both locks release the starting grid!',
  },
  {
    id: 'r5-002',
    round: 5,
    skill: 'grand_prix_hybrid',
    difficulty: 'medium',
    title: 'Pole Position Sequence & Turbo Gate',
    instruction: 'Step 1: Step for 6, 11, 16, 21, ? (+5). Step 2: Run Input 6 through [×3 - 2].',
    sequence: [6, 11, 16, 21, 26],
    commonDifference: 5,
    expectedStep: 5,
    functionInput: 6,
    twoStep: true,
    operator1: '×',
    operand1: 3,
    operator2: '-',
    operand2: 2,
    expectedOutput: 16,
    ruleDescription: 'Step: +5 | Function Output: 16',
    misconceptionTip: '💡 Step is 11 - 6 = 5. Function: (6 × 3) - 2 = 18 - 2 = 16.',
    mathExplanation: 'Step = 5. Function = 16.',
  },
  {
    id: 'r5-003',
    round: 5,
    skill: 'grand_prix_hybrid',
    difficulty: 'hard',
    title: 'Final Overdrive Circuit',
    instruction: 'Step 1: Step for 12, 19, 26, 33, ? (+7). Step 2: Run Input 7 through [×4 + 3].',
    sequence: [12, 19, 26, 33, 40],
    commonDifference: 7,
    expectedStep: 7,
    functionInput: 7,
    twoStep: true,
    operator1: '×',
    operand1: 4,
    operator2: '+',
    operand2: 3,
    expectedOutput: 31,
    ruleDescription: 'Step: +7 | Function Output: 31',
    misconceptionTip: '💡 19 - 12 = 7. Function: (7 × 4) + 3 = 28 + 3 = 31.',
    mathExplanation: 'Sequence step = +7. Function output = 31.',
  },
  {
    id: 'r5-004',
    round: 5,
    skill: 'grand_prix_hybrid',
    difficulty: 'hard',
    title: 'Grid Launch Hybrid Dual',
    instruction: 'Step 1: Step for 50, 42, 34, 26, ? (-8). Step 2: Run Input 9 through [×3 + 5].',
    sequence: [50, 42, 34, 26, 18],
    commonDifference: -8,
    expectedStep: -8,
    functionInput: 9,
    twoStep: true,
    operator1: '×',
    operand1: 3,
    operator2: '+',
    operand2: 5,
    expectedOutput: 32,
    ruleDescription: 'Step: -8 | Function Output: 32',
    misconceptionTip: '💡 Decreasing step is 42 - 50 = -8. Function: (9 × 3) + 5 = 27 + 5 = 32.',
    mathExplanation: 'Sequence step = -8. Function output = 32.',
  },
  {
    id: 'r5-005',
    round: 5,
    skill: 'grand_prix_hybrid',
    difficulty: 'hard',
    title: 'Final Trophy Qualifier',
    instruction: 'Step 1: Step for 15, 24, 33, 42, ? (+9). Step 2: Run Input 10 through [×5 - 7].',
    sequence: [15, 24, 33, 42, 51],
    commonDifference: 9,
    expectedStep: 9,
    functionInput: 10,
    twoStep: true,
    operator1: '×',
    operand1: 5,
    operator2: '-',
    operand2: 7,
    expectedOutput: 43,
    ruleDescription: 'Step: +9 | Function Output: 43',
    misconceptionTip: '💡 24 - 15 = 9. Function: (10 × 5) - 7 = 50 - 7 = 43.',
    mathExplanation: 'Sequence step = +9. Function output = 43.',
  },
];

// Helper to get challenges by round with fallback
export function getChallengesForRound(round: RoundNumber, difficulty?: string): SequenceChallenge[] {
  const filtered = PATTERN_CHALLENGE_BANK.filter((c) => c.round === round);
  if (filtered.length === 0) return PATTERN_CHALLENGE_BANK;
  return filtered;
}

// Generate an on-the-fly programmatic challenge for unlimited gameplay variety
export function generateDynamicChallenge(round: RoundNumber, seed: number): SequenceChallenge {
  const baseSteps = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, -2, -3, -4, -5, -6, -7, -8];
  const step = baseSteps[Math.abs(seed) % baseSteps.length];
  const start = step > 0 ? (seed % 10) + 2 : 50 + (seed % 30);
  const seq = [start, start + step, start + step * 2, start + step * 3, start + step * 4];

  if (round === 1) {
    return {
      id: `dyn-r1-${seed}`,
      round: 1,
      skill: 'sequence_step',
      difficulty: Math.abs(step) > 7 ? 'hard' : 'medium',
      title: `Grand Prix Sector Pattern (${step > 0 ? `+${step}` : step})`,
      instruction: 'Determine the constant step rule to extend the track segment.',
      sequence: seq,
      missingIndex: 4,
      commonDifference: step,
      expectedStep: step,
      expectedNextTerm: seq[4],
      ruleDescription: `${step > 0 ? `Add ${step}` : `Subtract ${Math.abs(step)}`} each step`,
      misconceptionTip: `💡 Difference: Subtract adjacent terms (${seq[1]} - ${seq[0]} = ${step}).`,
      mathExplanation: `Common difference is ${step > 0 ? `+${step}` : step}. Term 5 is ${seq[4]}.`,
    };
  }

  if (round === 2) {
    return {
      id: `dyn-r2-${seed}`,
      round: 2,
      skill: 'sequence_builder',
      difficulty: 'medium',
      title: `Track Builder Path (${start} → ${seq[4]})`,
      instruction: `Configure the Track Builder with Start = ${start}, Step = ${step > 0 ? `+${step}` : step}.`,
      sequence: seq,
      startValue: start,
      commonDifference: step,
      expectedStep: step,
      expectedNextTerm: seq[4],
      ruleDescription: `Start ${start}, step ${step}`,
      misconceptionTip: `💡 Start with ${start} and apply step ${step > 0 ? `+${step}` : step}.`,
      mathExplanation: `Sequence is ${seq.join(', ')}.`,
    };
  }

  if (round === 3) {
    const input = (seed % 8) + 3;
    const mult = (seed % 4) + 2;
    const add = (seed % 6) + 1;
    const output = input * mult + add;
    return {
      id: `dyn-r3-${seed}`,
      round: 3,
      skill: 'function_machine',
      difficulty: 'medium',
      title: `Turbo Machine [×${mult} + ${add}]`,
      instruction: `Input capsule [${input}] enters [×${mult} + ${add}]. Compute output.`,
      functionInput: input,
      twoStep: true,
      operator1: '×',
      operand1: mult,
      operator2: '+',
      operand2: add,
      expectedOutput: output,
      ruleDescription: `Input × ${mult} + ${add}`,
      misconceptionTip: `💡 Multiply first (${input} × ${mult} = ${input * mult}), then add ${add}.`,
      mathExplanation: `f(${input}) = (${input} × ${mult}) + ${add} = ${output}.`,
    };
  }

  if (round === 4) {
    const input = (seed % 6) + 3;
    const mult = (seed % 5) + 2;
    const output = input * mult;
    return {
      id: `dyn-r4-${seed}`,
      round: 4,
      skill: 'function_repair',
      difficulty: 'medium',
      title: `Machine Calibration ${input} → [ ? ] → ${output}`,
      instruction: `Configure the operator wheel to transform ${input} into ${output}.`,
      functionInput: input,
      functionOutput: output,
      expectedOperator: '×',
      expectedOperand: mult,
      ruleDescription: `Operator: ×, Value: ${mult}`,
      misconceptionTip: `💡 Reverse operation: ${output} ÷ ${input} = ${mult}. Rule is ×${mult}.`,
      mathExplanation: `${input} × ${mult} = ${output}. Rule is ×${mult}.`,
    };
  }

  // Round 5: Hybrid
  const input5 = (seed % 5) + 4;
  const mult5 = 2 + (seed % 3);
  const add5 = 1 + (seed % 4);
  const out5 = input5 * mult5 + add5;
  return {
    id: `dyn-r5-${seed}`,
    round: 5,
    skill: 'grand_prix_hybrid',
    difficulty: 'hard',
    title: `Championship Circuit (${step > 0 ? `+${step}` : step} & [×${mult5} + ${add5}])`,
    instruction: `Step 1: Step for ${seq.slice(0, 4).join(', ')} (${step > 0 ? `+${step}` : step}). Step 2: Input ${input5} in [×${mult5} + ${add5}].`,
    sequence: seq,
    commonDifference: step,
    expectedStep: step,
    functionInput: input5,
    twoStep: true,
    operator1: '×',
    operand1: mult5,
    operator2: '+',
    operand2: add5,
    expectedOutput: out5,
    ruleDescription: `Step: ${step > 0 ? `+${step}` : step} | Output: ${out5}`,
    misconceptionTip: `💡 Step: ${seq[1]} - ${seq[0]} = ${step}. Function: (${input5} × ${mult5}) + ${add5} = ${out5}.`,
    mathExplanation: `Step is ${step}, and function output is ${out5}.`,
  };
}
